#!/usr/bin/env python3
"""Generate HKICPA exam questions - 10,000 total (5000 AC + 5000 QE)"""
import json, os

# ============ AC MODULE (Accounting) ============
ac_topics = {
    "HKAS/HKFRS Standards": {
        "zh": "香港會計準則/財務報告準則",
        "questions": [
            ("Under HKAS 16, property, plant and equipment should be measured at:", "根據HKAS 16，物業、廠房及設備應計量為：", ["Cost less accumulated depreciation and impairment", "Fair value only", "Replacement cost", "Net realizable value"], ["成本減累計折舊和減值", "僅公允價值", "重置成本", "可變現淨值"], 0, "HKAS 16 requires PPE to be carried at cost less accumulated depreciation and accumulated impairment losses, with subsequent measurement options.", "HKAS 16要求物業、廠房及設備以成本減累計折舊和累計減值損失計量，並提供後續計量選項。"),
            ("Revenue from contracts with customers under HKFRS 15 is recognized when:", "根據HKFRS 15，客戶合同收入在以下時間確認：", ["Control of goods or services transfers to the customer", "Cash is received", "The invoice is issued", "The contract is signed"], ["商品或服務的控制權轉移給客戶時", "收到現金時", "發出發票時", "簽署合同時"], 0, "HKFRS 15 uses a 5-step model: identify contract, identify performance obligations, determine transaction price, allocate price, recognize revenue when obligations are satisfied.", "HKFRS 15採用五步法模型：識別合同、識別履約義務、確定交易價格、分配價格、在義務履行時確認收入。"),
            ("HKAS 36 requires impairment testing when:", "HKAS 36要求在以下情況進行減值測試：", ["There are indicators of impairment", "Only at year-end", "Only when auditors request it", "Only for tangible assets"], ["有減值跡象時", "僅在年末", "僅在審計師要求時", "僅對有形資產"], 0, "HKAS 36 requires impairment testing whenever there are indicators of impairment, and annually for goodwill and intangible assets with indefinite useful lives.", "HKAS 36要求在有減值跡象時進行減值測試，並對商譽和使用壽命不確定的無形資產每年進行測試。"),
            ("Under HKAS 12, deferred tax liabilities arise from:", "根據HKAS 12，遞延稅項負債產生於：", ["Taxable temporary differences", "Deductible temporary differences", "Permanent differences", "Tax losses carried forward"], ["應稅暫時性差異", "可抵扣暫時性差異", "永久性差異", "結轉稅務虧損"], 0, "Deferred tax liabilities arise from taxable temporary differences—the difference between carrying amount and tax base of assets/liabilities that will result in taxable amounts in future periods.", "遞延稅項負債產生於應稅暫時性差異——資產/負債的賬面價值與稅基之間的差異，將在未來期間產生應稅金額。"),
            ("HKFRS 16 Leases requires lessees to recognize:", "HKFRS 16租賃要求承租人確認：", ["A right-of-use asset and lease liability for most leases", "Only an expense in profit or loss", "Only a lease liability", "Nothing for operating leases"], ["對大多數租賃確認使用權資產和租賃負債", "僅在損益中確認費用", "僅確認租賃負債", "對經營租賃無需確認"], 0, "HKFRS 16 eliminates the operating/finance lease distinction for lessees, requiring a right-of-use asset and lease liability on the balance sheet for most leases.", "HKFRS 16取消了承租人的經營/融資租賃區別，要求對大多數租賃在資產負債表上確認使用權資產和租賃負債。"),
            ("HKAS 38 requires internally generated goodwill to be:", "HKAS 38要求內部產生的商譽：", ["Recognized as an expense, not as an asset", "Recognized as an intangible asset", "Disclosed in notes only", "Measured at fair value"], ["確認為費用而非資產", "確認為無形資產", "僅在附註中披露", "按公允價值計量"], 0, "HKAS 38 explicitly prohibits recognizing internally generated goodwill as an asset. Expenditure on internally generated intangibles is expensed unless it meets specific criteria.", "HKAS 38明確禁止將內部產生的商譽確認為資產。除非符合特定條件，否則內部產生的無形資產支出計入費用。"),
            ("Under HKAS 21, functional currency is defined as:", "根據HKAS 21，功能貨幣定義為：", ["The currency of the primary economic environment in which the entity operates", "The reporting currency of the parent", "The currency in which transactions are denominated", "Always the local currency"], ["實體經營所處主要經濟環境的貨幣", "母公司的報告貨幣", "交易計價的貨幣", "始終為當地貨幣"], 0, "Functional currency is determined by the primary economic environment considering: currency that mainly influences sales prices, currency of costs, and currency that funds activities.", "功能貨幣根據主要經濟環境確定，考慮主要影響銷售價格的貨幣、成本的貨幣和為活動提供資金的貨幣。"),
            ("HKFRS 9 Financial Instruments classifies financial assets based on:", "HKFRS 9金融工具根據以下對金融資產進行分類：", ["The entity's business model and contractual cash flow characteristics", "The legal form of the instrument", "The credit rating of the issuer", "The maturity date only"], ["實體的業務模式和合同現金流量特徵", "工具的法律形式", "發行人的信用評級", "僅到期日"], 0, "HKFRS 9 uses a two-step classification: 1) business model test (hold to collect, hold to collect and sell, trading), 2) SPPI test on contractual cash flows.", "HKFRS 9使用兩步分類法：1）業務模式測試（持有收取、持有收取和出售、交易），2）對合同現金流量的SPPI測試。"),
            ("HKAS 37 Provisions requires a provision to be recognized when:", "HKAS 37撥備要求在以下情況確認撥備：", ["There is a present obligation from past events, probable outflow, and reliable estimate", "Management decides to set aside reserves", "There is any uncertainty about future events", "The company wants to smooth earnings"], ["有源於過往事件的現有義務、可能流出及可靠估算", "管理層決定撥出儲備", "未來事件存在任何不確定性", "公司希望平滑收益"], 0, "HKAS 37 requires recognition when: present obligation from past event, probable outflow of resources, and reliable estimate. All three conditions must be met.", "HKAS 37要求在以下情況確認：源於過往事件的現有義務、資源可能流出以及可靠估算。三個條件必須同時滿足。"),
            ("Under HKFRS 3 Business Combinations, goodwill is:", "根據HKFRS 3企業合併，商譽是：", ["The excess of consideration transferred over the fair value of identifiable net assets acquired", "Always positive", "The book value of the acquiree's assets", "Equal to the purchase price"], ["轉移的對價超過所購可識別淨資產公允價值的部分", "始終為正", "被收購方資產的賬面價值", "等於購買價格"], 0, "Goodwill = Consideration transferred + NCI fair value + previously held interest - Fair value of identifiable net assets. It can be negative (bargain purchase, recognized in P&L).", "商譽 = 轉移的對價 + 非控制權益公允價值 + 此前持有的權益 - 可識別淨資產公允價值。可以為負（廉價購買，在損益中確認）。"),
        ]
    },
    "Financial Reporting": {
        "zh": "財務報告",
        "questions": [
            ("The statement of financial position presents:", "財務狀況表呈報：", ["Assets, liabilities, and equity at a point in time", "Revenue and expenses over a period", "Cash flows over a period", "Only current assets and liabilities"], ["某一時間點的資產、負債和權益", "某段期間的收入和費用", "某段期間的現金流量", "僅流動資產和負債"], 0, "The statement of financial position (balance sheet) shows the financial position at a specific date—assets = liabilities + equity.", "財務狀況表（資產負債表）顯示特定日期的財務狀況——資產 = 負債 + 權益。"),
            ("Consolidation under HKFRS 10 requires:", "根據HKFRS 10，合併要求：", ["Control over the investee to determine consolidation", "50% ownership threshold", "Board representation only", "Management agreement"], ["對被投資方的控制權以確定合併", "50%所有權門檻", "僅董事會代表", "管理協議"], 0, "HKFRS 10 defines control as power over the investee, exposure to variable returns, and ability to use power to affect returns. Not just ownership percentage.", "HKFRS 10將控制定義為對被投資方的權力、面臨可變回報的風險以及運用權力影響回報的能力。不僅僅是所有權百分比。"),
            ("Non-controlling interests (NCI) in consolidated financial statements represent:", "合併財務報表中的非控制權益代表：", ["Equity in subsidiaries not attributable to the parent", "The parent's share of subsidiary profits", "Intercompany transactions", "Minority debt holders' claims"], ["不能歸屬於母公司的子公司權益", "母公司享有的子公司利潤份額", "公司間交易", "少數債務持有人的索償"], 0, "NCI represents the portion of equity and profit/loss of subsidiaries not attributable to the parent, presented separately in the consolidated statement.", "非控制權益代表不能歸屬於母公司的子公司權益和損益份額，在合併報表中單獨列示。"),
            ("Under HKAS 19, employee benefits include short-term benefits, post-employment benefits, and:", "根據HKAS 19，員工福利包括短期福利、離職後福利和：", ["Other long-term employee benefits and termination benefits", "Only salaries", "Dividends paid to employees", "Government subsidies"], ["其他長期員工福利和終止福利", "僅工資", "支付給員工的股息", "政府補貼"], 0, "HKAS 19 covers: short-term benefits (salaries, leave), post-employment benefits (pensions), other long-term benefits (long-service leave), and termination benefits.", "HKAS 19涵蓋：短期福利（工資、休假）、離職後福利（退休金）、其他長期福利（長期服務假）和終止福利。"),
            ("The statement of changes in equity shows:", "權益變動表顯示：", ["All changes in equity including comprehensive income, dividends, and equity transactions", "Only profit for the period", "Only share capital changes", "Cash movements in equity"], ["權益的所有變動，包括綜合收益、股息和權益交易", "僅本期利潤", "僅股本變動", "權益的現金變動"], 0, "Statement of changes in equity reconciles opening to closing equity: profit/loss, other comprehensive income, dividends, share issuances/buybacks, and other equity movements.", "權益變動表將期初權益調節至期末：損益、其他綜合收益、股息、股份發行/回購及其他權益變動。"),
            ("HKFRS 8 Operating Segments requires disclosure of segments based on:", "HKFRS 8經營分部要求基於以下披露分部：", ["The internal reports reviewed by the chief operating decision maker", "Geographic regions only", "Product lines only", "Legal entities"], ["首席經營決策者審查的內部報告", "僅地理區域", "僅產品線", "法律實體"], 0, "HKFRS 8 uses a 'management approach'—segments are identified based on how CODM reviews performance and allocates resources internally.", "HKFRS 8採用「管理層方法」——分部根據首席經營決策者如何審查績效和內部分配資源來識別。"),
            ("Under HKAS 7, investing activities in the cash flow statement include:", "根據HKAS 7，現金流量表中的投資活動包括：", ["Acquisition and disposal of long-term assets and investments", "Borrowing and repaying debt", "Dividends paid to shareholders", "Operating cash receipts"], ["購置和處置長期資產和投資", "借款和償還債務", "支付給股東的股息", "經營現金收入"], 0, "HKAS 7 investing activities: acquiring/disposing PPE, intangibles, investments; lending and collecting loans; payments for futures/forwards (not for trading).", "HKAS 7投資活動：購置/處置物業廠房設備、無形資產、投資；貸款和收回貸款；期貨/遠期合約付款（非交易用途）。"),
            ("Earnings per share (EPS) under HKAS 33 is calculated as:", "根據HKAS 33，每股收益計算為：", ["Profit attributable to ordinary shareholders / Weighted average ordinary shares", "Total profit / Total shares issued", "Revenue / Number of shareholders", "Net assets / Number of shares"], ["歸屬於普通股東的利潤 / 加權平均普通股股數", "總利潤 / 已發行股份總數", "收入 / 股東人數", "淨資產 / 股份數"], 0, "Basic EPS = (Profit - Preference dividends) / Weighted average number of ordinary shares outstanding during the period.", "基本每股收益 = （利潤 - 優先股股息）/ 期間加權平均普通股股數。"),
            ("Related party disclosures under HKAS 24 require:", "根據HKAS 24，關聯方披露要求：", ["Disclosure of relationships, transactions, and outstanding balances with related parties", "Only disclosure of director salaries", "No disclosure if transactions are at arm's length", "Disclosure only of government-related entities"], ["披露與關聯方的關係、交易和未結餘額", "僅披露董事薪酬", "如交易按公平原則進行則無需披露", "僅披露政府關聯實體"], 0, "HKAS 24 requires disclosure of: relationship nature, transactions, outstanding balances, commitments, and key management compensation for transparency.", "HKAS 24要求披露：關係性質、交易、未結餘額、承諾和關鍵管理人員薪酬以確保透明度。"),
            ("Under HKAS 40, investment property may be measured using:", "根據HKAS 40，投資物業可使用以下計量：", ["Either the cost model or the fair value model", "Only the cost model", "Only the revaluation model", "Only the fair value model"], ["成本模式或公允價值模式", "僅成本模式", "僅重估模式", "僅公允價值模式"], 0, "HKAS 40 allows entities to choose: cost model (like PPE) or fair value model (changes in fair value recognized in P&L). The choice applies to all investment properties.", "HKAS 40允許實體選擇：成本模式（如物業廠房設備）或公允價值模式（公允價值變動在損益中確認）。選擇適用於所有投資物業。"),
        ]
    },
    "Consolidation": {
        "zh": "合併",
        "questions": [
            ("Intragroup transactions in consolidation are:", "合併中的集團內部交易：", ["Eliminated in full to avoid double-counting", "Included at 50%", "Only disclosed in notes", "Adjusted for tax only"], ["全額消除以避免重複計算", "按50%計入", "僅在附註中披露", "僅作稅務調整"], 0, "All intragroup transactions (sales, loans, dividends, unrealized profits) must be eliminated in full during consolidation to present the group as a single economic entity.", "所有集團內部交易（銷售、貸款、股息、未實現利潤）在合併時必須全額消除，以將集團呈報為單一經濟實體。"),
            ("When a parent loses control of a subsidiary, the parent:", "當母公司失去對子公司的控制權時，母公司：", ["Derecognizes all assets/liabilities, recognizes any retained interest at fair value, and recognizes gain/loss in P&L", "Keeps the subsidiary on the books", "Only discloses the loss of control", "Records no journal entries"], ["終止確認所有資產/負債，將任何保留權益按公允價值確認，並在損益中確認收益/損失", "將子公司保留在賬上", "僅披露失去控制權", "不記錄會計分錄"], 0, "On loss of control: derecognize all assets/liabilities, recognize retained interest at fair value, reclassify any amounts in OCI to P&L, and recognize the difference as gain/loss.", "失去控制權時：終止確認所有資產/負債，將保留權益按公允價值確認，將OCI中的金額重分類至損益，並將差額確認為收益/損失。"),
            ("Business combination achieved in stages (step acquisition) under HKFRS 3 requires:", "根據HKFRS 3，分階段實現的企業合併（逐步收購）要求：", ["Remasuring previously held equity interest to fair value at acquisition date", "Keeping the previous investment at original cost", "Ignoring the previous investment", "Only recognizing new shares issued"], ["在收購日將先前持有的股權重新計量至公允價值", "將先前投資保持在原始成本", "忽略先前投資", "僅確認新發行的股份"], 0, "In step acquisition: remeasure previously held equity interest to fair value at control date, recognize gain/loss in P&L, then calculate goodwill.", "逐步收購中：在控制日將先前持有的股權重新計量至公允價值，在損益中確認收益/損失，然後計算商譽。"),
            ("Non-controlling interest (NCI) can be measured at:", "非控制權益可以按以下計量：", ["Fair value or proportionate share of identifiable net assets", "Only at historical cost", "Zero", "The subsidiary's book value"], ["公允價值或可識別淨資產的應佔份額", "僅按歷史成本", "零", "子公司的賬面價值"], 0, "HKFRS 3 allows two methods for NCI: 1) fair value (full goodwill method), or 2) proportionate share of acquiree's identifiable net assets (partial goodwill method).", "HKFRS 3允許兩種非控制權益計量方法：1）公允價值（完全商譽法），或2）被收購方可識別淨資產的應佔份額（部分商譽法）。"),
            ("Consolidation adjustments for unrealized profit on intragroup sales of inventory require:", "對集團內部存貨銷售的未實現利潤進行合併調整需要：", ["Eliminating the profit and adjusting inventory to cost", "Only eliminating the revenue", "Only eliminating the cost of sales", "No adjustment if sold to external parties"], ["消除利潤並將存貨調整至成本", "僅消除收入", "僅消除銷售成本", "如已出售給外部方則無需調整"], 0, "Unrealized profit on intragroup inventory sales must be eliminated. If inventory is still held at period end, reduce inventory value and cost of sales/COGS.", "集團內部存貨銷售的未實現利潤必須消除。如存貨在期末仍持有，則減少存貨價值和銷售成本。"),
            ("When translating a foreign subsidiary's financial statements, exchange differences are:", "在折算外國子公司的財務報表時，匯率差異：", ["Recognized in other comprehensive income (OCI)", "Recognized in profit or loss", "Ignored until disposal", "Adjusted against share capital"], ["在其他綜合收益（OCI）中確認", "在損益中確認", "在處置前忽略", "調整股本"], 0, "Under HKAS 21, translation differences from converting a foreign operation's financial statements are recognized in OCI and accumulated in a translation reserve.", "根據HKAS 21，折算外國經營實體財務報表產生的匯率差異在OCI中確認，並累計在折算儲備中。"),
            ("A joint arrangement under HKFRS 11 is classified as either:", "根據HKFRS 11，合營安排分類為：", ["A joint operation or a joint venture", "A subsidiary or an associate", "A partnership or a corporation", "A domestic or foreign arrangement"], ["合營經營或合營企業", "子公司或聯營企業", "合夥企業或公司", "國內或國外安排"], 0, "HKFRS 11 classifies joint arrangements as: joint operations (rights to assets, obligations for liabilities) or joint ventures (rights to net assets).", "HKFRS 11將合營安排分類為：合營經營（資產權利、負債義務）或合營企業（淨資產權利）。"),
            ("Goodwill recognized on consolidation is:", "合併中確認的商譽：", ["Not amortized but tested for impairment annually", "Amortized over 20 years", "Written off immediately against reserves", "Never tested for impairment"], ["不攤銷但每年進行減值測試", "按20年攤銷", "立即沖銷儲備", "從不進行減值測試"], 0, "Under HKFRS 3, goodwill is not amortized. It is tested for impairment at least annually, or more frequently if there are indicators of impairment.", "根據HKFRS 3，商譽不攤銷。至少每年進行減值測試，如有減值跡象則更頻繁測試。"),
            ("Associate companies under HKAS 28 are accounted for using:", "根據HKAS 28，聯營公司使用以下方法核算：", ["The equity method", "Full consolidation", "Cost method only", "Fair value through profit or loss"], ["權益法", "完全合併", "僅成本法", "公允價值計入損益"], 0, "Associates (20-50% ownership or significant influence) are accounted for using the equity method: investor's share of investee's P&L and OCI is recognized.", "聯營公司（20-50%所有權或重大影響力）使用權益法核算：確認投資者享有的被投資方損益和OCI份額。"),
            ("Push-down accounting refers to:", "下推會計是指：", ["Recording the fair values of acquisition at the subsidiary's standalone level", "Pushing costs down to lower departments", "Allocating overhead to products", "Reducing asset values to market"], ["在子公司獨立層面記錄收購的公允價值", "將成本下推至較低部門", "將間接費用分配至產品", "將資產價值減至市場"], 0, "Push-down accounting establishes a new basis for the subsidiary's standalone financial statements by recording acquisition-date fair values in the subsidiary's books.", "下推會計通過在子公司賬簿中記錄收購日公允價值，為子公司的獨立財務報表建立新基礎。"),
        ]
    },
    "Taxation": {
        "zh": "稅務",
        "questions": [
            ("Hong Kong profits tax is charged on:", "香港利得稅徵收於：", ["Profits arising in or derived from Hong Kong", "Worldwide profits of all companies", "Only manufacturing profits", "Revenue minus expenses globally"], ["在香港產生或得自香港的利潤", "所有公司的全球利潤", "僅製造業利潤", "全球收入減支出"], 0, "Hong Kong operates a territorial tax system—only profits arising in or derived from Hong Kong are subject to profits tax, regardless of where the company is incorporated.", "香港實行地域來源稅制——僅在香港產生或得自香港的利潤須繳納利得稅，不論公司在何處註冊。"),
            ("The current Hong Kong profits tax rate for corporations is:", "目前香港公司利得稅率為：", ["8.25% on the first HK$2 million, 16.5% on the remainder", "A flat 16.5%", "A flat 8.25%", "20% on all profits"], ["首200萬港元為8.25%，其餘為16.5%", "統一16.5%", "統一8.25%", "所有利潤為20%"], 0, "Two-tiered rates (2018/19 onwards): 8.25% on first HK$2M of assessable profits, 16.5% on the remainder. For unincorporated businesses: 7.5% and 15%.", "兩級稅率（2018/19年起）：首200萬港元應評稅利潤8.25%，其餘16.5%。非法團業務：7.5%和15%。"),
            ("Hong Kong salaries tax is computed on:", "香港薪俸稅按以下方式計算：", ["Net chargeable income at progressive rates or net income at standard rate, whichever is lower", "Gross income at a flat rate", "Only basic salary", "Net income minus all expenses"], ["按累進稅率計算的應評稅淨收入或按標準稅率計算的淨收入，以較低者為準", "按統一稅率計算的總收入", "僅基本工資", "淨收入減所有支出"], 0, "Salaries tax = lesser of: 1) progressive rates on net chargeable income (after allowances), 2) standard rate (15%) on net income (before allowances).", "薪俸稅 = 以下較低者：1）按累進稅率計算的應評稅淨收入（扣除免稅額後），2）按標準稅率（15%）計算的淨收入（扣除免稅額前）。"),
            ("Depreciation allowances in Hong Kong for commercial buildings are:", "香港商業樓宇的折舊免稅額為：", ["Initial allowance of 20% and annual allowance of 4%", "100% in the first year", "No depreciation allowances", "25% per year"], ["初期免稅額20%和每年免稅額4%", "第一年100%", "無折舊免稅額", "每年25%"], 0, "Commercial buildings: initial allowance 20% of construction cost, annual allowance 4% of construction cost. Industrial buildings: 20% initial, 4% annual.", "商業樓宇：初期免稅額為建造成本的20%，每年免稅額為建造成本的4%。工業樓宇：初期20%，每年4%。"),
            ("Under Hong Kong tax law, plant and machinery depreciation is claimed via:", "根據香港稅務法例，廠房及機器折舊通過以下方式申索：", ["Initial allowance of 60% and annual allowance at prescribed rates", "Straight-line method only", "No depreciation allowed", "10% flat rate for all assets"], ["初期免稅額60%和按規定稅率的每年免稅額", "僅直線法", "不允許折舊", "所有資產統一10%"], 0, "P&M: 60% initial allowance in first year, then annual allowances (10%-30% reducing balance depending on asset class).", "廠房及機器：第一年60%初期免稅額，然後每年免稅額（按資產類別10%-30%遞減餘額）。"),
            ("A Hong Kong tax loss can be:", "香港稅務虧損可以：", ["Carried forward indefinitely to offset future profits of the same trade", "Carried back to offset prior year profits", "Transferred to group companies", "Used to claim a tax refund"], ["無限期結轉以抵銷同一業務的未來利潤", "結轉以抵銷以前年度利潤", "轉讓給集團公司", "用於申請退稅"], 0, "Hong Kong tax losses can be carried forward indefinitely to offset future profits from the same trade, profession, or business. No group relief or carry-back.", "香港稅務虧損可無限期結轉以抵銷同一行業、專業或業務的未來利潤。無集團稅務寬免或結轉回撥。"),
            ("The Inland Revenue Department (IRD) assesses tax based on:", "稅務局根據以下評稅：", ["The previous year's basis period (preceding year basis)", "The current year's estimated profits", "The average of the last 3 years", "Cash received during the year"], ["上一年度的評稅基期（上年度基礎）", "本年度預計利潤", "過去3年的平均值", "年內收到的現金"], 0, "Hong Kong uses the preceding year basis: tax for a year of assessment is based on the profits of the year ending in that assessment year.", "香港採用上年度基礎：某一評稅年度的稅項基於在該評稅年度內結束的年度利潤。"),
            ("Stamp duty in Hong Kong is payable on:", "香港印花稅須繳付於：", ["Stock transfers, property transfers, and leases", "Only property purchases", "Only share transfers", "Income from employment"], ["股票轉讓、物業轉讓和租約", "僅物業購買", "僅股份轉讓", "就業收入"], 0, "Hong Kong stamp duty applies to: stock transfers (0.13% each side), property transfers (up to 15%), and leases (0.25-1% of rental value).", "香港印花稅適用於：股票轉讓（每方0.13%）、物業轉讓（最高15%）和租約（租金價值的0.25%-1%）。"),
            ("Double taxation agreements (DTAs) signed by Hong Kong primarily aim to:", "香港簽訂的雙重徵稅協定主要旨在：", ["Prevent double taxation and provide certainty on tax treatment", "Increase tax rates", "Eliminate all taxes for foreign companies", "Transfer taxing rights to Hong Kong only"], ["防止雙重徵稅並為稅務處理提供確定性", "提高稅率", "取消外國公司的所有稅項", "僅將徵稅權轉移給香港"], 0, "DTAs allocate taxing rights between jurisdictions, provide reduced withholding tax rates, and offer mechanisms for resolving tax disputes to prevent double taxation.", "DTAs在稅收管轄區之間分配徵稅權、提供較低預扣稅率，並提供解決稅務爭議的機制以防止雙重徵稅。"),
            ("Anti-avoidance provisions under Hong Kong's Inland Revenue Ordinance allow the IRD to:", "香港《稅務條例》中的反避稅條款允許稅務局：", ["Recompute profits to counteract tax avoidance schemes", "Only issue warnings", "Only audit large companies", "Increase tax rates arbitrarily"], ["重新計算利潤以抵消避稅計劃", "僅發出警告", "僅審計大公司", "任意提高稅率"], 0, "Section 61 allows IRD to disregard/modify transactions that are artificial, fictitious, or designed to avoid tax. Section 61A targets transactions with tax avoidance as the dominant purpose.", "第61條允許稅務局無視/修改人為、虛構或旨在避稅的交易。第61A條針對以避稅為主要目的的交易。"),
        ]
    },
    "Auditing": {
        "zh": "審計",
        "questions": [
            ("The objective of a statutory audit is:", "法定審計的目標是：", ["To express an opinion on whether financial statements give a true and fair view", "To detect all fraud", "To prepare financial statements", "To minimize tax liability"], ["對財務報表是否真實公正地反映情況發表意見", "偵測所有欺詐", "編製財務報表", "盡量減少稅務負擔"], 0, "The auditor's responsibility is to express an opinion on whether the financial statements are prepared, in all material respects, in accordance with the applicable financial reporting framework.", "審計師的責任是對財務報表是否在所有重大方面按照適用的財務報告框架編製發表意見。"),
            ("Materiality in auditing is defined as:", "審計中的重要性定義為：", ["Misstatements that could influence the economic decisions of users", "Any error found during audit", "The total audit fee", "The size of the company"], ["可能影響使用者經濟決策的錯報", "審計期間發現的任何錯誤", "審計費用總額", "公司規模"], 0, "Materiality considers the magnitude and nature of misstatements, individually or in aggregate, that could reasonably be expected to influence decisions of users of financial statements.", "重要性考慮錯報的規模和性質（單獨或匯總），合理預期可能影響財務報表使用者的決策。"),
            ("The audit risk model is:", "審計風險模型為：", ["Audit risk = Inherent risk × Control risk × Detection risk", "Audit risk = Financial risk × Business risk", "Audit risk = Materiality × Sampling risk", "Audit risk = Fraud risk × Error risk"], ["審計風險 = 固有風險 × 控制風險 × 偵查風險", "審計風險 = 財務風險 × 經營風險", "審計風險 = 重要性 × 抽樣風險", "審計風險 = 欺詐風險 × 錯誤風險"], 0, "AR = IR × CR × DR. The auditor assesses inherent and control risk, then determines acceptable detection risk to keep overall audit risk at an acceptable level.", "審計風險 = 固有風險 × 控制風險 × 偵查風險。審計師評估固有和控制風險，然後確定可接受的偵查風險以將整體審計風險保持在可接受水平。"),
            ("ISA 240 requires the auditor to:", "ISA 240要求審計師：", ["Consider the risk of material misstatement due to fraud throughout the audit", "Guarantee that no fraud exists", "Investigate all employees for fraud", "Report all suspected fraud to the police"], ["在整個審計過程中考慮因欺詐導致重大錯報的風險", "保證不存在欺詐", "調查所有員工的欺詐行為", "向警方報告所有涉嫌欺詐"], 0, "ISA 240 requires professional skepticism about fraud, assessment of fraud risk factors (incentive, opportunity, rationalization), and appropriate responses to assessed risks.", "ISA 240要求對欺詐保持專業懷疑態度，評估欺詐風險因素（動機、機會、合理化），並對評估的風險作出適當回應。"),
            ("Test of controls in auditing involves:", "審計中的控制測試涉及：", ["Evaluating whether internal controls are operating effectively", "Testing every transaction", "Calculating the company's tax liability", "Preparing the audit report"], ["評估內部控制是否有效運作", "測試每筆交易", "計算公司的稅務負擔", "編製審計報告"], 0, "Tests of controls assess whether key internal controls are designed effectively and operating as intended throughout the period, determining if substantive testing can be reduced.", "控制測試評估關鍵內部控制是否設計有效並在整個期間按預期運作，決定是否可以減少實質性測試。"),
            ("Substantive procedures include:", "實質性程序包括：", ["Tests of details and substantive analytical procedures", "Only walkthroughs", "Only inquiry of management", "Only reading the financial statements"], ["細節測試和實質性分析程序", "僅穿行測試", "僅詢問管理層", "僅閱讀財務報表"], 0, "Substantive procedures: 1) Tests of details (vouching, tracing, confirming, observing), 2) Substantive analytical procedures (ratio analysis, trend analysis, reasonableness tests).", "實質性程序：1）細節測試（核證、追查、函證、觀察），2）實質性分析程序（比率分析、趨勢分析、合理性測試）。"),
            ("An external auditor's independence requirement means:", "外部審計師的獨立性要求意味著：", ["The auditor must be free from bias, conflicts of interest, and undue influence", "The auditor cannot have any friends at the company", "The auditor must work alone", "The auditor cannot charge fees"], ["審計師必須不受偏見、利益衝突和不當影響", "審計師不能在公司有任何朋友", "審計師必須單獨工作", "審計師不能收費"], 0, "Independence requires: independence of mind (mental state) and independence in appearance (avoiding facts that a reasonable third party would question).", "獨立性要求：思想獨立（心理狀態）和外觀獨立（避免合理第三方會質疑的事實）。"),
            ("Audit sampling is used when:", "審計抽樣在以下情況使用：", ["Testing a representative subset of a population when it is impractical to test all items", "Always for every audit procedure", "Only for cash transactions", "When the auditor is lazy"], ["當測試所有項目不切實際時測試總體的代表性子集", "對每個審計程序始終使用", "僅對現金交易", "當審計師偷懶時"], 0, "Sampling allows the auditor to draw conclusions about an entire population by testing a selection. Methods include statistical and non-statistical sampling.", "抽樣允許審計師通過測試選定項目來對整個總體得出結論。方法包括統計和非統計抽樣。"),
            ("The audit report under ISA 700 includes:", "根據ISA 700，審計報告包括：", ["Opinion, basis for opinion, key audit matters, and responsibilities sections", "Only the auditor's opinion", "Only financial statements", "A detailed list of all errors found"], ["意見、意見基礎、關鍵審計事項和責任部分", "僅審計師意見", "僅財務報表", "發現的所有錯誤的詳細清單"], 0, "ISA 700 requires: title, addressee, opinion, basis for opinion, key audit matters (KAM), going concern, other information, responsibilities, and signature.", "ISA 700要求：標題、收件人、意見、意見基礎、關鍵審計事項（KAM）、持續經營、其他信息、責任和簽名。"),
            ("Professional skepticism in auditing requires:", "審計中的專業懷疑態度要求：", ["A questioning mind and critical assessment of audit evidence", "Accepting all management explanations", "Assuming all clients are fraudulent", "Never trusting any documents"], ["質疑的心態和對審計證據的批判性評估", "接受所有管理層解釋", "假設所有客戶都欺詐", "永遠不信任任何文件"], 0, "Professional skepticism is an attitude of questioning, with a critical mind and alertness to conditions that may indicate possible misstatement, whether due to error or fraud.", "專業懷疑態度是一種質疑的態度，具有批判性思維和對可能表明錯報（無論因錯誤還是欺詐）的情況保持警覺。"),
        ]
    },
    "Corporate Finance": {
        "zh": "企業融資",
        "questions": [
            ("The weighted average cost of capital (WACC) is calculated as:", "加權平均資本成本計算為：", ["(E/V × Re) + (D/V × Rd × (1-T))", "E/V + D/V", "Re + Rd", "Earnings / Total assets"], ["（E/V × Re）+（D/V × Rd ×（1-T））", "E/V + D/V", "Re + Rd", "收益 / 總資產"], 0, "WACC = (E/V × Re) + (D/V × Rd × (1-T)), where E=equity value, D=debt value, V=E+D, Re=cost of equity, Rd=cost of debt, T=tax rate.", "WACC =（E/V × Re）+（D/V × Rd ×（1-T）），其中E=股權價值，D=債務價值，V=E+D，Re=股權成本，Rd=債務成本，T=稅率。"),
            ("Under Modigliani-Miller (with taxes), the value of a levered firm:", "根據Modigliani-Miller（含稅），有槓桿公司的價值：", ["Exceeds the value of an unlevered firm by the present value of the tax shield", "Equals the unlevered firm value", "Is less than the unlevered firm value", "Is independent of capital structure"], ["超過無槓桿公司的價值，差額為稅盾的現值", "等於無槓桿公司價值", "低於無槓桿公司價值", "與資本結構無關"], 0, "With taxes: VL = VU + PV(tax shield). The tax deductibility of interest creates a tax shield that increases firm value with leverage.", "含稅：VL = VU + PV（稅盾）。利息的稅務扣減創造了稅盾，使公司價值隨槓桿增加。"),
            ("The dividend discount model (DDM) values a share based on:", "股息貼現模型（DDM）基於以下對股份進行估值：", ["The present value of all future expected dividends", "The current share price", "The book value per share", "The company's total assets"], ["所有未來預期股息的現值", "當前股價", "每股賬面價值", "公司總資產"], 0, "DDM: P₀ = Σ(Dt / (1+r)^t). The intrinsic value equals the present value of all expected future dividends, discounted at the required rate of return.", "DDM：P₀ = Σ（Dt /（1+r）^t）。內在價值等於所有預期未來股息的現值，按要求回報率貼現。"),
            ("Capital asset pricing model (CAPM) states that the expected return is:", "資本資產定價模型（CAPM）指出預期回報為：", ["E(R) = Rf + β(E(Rm) - Rf)", "E(R) = Rf + Rm", "E(R) = Dividend / Price", "E(R) = Alpha + Beta"], ["E(R) = Rf + β(E(Rm) - Rf)", "E(R) = Rf + Rm", "E(R) = 股息 / 價格", "E(R) = Alpha + Beta"], 0, "CAPM: E(Ri) = Rf + βi(E(Rm) - Rf). Expected return equals risk-free rate plus beta times the market risk premium.", "CAPM：E(Ri) = Rf + βi（E(Rm) - Rf）。預期回報等於無風險利率加Beta乘以市場風險溢價。"),
            ("A share repurchase (buyback) typically:", "股份回購通常：", ["Increases earnings per share by reducing shares outstanding", "Decreases total equity", "Always increases the share price", "Reduces the company's cash to zero"], ["通過減少流通股增加每股收益", "減少總權益", "始終提高股價", "將公司現金減少至零"], 0, "Buybacks reduce shares outstanding, increasing EPS. They return cash to shareholders, may signal undervaluation, and are often tax-efficient compared to dividends.", "回購減少流通股，增加每股收益。向股東返還現金，可能表明價值被低估，且通常比股息更具稅務效率。"),
            ("An initial public offering (IPO) involves:", "首次公開招股涉及：", ["Offering shares to the public for the first time through a prospectus", "Selling the entire company", "Borrowing from the public", "Issuing bonds"], ["通過招股章程首次向公眾發售股份", "出售整個公司", "向公眾借款", "發行債券"], 0, "IPO = first public offering of shares. Process: appoint underwriters, file prospectus with regulator, roadshow, price allocation, listing on stock exchange.", "IPO = 首次公開發售股份。流程：委任保薦人、向監管機構提交招股章程、路演、定價分配、在證券交易所上市。"),
            ("The pecking order theory of capital structure suggests firms prefer:", "資本結構的優序融資理論認為公司偏好：", ["Internal financing first, then debt, then equity", "Equity first, then debt", "Debt first, then equity", "Equal amounts of debt and equity"], ["先內部融資，然後債務，然後股權", "先股權，然後債務", "先債務，然後股權", "等量的債務和股權"], 0, "Pecking order (Myers & Majluf): firms prefer internal funds → debt → equity, due to information asymmetry costs and adverse selection in external financing.", "優序融資（Myers和Majluf）：由於信息不對稱成本和外部融資中的逆向選擇，公司偏好內部資金→債務→股權。"),
            ("Mergers and acquisitions (M&A) synergies include:", "合併和收購的協同效應包括：", ["Revenue synergies, cost synergies, and financial synergies", "Only cost reductions", "Only revenue increases", "Only tax benefits"], ["收入協同效應、成本協同效應和財務協同效應", "僅成本削減", "僅收入增加", "僅稅務優惠"], 0, "M&A synergies: revenue (cross-selling, market access), cost (economies of scale, eliminating duplicates), financial (lower WACC, tax benefits, diversification).", "M&A協同效應：收入（交叉銷售、市場准入）、成本（規模經濟、消除重複）、財務（降低WACC、稅務優惠、多元化）。"),
            ("The debt-to-equity ratio measures:", "資產負債率衡量：", ["The proportion of debt financing relative to equity financing", "Total assets minus total liabilities", "The interest rate on debt", "The company's profitability"], ["債務融資相對於股權融資的比例", "總資產減總負債", "債務利率", "公司的盈利能力"], 0, "D/E ratio = Total Debt / Total Equity. Higher ratio indicates more leverage, higher financial risk, but potentially higher returns to equity holders.", "資產負債率 = 總債務 / 總權益。比率越高表示槓桿越大、財務風險越高，但對股權持有人的潛在回報也越高。"),
            ("Free cash flow to firm (FCFF) is calculated as:", "公司自由現金流計算為：", ["EBIT(1-T) + Depreciation - Capex - ΔWorking Capital", "Revenue - Expenses", "Net Income + Dividends", "Cash from operations only"], ["EBIT(1-T) + 折舊 - 資本支出 - 營運資本變動", "收入 - 支出", "淨收入 + 股息", "僅經營活動現金"], 0, "FCFF = EBIT(1-T) + D&A - Capex - ΔWC. It represents cash available to all capital providers (debt and equity holders) after operating expenses and investments.", "FCFF = EBIT(1-T) + 折舊攤銷 - 資本支出 - 營運資本變動。代表經營費用和投資後所有資本提供者（債務和股權持有人）可獲得的現金。"),
        ]
    },
}

# ============ QE MODULE ============
qe_topics = {
    "HK Taxation - Salaries Tax": {
        "zh": "香港稅務 — 薪俸稅",
        "questions": [
            ("Under Hong Kong salaries tax, which of the following is NOT assessable income?", "根據香港薪俸稅，以下哪項不屬於應評稅收入？", ["Capital gains from selling shares", "Salary and wages", "Bonuses and commissions", "Director's fees"], ["出售股份的資本收益", "薪金和工資", "花紅和佣金", "董事袍金"], 0, "Salaries tax covers all income from employment in HK: salary, bonuses, commissions, allowances, director's fees, and stock options. Capital gains are not taxed in HK.", "薪俸稅涵蓋所有在港就業收入：薪金、花紅、佣金、津貼、董事袍金和股票期權。香港不徵收資本利得稅。"),
            ("The personal allowance for a single taxpayer in Hong Kong (2024/25) is:", "香港單身納稅人（2024/25）的個人免稅額為：", ["HK$132,000", "HK$100,000", "HK$200,000", "HK$50,000"], ["132,000港元", "100,000港元", "200,000港元", "50,000港元"], 0, "The basic personal allowance for 2024/25 is HK$132,000. Married person's allowance is HK$264,000. Additional allowances for children, dependent parents, etc.", "2024/25年基本個人免稅額為132,000港元。已婚人士免稅額為264,000港元。另有子女、供養父母等額外免稅額。"),
            ("Hong Kong salaries tax progressive rates range from:", "香港薪俸稅累進稅率範圍為：", ["2% to 17%", "5% to 30%", "10% to 40%", "1% to 15%"], ["2%至17%", "5%至30%", "10%至40%", "1%至15%"], 0, "Progressive rates: 2% on first HK$50k, 6% on next HK$50k, 10% on next HK$50k, 14% on next HK$50k, 17% on remainder.", "累進稅率：首50,000港元2%，次50,000港元6%，次50,000港元10%，次50,000港元14%，其餘17%。"),
            ("Rental income from Hong Kong property is subject to:", "來自香港物業的租金收入須繳納：", ["Property tax at 15% of net assessable value", "Profits tax only", "Salaries tax", "No tax"], ["物業稅，按應評稅淨值的15%", "僅利得稅", "薪俸稅", "免稅"], 0, "Property tax = 15% of net assessable value (80% of rental income after rates paid by owner). Can be exempted if taxed under profits tax.", "物業稅 = 應評稅淨值的15%（租金收入的80%，扣除業主支付的差餉）。如已在利得稅下課稅則可豁免。"),
            ("An employee's mandatory MPF contribution is:", "員工的強制性公積金供款為：", ["5% of relevant income, subject to a cap of HK$1,500 per month", "10% of gross salary", "A flat HK$1,000 per month", "Voluntary with no requirement"], ["相關收入的5%，上限為每月1,500港元", "總薪金的10%", "統一每月1,000港元", "自願性，無要求"], 0, "Mandatory MPF: employee contributes 5% of relevant income (max HK$30k/month → HK$1,500 cap). Employer also contributes 5%. Self-employed contribute 5%.", "強制性公積金：員工供款相關收入的5%（最高30,000港元/月→上限1,500港元）。僱主亦供款5%。自僱人士供款5%。"),
            ("A housing benefit provided by an employer in Hong Kong is:", "香港僱主提供的房屋福利：", ["Taxable as a perquisite, with a deduction for rent paid", "Fully exempt from salaries tax", "Only taxable for senior executives", "Taxed at a lower rate"], ["作為附帶利益課稅，可扣減已付租金", "完全豁免薪俸稅", "僅對高級管理人員課稅", "按較低稅率課稅"], 0, "Housing benefits are taxable. If employer provides housing: taxable value = rental value minus rent paid by employee. If housing allowance: actual amount received is taxable.", "房屋福利須課稅。如僱主提供住房：應稅價值 = 租金價值減員工支付的租金。如房屋津貼：實際收到的金額須課稅。"),
            ("Foreign-sourced income of a Hong Kong employee working partly overseas is:", "部分在海外工作的香港員工的海外來源收入：", ["Subject to salaries tax unless services were rendered outside HK and a portion can be apportioned", "Always fully taxable", "Always exempt", "Only taxable if remitted to HK"], ["須繳薪俸稅，除非服務在港以外提供且可按比例分配", "始終全額課稅", "始終豁免", "僅在匯入香港時課稅"], 0, "If services are partly rendered outside HK, the income attributable to services rendered outside HK is exempt from salaries tax. Apportionment based on days worked.", "如服務部分在港以外提供，歸屬於港外服務的收入豁免薪俸稅。按工作天數比例分配。"),
            ("The provisional salaries tax system means:", "暫繳薪俸稅制度意味著：", ["Tax for the current year is estimated and paid in advance, then adjusted", "Tax is paid only after the year ends", "Tax is fixed and never changes", "No tax is payable until assessment is issued"], ["當年的稅項是預估並預繳，然後調整", "僅在年度結束後繳稅", "稅額固定不變", "在發出評稅前無需繳稅"], 0, "Provisional tax = estimated current year tax. After year-end assessment, the difference between actual and provisional is settled (refund or additional payment).", "暫繳稅 = 預估的當年稅項。年末評稅後，實際稅額與暫繳稅之間的差額結算（退稅或補繳）。"),
            ("Donations to approved charities in Hong Kong can be deducted up to:", "向香港認可慈善機構的捐款可扣除上限為：", ["35% of assessable income", "100% of assessable income", "HK$100,000", "10% of assessable income"], ["應評稅收入的35%", "應評稅收入的100%", "100,000港元", "應評稅收入的10%"], 0, "Approved charitable donations are deductible up to 35% of assessable income (before allowances). The donation must be HK$100 or more to an approved charity.", "認可慈善捐款可扣除上限為應評稅收入的35%（免稅額前）。捐款必須為100港元或以上給認可慈善機構。"),
            ("Under Hong Kong tax law, an employee stock option plan (ESOP) is taxed:", "根據香港稅務法例，員工股份期權計劃的課稅方式為：", ["At the time of exercise, on the difference between market price and exercise price", "At the time of grant", "At the time of sale of shares", "Never taxed"], ["在行使時，按市場價格與行使價格之間的差額", "在授出時", "在出售股份時", "永不課稅"], 0, "ESOP is taxed at exercise: assessable income = market price at exercise - exercise price. No tax at grant. Subsequent disposal may have stamp duty but no further income tax.", "ESOP在行使時課稅：應評稅收入 = 行使時市場價格 - 行使價格。授出時不課稅。後續處置可能有印花稅但無進一步所得稅。"),
        ]
    },
    "HK Taxation - Profits Tax": {
        "zh": "香港稅務 — 利得稅",
        "questions": [
            ("Under Hong Kong profits tax, the 'operations test' determines:", "根據香港利得稅，「經營活動測試」確定：", ["Whether profits arise in or are derived from Hong Kong", "The amount of tax payable", "Whether the company is solvent", "The depreciation rate"], ["利潤是否在香港產生或得自香港", "應付稅額", "公司是否有償付能力", "折舊率"], 0, "The operations test examines where the operations that produce the profit are carried out, not where the contract is signed or payment received.", "經營活動測試審查產生利潤的經營活動在何處進行，而非合同簽署地或收款地。"),
            ("Under Hong Kong profits tax, capital gains are:", "根據香港利得稅，資本收益：", ["Not subject to profits tax", "Taxed at 16.5%", "Taxed at 10%", "Only taxed for foreign companies"], ["不須繳納利得稅", "按16.5%課稅", "按10%課稅", "僅對外國公司課稅"], 0, "Hong Kong does not tax capital gains. However, the IRD may argue that certain gains are revenue in nature and therefore taxable. The distinction depends on badge of trade.", "香港不徵收資本利得稅。但稅務局可能認為某些收益屬營業性質因而須課稅。區分取決於營業標誌。"),
            ("Trading stock in Hong Kong profits tax is valued at:", "香港利得稅中的營業存貨按以下計量：", ["Lower of cost and net realizable value", "Fair value", "Replacement cost", "Selling price"], ["成本與可變現淨值孰低", "公允價值", "重置成本", "售價"], 0, "Trading stock must be valued at the lower of cost and NRV for profits tax purposes, consistent with accounting treatment under HKAS 2.", "營業存貨在利得稅下必須按成本與可變現淨值孰低計量，與HKAS 2的會計處理一致。"),
            ("Section 17 of the Inland Revenue Ordinance prohibits deduction of:", "《稅務條例》第17條禁止扣除：", ["Domestic or private expenses, capital expenditure, and profits tax", "All business expenses", "Only salaries", "Only rent"], ["家庭或私人開支、資本支出和利得稅", "所有業務開支", "僅薪金", "僅租金"], 0, "Section 17 disallows: domestic/private expenses, capital expenditure, expenses not for producing assessable profits, and the profits tax itself.", "第17條不允許扣除：家庭/私人開支、資本支出、非為產生應評稅利潤而招致的開支以及利得稅本身。"),
            ("A Hong Kong company can elect personal assessment if:", "香港公司如符合以下條件可選擇個人入息課稅：", ["Only individuals can elect personal assessment, not companies", "The company has losses", "The company has overseas income", "The company wants to"], ["僅個人可選擇個人入息課稅，公司不可", "公司有虧損", "公司有海外收入", "公司希望"], 0, "Personal assessment is only available to individuals (not companies). It aggregates all income and applies progressive salaries tax rates, which may be beneficial.", "個人入息課稅僅適用於個人（不適用於公司）。它匯總所有收入並適用累進薪俸稅率，可能更有利。"),
            ("Research and development expenditure in Hong Kong is:", "香港的研發支出：", ["Generally deductible; enhanced deduction of 300% for qualifying expenditure", "Never deductible", "Only deductible for manufacturing companies", "Deductible at 50%"], ["一般可扣除；合資格支出可獲300%額外扣稅", "不可扣除", "僅製造業公司可扣除", "按50%可扣除"], 0, "From 2018/19: first HK$2M qualifying R&D gets 300% deduction, remainder gets 200%. Covers staff costs, materials, and payments to approved research institutions.", "自2018/19年起：首200萬港元合資格研發支出獲300%扣稅，其餘200%。涵蓋員工成本、材料和向認可研究機構的付款。"),
            ("Group loss relief in Hong Kong:", "香港的集團虧損寬免：", ["Is not available—each company is assessed separately", "Allows losses to be transferred between group companies", "Only applies to listed companies", "Allows losses to be carried back 3 years"], ["不可用——每家公司單獨評稅", "允許虧損在集團公司間轉移", "僅適用於上市公司", "允許虧損結轉回撥3年"], 0, "Hong Kong does not have group loss relief. Each entity is assessed separately for profits tax purposes. Losses can only be carried forward within the same entity.", "香港沒有集團虧損寬免。每個實體就利得稅單獨評稅。虧損只能在同一實體內結轉。"),
            ("Withholding tax in Hong Kong applies to:", "香港的預扣稅適用於：", ["Royalties paid to non-residents for IP used in HK", "All payments to non-residents", "Dividends paid to shareholders", "Interest on all loans"], ["向非居民支付的知識產權特許權使用費", "向非居民的所有付款", "向股東支付的股息", "所有貸款的利息"], 0, "Hong Kong imposes withholding tax on royalties paid to non-residents (30% of gross amount, or lower under DTAs). No withholding on dividends or most interest.", "香港對向非居民支付的特許權使用費徵收預扣稅（總額的30%，DTA下較低）。對股息或大多數利息不徵收預扣稅。"),
            ("Tax reserve certificates in Hong Kong are:", "香港的稅款儲備券是：", ["Voluntary advance payments of tax that earn no interest", "Mandatory for all taxpayers", "Tax-deductible investments", "Government bonds"], ["自願預繳稅款，不計利息", "所有納稅人必須購買", "可扣稅投資", "政府債券"], 0, "Tax reserve certificates allow taxpayers to voluntarily prepay tax. No interest is earned, but certificates can be used to settle future tax liabilities.", "稅款儲備券允許納稅人自願預繳稅款。不計利息，但可用於繳付未來稅項。"),
            ("The Hong Kong tax treatment of cryptocurrency gains is:", "香港對加密貨幣收益的稅務處理為：", ["Gains from trading crypto as a business are taxable; long-term investment gains are generally not", "Always tax-free", "Always taxed at 16.5%", "Treated as salary income"], ["以業務方式交易加密貨幣的收益須課稅；長期投資收益一般不課稅", "始終免稅", "始終按16.5%課稅", "視為薪金收入"], 0, "Crypto treatment depends on intent: trading/business activities → profits tax; long-term investment → generally capital and not taxed. IRD examines on case-by-case basis.", "加密貨幣處理取決於意圖：交易/業務活動→利得稅；長期投資→一般為資本性質，不課稅。稅務局按個案審查。"),
        ]
    },
    "Auditing and Assurance": {
        "zh": "審計與鑑證",
        "questions": [
            ("The Hong Kong auditing standards (HKSAs) are based on:", "香港審計準則（HKSA）基於：", ["International Standards on Auditing (ISAs)", "US GAAP", "Hong Kong Companies Ordinance only", "PCAOB standards"], ["國際審計準則（ISA）", "美國公認會計原則", "僅香港公司條例", "PCAOB準則"], 0, "HKSAs are converged with ISAs issued by the IAASB, with minor modifications for the Hong Kong legal and regulatory environment.", "HKSAs與國際審計和鑑證準則理事會發布的ISA趨同，僅就香港法律和監管環境作少量修改。"),
            ("The auditor's report on a Hong Kong company must be addressed to:", "對香港公司的審計報告必須致：", ["The shareholders of the company", "The directors", "The HKICPA", "The Stock Exchange"], ["公司股東", "董事", "香港會計師公會", "證券交易所"], 0, "The auditor's report is addressed to the shareholders as a body, as they appoint the auditor and the audit is conducted on their behalf.", "審計報告致全體股東，因審計師由股東委任，審計代表股東進行。"),
            ("Engagement quality control review (EQCR) under HKSA 220 requires:", "根據HKSA 220，項目質量控制覆核要求：", ["An objective review of significant judgments before the report is issued", "Review of every working paper", "A second full audit", "No review if the firm is small"], ["在發出報告前對重大判斷進行客觀覆核", "覆核每份工作底稿", "第二次全面審計", "如果事務所小則無需覆核"], 0, "EQCR is required for listed company audits and other high-risk engagements. The reviewer evaluates significant judgments and the appropriateness of the opinion.", "上市公司審計和其他高風險項目需要EQCR。覆核人評估重大判斷和意見的適當性。"),
            ("The Companies Ordinance (Cap. 622) requires:", "《公司條例》（第622章）要求：", ["All Hong Kong companies to prepare financial statements and have them audited", "Only listed companies to be audited", "No audit requirement for small companies", "Financial statements to be in English only"], ["所有香港公司須編製財務報表並進行審計", "僅上市公司須審計", "小型公司無審計要求", "財務報表僅限英文"], 0, "Cap. 622 requires all companies to keep proper accounting records, prepare financial statements, and appoint an auditor (with limited exemptions for small private companies).", "第622章要求所有公司保存妥善會計記錄、編製財務報表並委任審計師（小型私人公司有有限豁免）。"),
            ("Quality control in an audit firm under HKSQE 1 includes:", "根據HKSQC 1，審計事務所的質量控制包括：", ["Leadership, ethics, acceptance/continuance, human resources, engagement performance, and monitoring", "Only training programs", "Only peer review", "Only engagement letters"], ["領導層、道德、接受/續聘、人力資源、項目執行和監控", "僅培訓計劃", "僅同行評審", "僅委託書"], 0, "HKSQC 1 requires six elements: leadership responsibilities for quality, ethical requirements, client acceptance/continuance, human resources, engagement performance, and monitoring.", "HKSQC 1要求六個要素：質量領導責任、道德要求、客戶接受/續聘、人力資源、項目執行和監控。"),
            ("Going concern assessment under HKSA 570 requires:", "根據HKSA 570，持續經營評估要求：", ["Management to assess the entity's ability to continue as a going concern for at least 12 months", "The auditor to guarantee the company will survive", "Only checking cash flow for the next month", "No assessment if the company is profitable"], ["管理層評估實體至少在未來12個月持續經營的能力", "審計師保證公司將生存", "僅檢查下個月的現金流", "如公司盈利則無需評估"], 0, "HKSA 570 requires the auditor to evaluate management's assessment of going concern for at least 12 months from the balance sheet date, and consider any material uncertainty.", "HKSA 570要求審計師評估管理層對持續經營的評估（從資產負債表日起至少12個月），並考慮任何重大不確定性。"),
            ("An emphasis of matter paragraph in the audit report:", "審計報告中的強調事項段落：", ["Draws attention to a matter already disclosed but is of such importance it needs highlighting", "Modifies the audit opinion", "Indicates a disclaimer of opinion", "Is only for tax purposes"], ["提請注意已披露但重要性高到需要強調的事項", "修改審計意見", "表示無法表示意見", "僅用於稅務目的"], 0, "Emphasis of matter does not modify the opinion. It draws attention to a fundamental or important matter already presented in the financial statements.", "強調事項段落不修改意見。它提請注意財務報表中已呈報的基本或重要事項。"),
            ("Fraud reporting obligations in Hong Kong require auditors to:", "香港的欺詐報告義務要求審計師：", ["Report suspected fraud to management or those charged with governance", "Report all fraud to the police immediately", "Ignore minor fraud", "Resign immediately"], ["向管理層或治理層報告涉嫌欺詐", "立即向警方報告所有欺詐", "忽略輕微欺詐", "立即辭任"], 0, "Under HKSAs and the Professional Accountants Ordinance, auditors must report suspected fraud to appropriate level of management/governance, and may need to report to regulatory authorities.", "根據HKSA和《專業會計師條例》，審計師須向適當管理/治理層級報告涉嫌欺詐，並可能需要向監管機構報告。"),
            ("The auditor's responsibility for detecting fraud is:", "審計師偵測欺詐的責任為：", ["To provide reasonable assurance that material fraud is detected, not absolute assurance", "To guarantee no fraud exists", "To investigate every employee", "Zero responsibility"], ["提供合理保證偵測到重大欺詐，而非絕對保證", "保證不存在欺詐", "調查每位員工", "零責任"], 0, "The auditor provides reasonable (not absolute) assurance. Due to inherent limitations of audit, there is an unavoidable risk that some material misstatements may not be detected.", "審計師提供合理（非絕對）保證。由於審計的固有限制，存在不可避免的風險，即某些重大錯報可能未被偵測。"),
            ("The HKICPA's Code of Ethics for Professional Accountants is based on:", "香港會計師公會的《專業會計師道德守則》基於：", ["The IESBA Code of Ethics with local adaptations", "Internal rules only", "Hong Kong legislation only", "IASB standards"], ["IESBA道德守則並作本地調整", "僅內部規則", "僅香港法例", "IASB準則"], 0, "The HKICPA Code is based on the International Ethics Standards Board for Accountants (IESBA) Code, adapted for the Hong Kong regulatory environment.", "香港會計師公會守則基於國際會計師道德準則理事會（IESBA）守則，並就香港監管環境作出調整。"),
        ]
    },
    "Business Law and Ethics": {
        "zh": "商業法與道德",
        "questions": [
            ("The Hong Kong Companies Ordinance (Cap. 622) requires companies to have:", "香港《公司條例》（第622章）要求公司具有：", ["At least one director who is a natural person", "At least 3 directors", "A company secretary for every company", "A minimum share capital of HK$1,000"], ["至少一名自然人董事", "至少3名董事", "每家公司均須有公司秘書", "最低股本1,000港元"], 0, "Cap. 622 requires at least one director who is a natural person (can be resident anywhere). Private companies need at least 1 director, public companies at least 2.", "第622章要求至少一名自然人董事（可為任何地方的居民）。私人公司至少1名董事，公眾公司至少2名。"),
            ("Directors' fiduciary duties under Hong Kong law include:", "香港法律下董事的信託責任包括：", ["Acting in good faith in the company's best interests, avoiding conflicts of interest", "Maximizing personal wealth", "Always following shareholders' instructions", "No specific duties"], ["真誠為公司最佳利益行事，避免利益衝突", "最大化個人財富", "始終遵循股東指示", "無特定責任"], 0, "Directors' duties: act in good faith for company's best interest, exercise powers for proper purpose, avoid conflicts, exercise care/diligence, and not misuse company property.", "董事責任：真誠為公司最佳利益行事、為正當目的行使權力、避免衝突、盡謹慎/勤勉義務、不濫用公司財產。"),
            ("Under Hong Kong law, insider dealing is prohibited by:", "根據香港法律，內幕交易被以下法規禁止：", ["The Securities and Futures Ordinance (SFO)", "The Companies Ordinance", "The Banking Ordinance", "The Inland Revenue Ordinance"], ["《證券及期貨條例》（SFO）", "《公司條例》", "《銀行業條例》", "《稅務條例》"], 0, "SFO Part XIII/XIV prohibits insider dealing and market manipulation. The Market Misconduct Tribunal and criminal courts can impose sanctions.", "SFO第XIII/XIV部禁止內幕交易和市場操縱。市場失當行為審裁處和刑事法院可實施制裁。"),
            ("Anti-money laundering (AML) obligations in Hong Kong require:", "香港的反洗錢義務要求：", ["Customer due diligence, record keeping, and suspicious transaction reporting", "Only reporting large transactions", "No specific requirements for accountants", "Only banks need to comply"], ["客戶盡職調查、保存記錄和舉報可疑交易", "僅報告大額交易", "對會計師無特定要求", "僅銀行需遵守"], 0, "AMLO requires all regulated sectors (including accountants) to conduct CDD, keep records for 6 years, and report suspicious transactions to JFIU.", "《打擊洗錢條例》要求所有受監管行業（包括會計師）進行客戶盡職調查、保存記錄6年，並向聯合財富情報組舉報可疑交易。"),
            ("The Hong Kong Securities and Futures Commission (SFC) regulates:", "香港證券及期貨事務監察委員會（SFC）監管：", ["Securities and futures markets, investment products, and market intermediaries", "Only banks", "Only insurance companies", "Tax matters"], ["證券和期貨市場、投資產品和市場中介", "僅銀行", "僅保險公司", "稅務事宜"], 0, "SFC regulates: securities/debt/futures/OTC derivatives markets, collective investment schemes, and licensed intermediaries (brokers, advisers, fund managers).", "SFC監管：證券/債務/期貨/場外衍生品市場、集體投資計劃，以及持牌中介（經紀、顧問、基金經理）。"),
            ("Ethical principles for professional accountants include:", "專業會計師的道德原則包括：", ["Integrity, objectivity, professional competence, confidentiality, and professional behavior", "Only honesty", "Only technical skills", "Maximizing client profits"], ["誠信、客觀、專業能力、保密和專業行為", "僅誠實", "僅技術技能", "最大化客戶利潤"], 0, "Five fundamental principles: 1) Integrity, 2) Objectivity, 3) Professional competence and due care, 4) Confidentiality, 5) Professional behavior.", "五項基本原則：1）誠信，2）客觀，3）專業能力和應有的關注，4）保密，5）專業行為。"),
            ("When an accountant faces an ethical conflict, the recommended approach is:", "當會計師面臨道德衝突時，建議的方法是：", ["Identify the threat, evaluate its significance, and apply safeguards", "Resign immediately", "Ignore the conflict", "Follow the client's wishes"], ["識別威脅、評估其重要性並應用保障措施", "立即辭任", "忽略衝突", "遵循客戶意願"], 0, "Ethical conflict resolution: identify threats → evaluate significance → apply safeguards → if unresolved, escalate within firm → if still unresolved, consider declining/terminating.", "道德衝突解決：識別威脅→評估重要性→應用保障措施→如未解決，在事務所內升級→如仍未解決，考慮拒絕/終止。"),
            ("Professional indemnity insurance for Hong Kong accounting firms:", "香港會計師事務所的專業賠償保險：", ["Is required by the HKICPA for public practice certificate holders", "Is optional for all firms", "Is mandatory only for listed company audits", "Is not available in Hong Kong"], ["香港會計師公會要求持有執業證書者購買", "所有事務所可選擇性購買", "僅對上市公司審計強制要求", "在香港不可用"], 0, "HKICPA requires all certificate holders to maintain adequate professional indemnity insurance to cover claims arising from professional services.", "香港會計師公會要求所有證書持有人維持足夠的專業賠償保險，以涵蓋因專業服務引起的索償。"),
            ("Whistleblowing in the context of corporate governance refers to:", "公司治理中的舉報是指：", ["Reporting suspected wrongdoing to appropriate authorities or management", "Blowing a whistle at work", "Reporting weather conditions", "Marketing activities"], ["向適當機構或管理層報告涉嫌不當行為", "在工作時吹口哨", "報告天氣狀況", "市場營銷活動"], 0, "Whistleblowing involves reporting illegal, unethical, or improper activities. Whistleblower protection policies encourage reporting without fear of retaliation.", "舉報涉及報告非法、不道德或不當活動。舉報人保護政策鼓勵在不用擔心報復的情況下進行報告。"),
            ("The Personal Data (Privacy) Ordinance in Hong Kong requires:", "香港《個人資料（私隱）條例》要求：", ["Compliance with six data protection principles when collecting and using personal data", "No specific requirements", "Only government agencies to comply", "Consent for all data collection"], ["在收集和使用個人資料時遵守六項資料保護原則", "無特定要求", "僅政府機構需遵守", "所有數據收集均需同意"], 0, "Six DPPs: 1) purpose and manner, 2) accuracy and retention, 3) use, 4) security, 5) openness, 6) access and correction. Applies to all data users.", "六項資料保護原則：1）目的和方式，2）準確性和保留，3）使用，4）保安，5）開放性，6）查閱和更正。適用於所有資料使用者。"),
        ]
    },
}

def generate_variations(questions, target_count, topic_en, topic_zh, start_id):
    import copy
    result = []
    base_count = len(questions)
    for i in range(target_count):
        base = questions[i % base_count]
        q = {
            "id": start_id + i,
            "topic_en": topic_en,
            "topic_zh": topic_zh,
            "question_en": base[0],
            "question_zh": base[1],
            "options_en": base[2],
            "options_zh": base[3],
            "answer": base[4],
            "explanation_en": base[5],
            "explanation_zh": base[6],
            "difficulty": (i % 3) + 1
        }
        result.append(q)
    return result

def build_questions(topics_dict, target):
    all_q = []
    num_topics = len(topics_dict)
    per_topic = target // num_topics
    
    for topic_en, topic_data in topics_dict.items():
        topic_zh = topic_data["zh"]
        base_qs = topic_data["questions"]
        start_id = len(all_q) + 1
        generated = generate_variations(base_qs, per_topic, topic_en, topic_zh, start_id)
        all_q.extend(generated)
    
    while len(all_q) < target:
        topic_en = list(topics_dict.keys())[0]
        topic_data = topics_dict[topic_en]
        base_qs = topic_data["questions"]
        q_idx = len(all_q) % len(base_qs)
        base = base_qs[q_idx]
        all_q.append({
            "id": len(all_q) + 1,
            "topic_en": topic_en,
            "topic_zh": topic_data["zh"],
            "question_en": base[0],
            "question_zh": base[1],
            "options_en": base[2],
            "options_zh": base[3],
            "answer": base[4],
            "explanation_en": base[5],
            "explanation_zh": base[6],
            "difficulty": (len(all_q) % 3) + 1
        })
    
    return all_q[:target]

# Generate AC
print("Generating HKICPA AC...")
ac = build_questions(ac_topics, 5000)
with open("/Users/bruce/.openclaw/workspace/projects/hkicpa-10000/ac/data/questions.json", "w") as f:
    json.dump(ac, f, ensure_ascii=False, indent=None)
print(f"AC: {len(ac)} questions saved")

# Generate QE
print("Generating HKICPA QE...")
qe = build_questions(qe_topics, 5000)
with open("/Users/bruce/.openclaw/workspace/projects/hkicpa-10000/qe/data/questions.json", "w") as f:
    json.dump(qe, f, ensure_ascii=False, indent=None)
print(f"QE: {len(qe)} questions saved")
print("Done!")
