#!/usr/bin/env python3
"""Generate 100 questions per movie series - harder, more relevant."""
import json, os

BASE = "others/movies/topics"

def w(fp, data):
    with open(os.path.join(BASE, fp), 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✅ {fp}: {len(data)} questions")

# ═══════════════════════════════════════════
# 周星馳系列 - 100 questions
# ═══════════════════════════════════════════
sc = [
    # 賭聖 (1990)
    {"question_zh":"《賭聖》（1990）中，左頌星從哪裏來港？","question_en":"Where does So Chun-sing come from in 'All for the Winner'?","options_zh":["廣東","上海","北京","台灣"],"options_en":["Guangdong","Shanghai","Beijing","Taiwan"],"answer":0,"explanation_zh":"左頌星從廣東鄉下來港。","explanation_en":"So Chun-sing comes from rural Guangdong.","difficulty":1},
    {"question_zh":"《賭聖》中，左頌星的特異功能需要什麼來激活？","question_en":"What activates So Chun-sing's power?","options_zh":["摸嘴唇","閉眼","深呼吸","念咒語"],"options_en":["Touch lips","Close eyes","Deep breath","Chant"],"answer":0,"explanation_zh":"摸嘴唇是激活特異功能的動作。","explanation_en":"Touching his lips activates the power.","difficulty":1},
    {"question_zh":"《賭聖》中，綺夢由誰飾演？","question_en":"Who plays Qi Meng in 'All for the Winner'?","options_zh":["張敏","朱茵","鞏俐","邱淑貞"],"options_en":["Sharla Cheung","Athena Chu","Gong Li","Chingmy Yau"],"answer":0,"explanation_zh":"張敏飾演綺夢。","explanation_en":"Sharla Cheung plays Qi Meng.","difficulty":1},
    {"question_zh":"《賭聖》的票房打破了哪部電影的紀錄？","question_en":"Which film's box office record did 'All for the Winner' break?","options_zh":["《賭神》","《英雄本色》","《少林寺》","《最佳拍檔》"],"options_en":["God of Gamblers","A Better Tomorrow","Shaolin Temple","Aces Go Places"],"answer":0,"explanation_zh":"《賭聖》打破了《賭神》的票房紀錄，成為1990年香港票房冠軍。","explanation_en":"It broke God of Gamblers' record, becoming 1990's top grossing HK film.","difficulty":2},
    {"question_zh":"《賭聖》中，左頌星與賭神高進的關係是？","question_en":"What is So Chun-sing's relationship with Ko Chun?","options_zh":["粉絲與偶像","師徒","兄弟","敵人"],"options_en":["Fan and idol","Master and disciple","Brothers","Enemies"],"answer":0,"explanation_zh":"左頌星是賭神高進的粉絲。","explanation_en":"So Chun-sing is a fan of Ko Chun.","difficulty":1},
    # 逃學威龍 (1991)
    {"question_zh":"《逃學威龍》中，周星星被派去學校調查什麼？","question_en":"What is Chow Sing-sing investigating in the school?","options_zh":["失槍案","毒品案","綁架案","謀殺案"],"options_en":["Missing gun","Drug case","Kidnapping","Murder"],"answer":0,"explanation_zh":"周星星被派去學校臥底調查失槍案。","explanation_en":"He's investigating a missing gun case.","difficulty":1},
    {"question_zh":"《逃學威龍》中，周星星的上司由誰飾演？","question_en":"Who plays Chow Sing-sing's superior?","options_zh":["黃霑","曾志偉","吳孟達","秦沛"],"options_en":["James Wong","Eric Tsang","Ng Man-tat","Chun Pei"],"answer":2,"explanation_zh":"吳孟達飾演周星星的上司兼搭檔。","explanation_en":"Ng Man-tat plays his superior and partner.","difficulty":1},
    {"question_zh":"《逃學威龍2》（1992）中，周星星去了哪間學校臥底？","question_en":"Which school does Chow Sing-sin infiltrate in 'Fight Back to School 2'?","options_zh":["聖育強中學","貴族中學","國際學校","女子中學"],"options_en":["St. Ying Keung","Elite School","International School","Girls' School"],"answer":1,"explanation_zh":"周星星去了貴族中學臥底。","explanation_en":"He infiltrates an elite school.","difficulty":1},
    {"question_zh":"《逃學威龍3：龍過雞年》（1993）中，周星星飾演誰？","question_en":"Who does Chow Sing-sing play in 'Fight Back to School 3'?","options_zh":["警察臥底","富商","老師","學生"],"options_en":["Undercover cop","Rich businessman","Teacher","Student"],"answer":1,"explanation_zh":"周星星飾演一個富商。","explanation_en":"He plays a rich businessman.","difficulty":1},
    # 唐伯虎點秋香 (1993)
    {"question_zh":"《唐伯虎點秋香》中，唐伯虎為何要進入華太師府？","question_en":"Why does Tang Bohu enter the Hua household?","options_zh":["追求秋香","逃避仇家","應徵做官","做生意"],"options_en":["Pursue Qiu Xiang","Escape enemies","Apply for official post","Business"],"answer":0,"explanation_zh":"唐伯虎為了追求秋香而進入華太師府做書僮。","explanation_en":"Tang Bohu enters as a servant to pursue Qiu Xiang.","difficulty":1},
    {"question_zh":"《唐伯虎點秋香》中，唐伯虎在華府的化名是什麼？","question_en":"What is Tang Bohu's alias in the Hua household?","options_zh":["華安","張三","李四","王五"],"options_en":["Hua An","Zhang San","Li Si","Wang Wu"],"answer":0,"explanation_zh":"唐伯虎化名華安。","explanation_en":"His alias is Hua An.","difficulty":1},
    {"question_zh":"《唐伯虎點秋香》中，誰是華太師府中的對手？","question_en":"Who is Tang Bohu's rival in the Hua household?","options_zh":["奪命書生","武狀元","華文華武","石榴姐"],"options_en":["Killer Scholar","Martial Champion","Hua Wen & Wu","Sister Shiliu"],"answer":0,"explanation_zh":"奪命書生是唐伯虎在華府的主要對手。","explanation_en":"Killer Scholar is his main rival.","difficulty":1},
    {"question_zh":"《唐伯虎點秋香》中，石榴姐由誰飾演？","question_en":"Who plays Sister Shiliu?","options_zh":["苑瓊丹","吳君如","梅艷芳","毛舜筠"],"options_en":["Yuen King-tan","Sandra Ng","Anita Mui","Mabel Cheung"],"answer":0,"explanation_zh":"苑瓊丹飾演石榴姐。","explanation_en":"Yuen King-tan plays Sister Shiliu.","difficulty":1},
    {"question_zh":"《唐伯虎點秋香》的經典對白「我對你的敬仰有如滔滔江水」出自誰口？","options_zh":["唐伯虎","祝枝山","武狀元","華太師"],"options_en":["Tang Bohu","Zhu Zhishan","Martial Champion","Grandpa Hua"],"question_en":"Who says the classic line about admiration?","answer":2,"explanation_zh":"武狀元說出這句經典對白。","explanation_en":"The Martial Champion says this classic line.","difficulty":1},
    # 大話西遊 (1995)
    {"question_zh":"《大話西遊》分為上下兩集，下集叫什麼？","question_en":"What is the subtitle of 'A Chinese Odyssey Part Two'?","options_zh":["大聖娶親","月光寶盒","仙履奇緣","西遊記"],"options_en":["Cinderella","Pandora's Box","A Chinese Odyssey","Journey to the West"],"answer":0,"explanation_zh":"下集叫《大聖娶親》。","explanation_en":"Part Two is called 'Cinderella' (A Chinese Odyssey Part Two).","difficulty":1},
    {"question_zh":"《大話西遊》中，至尊寶用月光寶盒穿越到什麼時代？","question_en":"What era does Supreme Treasure travel to?","options_zh":["五百年前","唐朝","宋朝","明朝"],"options_en":["500 years ago","Tang Dynasty","Song Dynasty","Ming Dynasty"],"answer":0,"explanation_zh":"至尊寶穿越到五百年前。","explanation_en":"He travels 500 years into the past.","difficulty":1},
    {"question_zh":"《大話西遊》中，牛魔王由誰飾演？","options_zh":["陸樹銘","羅家英","黃秋生","劉鎮偉"],"options_en":["Lu Shujin","Law Ka-ying","Anthony Wong","Jeffrey Lau"],"question_en":"Who plays the Bull Demon King?","answer":1,"explanation_zh":"羅家英飾演牛魔王。","explanation_en":"Law Ka-ying plays the Bull Demon King.","difficulty":1},
    {"question_zh":"《大話西遊》中，唐三藏的經典口頭禪是什麼？","options_zh":["你媽貴姓","阿彌陀佛","悟空救我","善哉善哉"],"options_en":["What's your mother's name?","Amitabha","Wukong save me","Mercy"],"question_en":"What is Tripitaka's catchphrase?","answer":0,"explanation_zh":"唐三藏經常問「你媽貴姓」。","explanation_en":"Tripitaka often asks 'What's your mother's surname?'","difficulty":1},
    {"question_zh":"《大話西遊》的導演是誰？","options_zh":["劉鎮偉","王家衛","周星馳","徐克"],"options_en":["Jeffrey Lau","Wong Kar-wai","Stephen Chow","Tsui Hark"],"question_en":"Who directed 'A Chinese Odyssey'?","answer":0,"explanation_zh":"劉鎮偉執導，周星馳主演。","explanation_en":"Directed by Jeffrey Lau, starring Stephen Chow.","difficulty":1},
    # 食神 (1996)
    {"question_zh":"《食神》中，史提芬周被誰陷害失去食神稱號？","options_zh":["唐牛","大快樂","鵝頭","吳啟華"],"options_en":["Tang Niu","Big Happy","Goose Head","Ng Kai-wah"],"question_en":"Who betrays the God of Cookery?","answer":0,"explanation_zh":"唐牛與大快樂合謀陷害史提芬周。","explanation_en":"Tang Niu conspires against him.","difficulty":1},
    {"question_zh":"《食神》中，火雞臉上有什麼特徵？","options_zh":["刀疤","痣","胎記","紋身"],"options_en":["Scar","Mole","Birthmark","Tattoo"],"question_en":"What is Fire Chicken's facial feature?","answer":0,"explanation_zh":"火雞臉上有刀疤。","explanation_en":"Fire Chicken has a scar on her face.","difficulty":1},
    {"question_zh":"《食神》中，雜碎麵的真名是什麼？","options_zh":["撒尿牛丸","黯然銷魂飯","佛跳牆","叉燒飯"],"options_en":["Pissing Beef Balls","Sorrowful Rice","Buddha Jumps Over Wall","Char siu rice"],"question_en":"What is the real name of the noodle dish?","answer":0,"explanation_zh":"撒尿牛丸是史提芬周重新發明的菜式。","explanation_en":"Pissing Beef Balls is the dish he reinvents.","difficulty":1},
    {"question_zh":"《食神》的決賽在什麼地方舉行？","options_zh":["少林寺","皇宮","廚神大賽","美食街"],"options_en":["Shaolin Temple","Palace","God of Cookery Competition","Food Street"],"question_en":"Where is the final competition held?","answer":2,"explanation_zh":"決賽在廚神大賽中舉行。","explanation_en":"The final is at the God of Cookery Competition.","difficulty":1},
    # 少林足球 (2001)
    {"question_zh":"《少林足球》中，大師兄的職業是什麼？","options_zh":["搬運工","清潔工","廚師","的士司機"],"options_en":["Porter","Cleaner","Chef","Taxi driver"],"question_en":"What is the eldest brother's job?","answer":1,"explanation_zh":"大師兄是個清潔工。","explanation_en":"The eldest brother works as a cleaner.","difficulty":1},
    {"question_zh":"《少林足球》中，阿梅由誰飾演？","options_zh":["趙薇","莫文蔚","張柏芝","朱茵"],"options_en":["Zhao Wei","Karen Mok","Cecilia Cheung","Athena Chu"],"question_en":"Who plays Ah Mei?","answer":0,"explanation_zh":"趙薇飾演阿梅。","explanation_en":"Zhao Wei plays Ah Mei.","difficulty":1},
    {"question_zh":"《少林足球》中，少林隊的對手是什麼隊？","options_zh":["魔鬼隊","霸王隊","猛虎隊","雄鷹隊"],"options_en":["Devil Team","霸王","Tiger","Eagle"],"question_en":"What is Shaolin Team's rival?","answer":0,"explanation_zh":"對手是魔鬼隊。","explanation_en":"The rival is the Devil Team.","difficulty":1},
    {"question_zh":"《少林足球》中，三師兄的絕招是什麼？","options_zh":["旋風地堂腿","鐵頭功","金鐘罩","鬼影擒拿手"],"options_en":["Whirlwind Leg","Iron Head","Golden Bell","Ghost Catching"],"question_en":"What is the 3rd brother's specialty?","answer":0,"explanation_zh":"三師兄精通旋風地堂腿。","explanation_en":"The 3rd brother masters Whirlwind Leg.","difficulty":1},
    {"question_zh":"《少林足球》中，四師兄的絕招是什麼？","options_zh":["鬼影擒拿手","鐵頭功","旋風腿","金鐘罩"],"options_en":["Ghost Catching","Iron Head","Whirlwind","Golden Bell"],"question_en":"What is the 4th brother's specialty?","answer":0,"explanation_zh":"四師兄精通鬼影擒拿手，擅長守龍門。","explanation_en":"The 4th brother masters Ghost Catching, great as goalkeeper.","difficulty":1},
    # 功夫 (2004)
    {"question_zh":"《功夫》中，星仔的夢想是加入什麼幫派？","options_zh":["斧頭幫","洪興","東星","三合會"],"options_en":["Axe Gang","Hung Hing","Tung Sing","Triad"],"question_en":"What gang does Sing want to join?","answer":0,"explanation_zh":"星仔夢想加入斧頭幫。","explanation_en":"Sing wants to join the Axe Gang.","difficulty":1},
    {"question_zh":"《功夫》中，包租婆的真名是什麼？","options_zh":["肥婆四","包租婆","阿四","四姐"],"options_en":["Fat Woman Four","Landlady","Ah Four","Sister Four"],"question_en":"What is the Landlady's real name?","answer":0,"explanation_zh":"包租婆又稱肥婆四。","explanation_en":"The Landlady is also known as Fat Woman Four.","difficulty":2},
    {"question_zh":"《功夫》中，星仔最後領悟了什麼功夫？","options_zh":["如來神掌","獅吼功","蛤蟆功","太極拳"],"options_en":["Buddha's Palm","Lion's Roar","Toad Style","Tai Chi"],"question_en":"What kung fu does Sing master at the end?","answer":0,"explanation_zh":"星仔最終領悟了如來神掌。","explanation_en":"Sing ultimately masters Buddha's Palm.","difficulty":1},
    {"question_zh":"《功夫》中，天殘地缺是什麼樣的高手？","options_zh":["音波殺手","暗器高手","輕功高手","內功高手"],"options_en":["Sonic killers","Hidden weapon","Lightness","Internal power"],"question_en":"What kind of experts are the Heavenly Twins?","answer":0,"explanation_zh":"天殘地缺是音波殺手，用古琴殺人。","explanation_en":"They are sonic killers who use a guqin to kill.","difficulty":1},
    {"question_zh":"《功夫》中，裁縫的絕招是什麼？","options_zh":["十二路譚腿","洪家鐵線拳","五郎八卦棍","金鐘罩"],"options_en":["12 Tan Legs","Hung Iron Wire","5th Brother Staff","Golden Bell"],"question_en":"What is the Tailor's specialty?","answer":1,"explanation_zh":"裁縫精通洪家鐵線拳。","explanation_en":"The Tailor masters Hung Iron Wire Fist.","difficulty":2},
    {"question_zh":"《功夫》中，苦力強的絕招是什麼？","options_zh":["十二路譚腿","洪家鐵線拳","五郎八卦棍","金鐘罩"],"options_en":["12 Tan Legs","Hung Iron Wire","5th Brother Staff","Golden Bell"],"question_en":"What is Coolie's specialty?","answer":0,"explanation_zh":"苦力強精通十二路譚腿。","explanation_en":"Coolie masters 12 Tan Legs.","difficulty":2},
    {"question_zh":"《功夫》中，油炸鬼的絕招是什麼？","options_zh":["五郎八卦棍","十二路譚腿","洪家鐵線拳","金鐘罩"],"options_en":["5th Brother Staff","12 Tan Legs","Hung Iron Wire","Golden Bell"],"question_en":"What is the Donut Maker's specialty?","answer":0,"explanation_zh":"油炸鬼精通五郎八卦棍。","explanation_en":"The Donut Maker masters 5th Brother Staff.","difficulty":2},
    # 長江7號 (2008)
    {"question_zh":"《長江7號》中，周星馳飾演什麼角色？","options_zh":["窮父親","富商","老師","科學家"],"options_en":["Poor father","Rich man","Teacher","Scientist"],"question_en":"What role does Stephen Chow play in CJ7?","answer":0,"explanation_zh":"周星馳飾演一個窮父親。","explanation_en":"Stephen Chow plays a poor father.","difficulty":1},
    {"question_zh":"《長江7號》中，兒子小狄由誰飾演？","options_zh":["徐嬌","林妙可","張子楓","關曉彤"],"options_en":["Xu Jiao","Lin Miaoke","Zhang Zifeng","Guan Xiaotong"],"question_en":"Who plays the son Dicky?","answer":0,"explanation_zh":"徐嬌飾演小狄，是女扮男裝。","explanation_en":"Xu Jiao plays Dicky (a girl playing a boy role).","difficulty":1},
    # 美人魚 (2016)
    {"question_zh":"《美人魚》中，劉軒由誰飾演？","options_zh":["鄧超","黃渤","徐崢","沈騰"],"options_en":["Deng Chao","Huang Bo","Xu Zheng","Shen Teng"],"question_en":"Who plays Liu Xuan?","answer":0,"explanation_zh":"鄧超飾演富豪劉軒。","explanation_en":"Deng Chao plays billionaire Liu Xuan.","difficulty":1},
    {"question_zh":"《美人魚》中，珊珊為何接近劉軒？","options_zh":["刺殺他","愛上他","做生意","做調查"],"options_en":["Assassinate him","Fall in love","Business","Investigation"],"question_en":"Why does Shan Shan approach Liu Xuan?","answer":0,"explanation_zh":"珊珊最初是為了刺殺劉軒，因為他的項目威脅美人魚族群。","explanation_en":"Initially to assassinate him, as his project threatens the mermaids.","difficulty":1},
    # 西遊·降魔篇 (2013)
    {"question_zh":"《西遊·降魔篇》中，文章飾演的唐三藏有什麼特點？","options_zh":["不會武功但會兒歌三百首","武功高強","會念咒","會變身"],"options_en":["Can't fight but sings children's songs","Martial arts master","Can chant","Can transform"],"question_en":"What is special about Tripitaka in 'Journey to the West'?","answer":0,"explanation_zh":"唐三藏不會武功，靠「兒歌三百首」降魔。","explanation_en":"He can't fight, relying on '300 Children's Songs' to subdue demons.","difficulty":1},
    {"question_zh":"《西遊·降魔篇》中，黃渤飾演誰？","options_zh":["孫悟空","豬八戒","沙僧","牛魔王"],"options_en":["Sun Wukong","Zhu Bajie","Sha Wujing","Bull Demon King"],"question_en":"Who does Huang Bo play?","answer":0,"explanation_zh":"黃渤飾演被壓在五行山下的孫悟空。","explanation_en":"Huang Bo plays Sun Wukong trapped under the mountain.","difficulty":1},
    # 鹿鼎記 (1992)
    {"question_zh":"《鹿鼎記》中，韋小寶在皇宮中的身份是什麼？","options_zh":["太監","侍衛","御醫","廚師"],"options_en":["Eunuch","Guard","Imperial doctor","Chef"],"question_en":"What is Wei Xiaobao's identity in the palace?","answer":0,"explanation_zh":"韋小寶假扮太監混入皇宮。","explanation_en":"Wei Xiaobao disguises as a eunuch to enter the palace.","difficulty":1},
    {"question_zh":"《鹿鼎記》中，康熙由誰飾演？","options_zh":["溫兆倫","劉德華","梁朝偉","張衛健"],"options_en":["Wen Siu-lun","Andy Lau","Tony Leung","Dicky Cheung"],"question_en":"Who plays Emperor Kangxi?","answer":0,"explanation_zh":"溫兆倫飾演康熙皇帝。","explanation_en":"Wen Siu-lun plays Emperor Kangxi.","difficulty":2},
    {"question_zh":"《鹿鼎記》中，韋小寶的絕招是什麼？","options_zh":["化骨綿掌","降龍十八掌","九陰真經","葵花寶典"],"options_en":["Bone Melting Palm","18 Dragon Subduing","Nine Yin Manual","Sunflower Manual"],"question_en":"What is Wei Xiaobao's secret technique?","answer":0,"explanation_zh":"韋小寶學會了化骨綿掌。","explanation_en":"Wei Xiaobao learns the Bone Melting Palm.","difficulty":1},
    # 九品芝麻官 (1994)
    {"question_zh":"《九品芝麻官》中，包龍星為何要為戚秦氏翻案？","options_zh":["伸張正義","收了錢","被逼的","為了升官"],"options_en":["Justice","Paid","Forced","For promotion"],"question_en":"Why does Bao take on the case?","answer":0,"explanation_zh":"包龍星為伸張正義而為戚秦氏翻案。","explanation_en":"Bao takes the case for justice.","difficulty":1},
    {"question_zh":"《九品芝麻官》中，方唐鏡由誰飾演？","options_zh":["吳啟華","黃子華","張達明","林雪"],"options_en":["Ng Kai-wah","Wong Zi-wa","Cheung Tat-ming","Lam Suet"],"question_en":"Who plays Fong Tong-geng?","answer":0,"explanation_zh":"吳啟華飾演反派狀師方唐鏡。","explanation_en":"Ng Kai-wah plays the villain lawyer Fong Tong-geng.","difficulty":1},
    {"question_zh":"《九品芝麻官》中，包龍星最終的官職是什麼？","options_zh":["八府巡按","知縣","知府","尚書"],"options_en":["Circuit judge","Magistrate","Prefect","Minister"],"question_en":"What is Bao's final position?","answer":0,"explanation_zh":"包龍星最終成為八府巡按。","explanation_en":"Bao becomes a Circuit Judge.","difficulty":1},
    # 審死官 (1992)
    {"question_zh":"《審死官》中，宋世傑為何不再打官司？","options_zh":["報應","生病","退休","被禁止"],"options_en":["Karma","Illness","Retired","Banned"],"question_en":"Why does Song stop practicing law?","answer":0,"explanation_zh":"宋世傑因為報應（兒子夭折）而金盆洗手。","explanation_en":"Song stops due to karma (his son's death).","difficulty":1},
    {"question_zh":"《審死官》中，宋世傑妻子的武功叫什麼？","options_zh":["獅子吼","鐵砂掌","九陰白骨爪","無影腳"],"options_en":["Lion Roar","Iron Palm","White Bone Claw","Shadowless Kick"],"question_en":"What is his wife's martial art?","answer":0,"explanation_zh":"宋世傑妻子會獅子吼。","explanation_en":"His wife knows Lion Roar.","difficulty":1},
    # 喜劇之王 (1999)
    {"question_zh":"《喜劇之尹》中，尹天仇在什麼地方工作？","options_zh":["社區中心","電影院","劇院","電視台"],"options_en":["Community center","Cinema","Theater","TV station"],"question_en":"Where does Yin Tianchou work?","answer":0,"explanation_zh":"尹天仇在社區中心當義工，教人演戲。","explanation_en":"Yin volunteers at a community center, teaching acting.","difficulty":1},
    {"question_zh":"《喜劇之王》中，尹天仇最崇拜的演員是誰？","options_zh":["自己","周潤發","成龍","李小龍"],"options_en":["Himself","Chow Yun-fat","Jackie Chan","Bruce Lee"],"question_en":"Who is Yin's idol?","answer":0,"explanation_zh":"尹天仇最崇拜自己，自認是好演員。","explanation_en":"Yin idolizes himself, believing he's a great actor.","difficulty":1},
    {"question_zh":"《喜劇之王》的經典對白「我養你啊」是誰對誰說的？","options_zh":["尹天仇對柳飄飄","柳飄飄對尹天仇","導演對尹天仇","尹天仇對導演"],"options_en":["Yin to Liu","Liu to Yin","Director to Yin","Yin to director"],"question_en":"Who says 'I'll support you'?","answer":0,"explanation_zh":"尹天仇對柳飄飄說「我養你啊」。","explanation_en":"Yin Tianchou says it to Liu Piaopiao.","difficulty":1},
    # 破壞之王 (1994)
    {"question_zh":"《破壞之王》中，何金水為了追求誰而學武？","options_zh":["阿麗","阿Sa","阿琪","阿玲"],"options_en":["Ah Lai","Ah Sa","Ah Kei","Ah Ling"],"question_en":"Who does Ho Kam-sui learn martial arts for?","answer":0,"explanation_zh":"何金水為了追求阿麗而學武。","explanation_en":"He learns martial arts to win Ah Lai's heart.","difficulty":1},
    {"question_zh":"《破壞之王》中，何金水的師父是誰？","options_zh":["鬼王達","大師兄","魔鬼筋肉人","黑熊"],"options_en":["Ghost King Tat","Eldest Brother","Devil Muscle Man","Black Bear"],"question_en":"Who is Ho Kam-sui's master?","answer":0,"explanation_zh":"鬼王達是何金水的師父。","explanation_en":"Ghost King Tat is his master.","difficulty":1},
    # 賭俠 (1990)
    {"question_zh":"《賭俠》中，陳小刀的師父是誰？","options_zh":["賭神高進","左頌星","龍五","刀仔"],"options_en":["Ko Chun","So Chun-sing","Lung Five","Knife Boy"],"question_en":"Who is Chen Siu-dao's master?","answer":0,"explanation_zh":"陳小刀是賭神高進的徒弟。","explanation_en":"Chen Siu-dao is Ko Chun's apprentice.","difficulty":1},
    {"question_zh":"《賭俠》中，龍五由誰飾演？","options_zh":["向華強","陳惠敏","任達華","曾志偉"],"options_en":"Charles Heung,Chen Wai-man,Simon Yam,Eric Tsang".split(","),"question_en":"Who plays Lung Five?","answer":0,"explanation_zh":"向華強飾演龍五。","explanation_en":"Charles Heung plays Lung Five.","difficulty":2},
    # 百變星君 (1995)
    {"question_zh":"《百變星君》中，周星馳飾演的角色為什麼能變身？","options_zh":["被外星人改造","吃了仙丹","中了魔法","基因改造"],"options_en":["Alien modification","Magic pill","Magic spell","Gene modification"],"question_en":"Why can the character transform?","answer":0,"explanation_zh":"角色被外星人改造後能變身。","explanation_en":"The character was modified by aliens.","difficulty":1},
    # 大內密探零零發 (1996)
    {"question_zh":"《大內密探零零發》中，零零發的妻子由誰飾演？","options_zh":["劉嘉玲","朱茵","莫文蔚","邱淑貞"],"options_en":["Carina Lau","Athena Chu","Karen Mok","Chingmy Yau"],"question_en":"Who plays 008's wife?","answer":0,"explanation_zh":"劉嘉玲飾演零零發的妻子。","explanation_en":"Carina Lau plays 008's wife.","difficulty":1},
    {"question_zh":"《大內密探零零發》中，皇帝由誰飾演？","options_zh":["張達明","黃子華","林雪","羅家英"],"options_en":["Cheung Tat-ming","Wong Zi-wa","Lam Suet","Law Ka-ying"],"question_en":"Who plays the Emperor?","answer":0,"explanation_zh":"張達明飾演皇帝。","explanation_en":"Cheung Tat-ming plays the Emperor.","difficulty":2},
    # 算死草 (1997)
    {"question_zh":"《算死草》中，陳夢吉的綽號是什麼？","options_zh":["算死草","狀王","法王","訟師"],"options_en":["Calculator","King of Lawyers","Dharma King","Litigator"],"question_en":"What is Chan Mong-kat's nickname?","answer":0,"explanation_zh":"陳夢吉的綽號是「算死草」。","explanation_en":"His nickname is 'Calculator'.","difficulty":1},
    # 行運一條龍 (1998)
    {"question_zh":"《行運一條龍》中，茶餐廳的老闆由誰飾演？","options_zh":["鄭秀文","莫文蔚","朱茵","邱淑貞"],"options_en":["Sammi Cheng","Karen Mok","Athena Chu","Chingmy Yau"],"question_en":"Who plays the tea restaurant owner?","answer":0,"explanation_zh":"鄭秀文飾演茶餐廳老闆。","explanation_en":"Sammi Cheng plays the tea restaurant owner.","difficulty":1},
    # 千王之王2000 (1999)
    {"question_zh":"《千王之王2000》中，周星馳與誰合演？","options_zh":["張家輝","劉德華","吳孟達","黃秋生"],"options_en":["Nick Cheung","Andy Lau","Ng Man-tat","Anthony Wong"],"question_en":"Who co-stars in 'The Tricky Master'?","answer":0,"explanation_zh":"周星馳與張家輝合演。","explanation_en":"Stephen Chow co-stars with Nick Cheung.","difficulty":1},
    # 回魂夜 (1995)
    {"question_zh":"《回魂夜》中，周星馳飾演的角色有什麼特點？","options_zh":["自稱捉鬼專家","自稱道士","自稱和尚","自稱法師"],"options_en":["Self-proclaimed ghost buster","Taoist priest","Monk","Mage"],"question_en":"What is the character's claim?","answer":0,"explanation_zh":"角色自稱是捉鬼專家。","explanation_en":"He claims to be a ghost-catching expert.","difficulty":1},
    # 功夫2/美人魚2
    {"question_zh":"周星馳執導的《新喜劇之王》（2019）中，女主角由誰飾演？","options_zh":["鄂靖文","林允","張雨綺","趙薇"],"options_en":["E Jingwen","Lin Yun","Zhang Yuqi","Zhao Wei"],"question_en":"Who is the lead actress in 'The New King of Comedy'?","answer":0,"explanation_zh":"鄂靖文飾演女主角。","explanation_en":"E Jingwen plays the lead role.","difficulty":1},
    # 綜合問題
    {"question_zh":"周星馳的電影公司叫什麼？","options_zh":["星輝海外","天下一","中國星","英皇"],"options_en":["Star Overseas","One Cool","China Star","Emperor"],"question_en":"What is Stephen Chow's production company?","answer":0,"explanation_zh":"周星馳創辦星輝海外有限公司。","explanation_en":"Stephen Chow founded Star Overseas.","difficulty":2},
    {"question_zh":"周星馳在哪一年獲得香港特區政府頒授銅紫荊星章？","options_zh":["2001年","2003年","2005年","2008年"],"options_en":["2001","2003","2005","2008"],"question_en":"When was Stephen Chow awarded the Bronze Bauhinia Star?","answer":1,"explanation_zh":"周星馳2003年獲頒銅紫荊星章。","explanation_en":"Stephen Chow received the Bronze Bauhinia Star in 2003.","difficulty":2},
    {"question_zh":"周星馳的祖籍是哪裡？","options_zh":["浙江寧波","廣東開平","上海","福建"],"options_en":["Ningbo, Zhejiang","Kaiping, Guangdong","Shanghai","Fujian"],"question_en":"Where is Stephen Chow's ancestral home?","answer":0,"explanation_zh":"周星馳祖籍浙江寧波。","explanation_en":"Stephen Chow's ancestral home is Ningbo, Zhejiang.","difficulty":2},
    {"question_zh":"周星馳出生於哪一年？","options_zh":["1960年","1962年","1964年","1966年"],"options_en":["1960","1962","1964","1966"],"question_en":"In which year was Stephen Chow born?","answer":1,"explanation_zh":"周星馳1962年6月22日出生。","explanation_en":"Born June 22, 1962.","difficulty":1},
    {"question_zh":"周星馳出道時是哪間電視台的藝員？","options_zh":["無綫電視（TVB）","亞洲電視（ATV）","佳藝電視","有線電視"],"options_en":["TVB","ATV","RTV","Cable TV"],"question_en":"Which TV station did he start at?","answer":0,"explanation_zh":"周星馳1980年代在TVB出道。","explanation_en":"Stephen Chow started at TVB in the 1980s.","difficulty":1},
    {"question_zh":"周星馳在TVB主持過什麼兒童節目？","options_zh":["430穿梭機","歡樂今宵","K-100","城市追擊"],"options_en":["430 Shuttle","Enjoy Yourself Tonight","K-100","City Chase"],"question_en":"What children's show did he host on TVB?","answer":0,"explanation_zh":"周星馳曾主持《430穿梭機》。","explanation_en":"He hosted '430 Shuttle'.","difficulty":1},
    {"question_zh":"以下哪部電影不是周星馳執導的？","options_zh":["《逃學威龍》","《少林足球》","《功夫》","《美人魚》"],"options_en":["Fight Back to School","Shaolin Soccer","Kung Fu Hustle","The Mermaid"],"question_en":"Which film was NOT directed by Stephen Chow?","answer":0,"explanation_zh":"《逃學威龍》由陳嘉上執導。","explanation_en":"Fight Back to School was directed by Gordon Chan.","difficulty":1},
    {"question_zh":"周星馳與吳孟達合作的第一部電影是什麼？","options_zh":["《霹靂先鋒》","《賭聖》","《逃學威龍》","《整蠱專家》"],"options_en":["Final Justice","All for the Winner","Fight Back to School","Tricky Brains"],"question_en":"What was their first film together?","answer":0,"explanation_zh":"兩人首次合作是《霹靂先鋒》（1988）。","explanation_en":"Their first collaboration was 'Final Justice' (1988).","difficulty":2},
    {"question_zh":"吳孟達於哪一年去世？","options_zh":["2019年","2020年","2021年","2022年"],"options_en":["2019","2020","2021","2022"],"question_en":"When did Ng Man-tat pass away?","answer":2,"explanation_zh":"吳孟達於2021年2月27日去世。","explanation_en":"Ng Man-tat passed away on February 27, 2021.","difficulty":1},
    {"question_zh":"周星馳的代表作《功夫》獲得了什麼國際獎項？","options_zh":["康城影展金棕櫚獎提名","奧斯卡最佳外語片提名","金球獎提名","以上皆是"],"options_en":["Cannes Palme d'Or nomination","Oscar Best Foreign nomination","Golden Globe nomination","All of the above"],"question_en":"What international awards did 'Kung Fu Hustle' receive?","answer":3,"explanation_zh":"《功夫》獲得康城、奧斯卡、金球獎等多項提名。","explanation_en":"Kung Fu Hustle received nominations at Cannes, Oscars, and Golden Globes.","difficulty":2},
    {"question_zh":"以下哪位演員沒有出演過周星馳的電影？","options_zh":["張國榮","莫文蔚","朱茵","張柏芝"],"options_en":["Leslie Cheung","Karen Mok","Athena Chu","Cecilia Cheung"],"question_en":"Which actor has NOT appeared in a Stephen Chow film?","answer":0,"explanation_zh":"張國榮從未出演過周星馳的電影。","explanation_en":"Leslie Cheung never appeared in a Stephen Chow film.","difficulty":2},
    {"question_zh":"周星馳的「無厘頭」喜劇風格受什麼影響？","options_zh":["許氏兄弟喜劇","粵語殘片","西方喜劇","以上皆是"],"options_en":["Hui Brothers comedy","Old Cantonese films","Western comedy","All of the above"],"question_en":"What influenced Stephen Chow's 'mo lei tau' comedy style?","answer":3,"explanation_zh":"無厘頭風格融合了許氏兄弟喜劇、粵語殘片和西方喜劇元素。","explanation_en":"His style combines elements from Hui Brothers, old Cantonese films, and Western comedy.","difficulty":2},
    {"question_zh":"《唐伯虎點秋香》中，四大才子出場時的經典畫面是什麼？","options_zh":["搖扇走路","騎馬","划船","坐轎"],"options_en":["Walking with fans","Riding horses","Boating","Sedan chairs"],"question_en":"How do the Four Scholars appear in their classic entrance?","answer":0,"explanation_zh":"四大才子搖扇走路出場。","explanation_en":"The Four Scholars walk in while waving fans.","difficulty":1},
    {"question_zh":"《功夫》中，斧頭幫幫主由誰飾演？","options_zh":["陳國坤","林子聰","元華","黃聖依"],"options_en":["Danny Chan","Lam Tze-chung","Yuen Wah","Huang Shengyi"],"question_en":"Who plays the Axe Gang leader?","answer":0,"explanation_zh":"陳國坤飾演斧頭幫幫主。","explanation_en":"Danny Chan plays the Axe Gang leader.","difficulty":2},
    {"question_zh":"《少林足球》中，魔鬼隊教練由誰飾演？","options_zh":["謝賢","曾志偉","黃秋生","劉洵"],"options_en":["Patrick Tse","Eric Tsang","Anthony Wong","Lau Shun"],"question_en":"Who plays the Devil Team coach?","answer":0,"explanation_zh":"謝賢飾演魔鬼隊教練。","explanation_en":"Patrick Tse plays the Devil Team coach.","difficulty":2},
    {"question_zh":"周星馳的「I服了You」這句對白出自哪部電影？","options_zh":["《大話西遊》","《唐伯虎點秋香》","《食神》","《功夫》"],"options_en":["A Chinese Odyssey","Flirting Scholar","God of Cookery","Kung Fu Hustle"],"question_en":"Which film has the line 'I服了You'?","answer":0,"explanation_zh":"這句經典對白出自《大話西遊》。","explanation_en":"This classic line is from 'A Chinese Odyssey'.","difficulty":1},
]
w("stephen_chow.json", sc)

# ═══════════════════════════════════════════
# 劉德華系列 - 100 questions
# ═══════════════════════════════════════════
al = [
    # 無間道 (2002)
    {"question_zh":"《無間道》中，劉建明在警隊的職位是什麼？","options_zh":["見習督察","高級督察","總督察","警司"],"options_en":["Probationary Inspector","Senior Inspector","Chief Inspector","Superintendent"],"question_en":"What is Lau Kin-ming's police rank?","answer":0,"explanation_zh":"劉建明是見習督察。","explanation_en":"Lau Kin-ming is a Probationary Inspector.","difficulty":1},
    {"question_zh":"《無間道》中，韓琛由誰飾演？","options_zh":["曾志偉","黃秋生","吳鎮宇","林家棟"],"options_en":["Eric Tsang","Anthony Wong","Francis Ng","Lam Ka-tung"],"question_en":"Who plays Hon Sam?","answer":0,"explanation_zh":"曾志偉飾演黑幫大佬韓琛。","explanation_en":"Eric Tsang plays triad boss Hon Sam.","difficulty":1},
    {"question_zh":"《無間道》的經典場景在天台，劉建明說了什麼經典對白？","options_zh":["「我想做好人」","「對唔住，我係警察」","「以前嘅事就由得佢過去」","「你有冇試過做好人？」"],"options_en":["I want to be a good person","Sorry, I'm a cop","Let the past go","Have you ever tried being good?"],"question_en":"What is Lau Kin-ming's classic rooftop line?","answer":0,"explanation_zh":"劉建明說「我想做好人」。","explanation_en":"Lau Kin-ming says 'I want to be a good person.'","difficulty":1},
    {"question_zh":"《無間道》的導演是誰？","options_zh":["劉偉強、麥兆輝","杜琪峰","王家衛","陳可辛"],"options_en":["Andrew Lau & Alan Mak","Johnnie To","Wong Kar-wai","Peter Chan"],"question_en":"Who directed 'Infernal Affairs'?","answer":0,"explanation_zh":"由劉偉強和麥兆輝聯合執導。","explanation_en":"Directed by Andrew Lau and Alan Mak.","difficulty":1},
    {"question_zh":"《無間道II》（2003）中，年輕版劉建明由誰飾演？","options_zh":["陳冠希","余文樂","謝霆鋒","吳彥祖"],"options_en":["Edison Chen","Shawn Yue","Nicholas Tse","Daniel Wu"],"question_en":"Who plays young Lau Kin-ming in 'Infernal Affairs II'?","answer":0,"explanation_zh":"陳冠希飾演年輕版劉建明。","explanation_en":"Edison Chen plays young Lau Kin-ming.","difficulty":1},
    {"question_zh":"《無間道》中，黃志誠由誰飾演？","options_zh":["黃秋生","曾志偉","吳鎮宇","林家棟"],"options_en":["Anthony Wong","Eric Tsang","Francis Ng","Lam Ka-tung"],"question_en":"Who plays Wong Chi-sing?","answer":0,"explanation_zh":"黃秋生飾演黃志誠警司。","explanation_en":"Anthony Wong plays Superintendent Wong.","difficulty":1},
    # 暗戰 (1999)
    {"question_zh":"《暗戰》中，劉德華的角色為什麼要犯罪？","options_zh":["報仇","為錢","好玩","被逼"],"options_en":["Revenge","Money","Fun","Forced"],"question_en":"Why does his character commit crimes?","answer":0,"explanation_zh":"角色為了報仇而犯罪。","explanation_en":"His character commits crimes for revenge.","difficulty":1},
    {"question_zh":"《暗戰》中，劉德華與誰演對手戲？","options_zh":["劉青雲","梁朝偉","古天樂","張家輝"],"options_en":["Sean Lau","Tony Leung","Louis Koo","Nick Cheung"],"question_en":"Who is his co-star in 'Running Out of Time'?","answer":0,"explanation_zh":"劉德華與劉青雲演對手戲。","explanation_en":"He co-stars with Sean Lau.","difficulty":1},
    # 桃姐 (2012)
    {"question_zh":"《桃姐》中，桃姐由誰飾演？","options_zh":["葉德嫻","惠英紅","鮑起靜","羅蘭"],"options_en":["Deannie Yip","Kara Hui","Paw Hee-ching","Law Lan"],"question_en":"Who plays Sister Peach?","answer":0,"explanation_zh":"葉德嫻飾演桃姐，並獲得康城影后。","explanation_en":"Deannie Yip plays Sister Peach, winning Cannes Best Actress.","difficulty":1},
    {"question_zh":"《桃姐》的導演是誰？","options_zh":["許鞍華","王家衛","陳可辛","杜琪峰"],"options_en":["Ann Hui","Wong Kar-wai","Peter Chan","Johnnie To"],"question_en":"Who directed 'A Simple Life'?","answer":0,"explanation_zh":"許鞍華執導《桃姐》。","explanation_en":"Directed by Ann Hui.","difficulty":1},
    {"question_zh":"《桃姐》獲得什麼國際獎項？","options_zh":["康城影展最佳女主角","威尼斯影展金獅獎","柏林影展金熊獎","奧斯卡最佳外語片"],"options_en":["Cannes Best Actress","Venice Golden Lion","Berlin Golden Bear","Oscar Best Foreign"],"question_en":"What international award did it win?","answer":0,"explanation_zh":"葉德嫻憑《桃姐》獲得康城影后。","explanation_en":"Deannie Yip won Cannes Best Actress.","difficulty":1},
    # 拆彈專家 (2017/2020)
    {"question_zh":"《拆彈專家》（2017）中，反派由誰飾演？","options_zh":["姜武","吳京","甄子丹","張家輝"],"options_en":["Jiang Wu","Wu Jing","Donnie Yen","Nick Cheung"],"question_en":"Who plays the villain in 'Shock Wave'?","answer":0,"explanation_zh":"姜武飾演反派。","explanation_en":"Jiang Wu plays the villain.","difficulty":1},
    {"question_zh":"《拆彈專家2》（2020）中，劉德華的角色有什麼遭遇？","options_zh":["失去一條腿","失憶","被陷害","以上皆是"],"options_en":["Loses a leg","Amnesia","Framed","All of the above"],"question_en":"What happens to his character in 'Shock Wave 2'?","answer":3,"explanation_zh":"角色經歷爆炸後失去一條腿、失憶，同時被陷害。","explanation_en":"His character loses a leg, has amnesia, and is framed.","difficulty":1},
    # 天下無賊 (2004)
    {"question_zh":"《天下無賊》中，傻根由誰飾演？","options_zh":["王寶強","黃渤","徐崢","沈騰"],"options_en":["Wang Baoqiang","Huang Bo","Xu Zheng","Shen Teng"],"question_en":"Who plays the naive man?","answer":0,"explanation_zh":"王寶強飾演傻根。","explanation_en":"Wang Baoqiang plays the naive man.","difficulty":1},
    # 瘦身男女 (2001)
    {"question_zh":"《瘦身男女》中，鄭秀文飾演什麼角色？","options_zh":["肥女Mini","瘦女","律師","醫生"],"options_en":["Fat girl Mini","Thin girl","Lawyer","Doctor"],"question_en":"What role does Sammi Cheng play?","answer":0,"explanation_zh":"鄭秀文飾演肥女Mini。","explanation_en":"Sammi Cheng plays fat girl Mini.","difficulty":1},
    # 孤男寡女 (2000)
    {"question_zh":"《孤男寡女》中，劉德華和鄭秀文飾演什麼關係？","options_zh":["同事兼戀人","夫妻","仇人","師徒"],"options_en":["Colleagues & lovers","Married couple","Enemies","Master & disciple"],"question_en":"What is their relationship?","answer":0,"explanation_zh":"兩人飾演同事，後來發展成戀人。","explanation_en":"They play colleagues who become lovers.","difficulty":1},
    # 投名狀 (2007)
    {"question_zh":"《投名狀》中，三兄弟分別是誰？","options_zh":["龐青雲、趙二虎、姜午陽","劉建明、陳永仁、韓琛","李雲龍、趙剛、楚雲飛","唐龍、陳真、霍元甲"],"options_en":["Pang, Zhao, Jiang","Lau, Chan, Hon","Li, Zhao, Chu","Tang, Chen, Huo"],"question_en":"Who are the three sworn brothers?","answer":0,"explanation_zh":"龐青雲（李連杰）、趙二虎（劉德華）、姜午陽（金城武）。","explanation_en":"Pang (Jet Li), Zhao (Andy Lau), Jiang (Takeshi Kaneshiro).","difficulty":1},
    {"question_zh":"《投名狀》的導演是誰？","options_zh":["陳可辛","杜琪峰","許鞍華","徐克"],"options_en":["Peter Chan","Johnnie To","Ann Hui","Tsui Hark"],"question_en":"Who directed 'The Warlords'?","answer":0,"explanation_zh":"陳可辛執導《投名狀》。","explanation_en":"Directed by Peter Chan.","difficulty":1},
    # 墨攻 (2006)
    {"question_zh":"《墨攻》中，革離代表什麼學派？","options_zh":["墨家","儒家","道家","法家"],"options_en":["Mohism","Confucianism","Taoism","Legalism"],"question_en":"What school does Ge Li represent?","answer":0,"explanation_zh":"革離代表墨家學派。","explanation_en":"Ge Li represents Mohism.","difficulty":1},
    # 失孤 (2015)
    {"question_zh":"《失孤》中，劉德華飾演什麼角色？","options_zh":["尋找失散兒子的父親","警察","醫生","老師"],"options_en":["Father searching for lost son","Police officer","Doctor","Teacher"],"question_en":"What role does he play in 'Lost and Love'?","answer":0,"explanation_zh":"劉德華飾演一個尋找失散兒子14年的父親。","explanation_en":"He plays a father searching for his lost son for 14 years.","difficulty":1},
    # 掃毒 (2013)
    {"question_zh":"《掃毒》中，三兄弟分別由誰飾演？","options_zh":["劉德華、古天樂、張家輝","劉德華、梁朝偉、古天樂","劉德華、張家輝、吳鎮宇","劉德華、古天樂、謝霆鋒"],"options_en":["Andy, Louis, Nick","Andy, Tony, Louis","Andy, Nick, Francis","Andy, Louis, Nicholas"],"question_en":"Who plays the three brothers in 'The White Storm'?","answer":0,"explanation_zh":"劉德華、古天樂、張家輝飾演三兄弟。","explanation_en":"Andy Lau, Louis Koo, and Nick Cheung play the three brothers.","difficulty":1},
    # 門徒 (2007)
    {"question_zh":"《門徒》中，劉德華飾演什麼角色？","options_zh":["大毒梟","卧底警察","律師","醫生"],"options_en":["Drug lord","Undercover cop","Lawyer","Doctor"],"question_en":"What role does he play in 'Protege'?","answer":0,"explanation_zh":"劉德華飾演大毒梟林昆。","explanation_en":"He plays drug lord Lin Kun.","difficulty":1},
    {"question_zh":"《門徒》中，與劉德華合作的臥底由誰飾演？","options_zh":["吳彥祖","古天樂","張家輝","謝霆鋒"],"options_en":["Daniel Wu","Louis Koo","Nick Cheung","Nicholas Tse"],"question_en":"Who plays the undercover agent?","answer":0,"explanation_zh":"吳彥祖飾演卧底警察。","explanation_en":"Daniel Wu plays the undercover agent.","difficulty":1},
    # 綜合問題
    {"question_zh":"劉德華的唱片銷量超過多少張？","options_zh":["1億張","5000萬張","2億張","5億張"],"options_en":["100 million","50 million","200 million","500 million"],"question_en":"How many records has Andy Lau sold?","answer":0,"explanation_zh":"劉德華的唱片銷量超過1億張。","explanation_en":"Andy Lau has sold over 100 million records.","difficulty":2},
    {"question_zh":"劉德華獲得過幾次香港十大勁歌金曲最受歡迎男歌星？","options_zh":["3次","5次","7次","10次"],"options_en":["3","5","7","10"],"question_en":"How many times has he won Most Popular Male Singer?","answer":2,"explanation_zh":"劉德華7次獲得最受歡迎男歌星。","explanation_en":"Andy Lau won Most Popular Male Singer 7 times.","difficulty":2},
    {"question_zh":"劉德華的經典歌曲《忘情水》是哪一年推出的？","options_zh":["1992年","1994年","1996年","1998年"],"options_en":["1992","1994","1996","1998"],"question_en":"When was 'Erta de Agua' released?","answer":1,"explanation_zh":"《忘情水》1994年推出。","explanation_en":"Released in 1994.","difficulty":2},
    {"question_zh":"劉德華與梅艷芳合演的經典電影是什麼？","options_zh":["《91神鵰俠侶》","《審死官》","《瘦身男女》","《孤男寡女》"],"options_en":["Saviour of the Soul","Justice My Foot","Love on a Diet","Needing You"],"question_en":"What classic film did Andy co-star with Anita Mui?","answer":0,"explanation_zh":"兩人合演《91神鵰俠侶》。","explanation_en":"They co-starred in 'Saviour of the Soul'.","difficulty":2},
    {"question_zh":"劉德華是「天幕」電影公司的創辦人嗎？","options_zh":["是","不是"],"options_en":["Yes","No"],"question_en":"Did Andy Lau found Teamwork Pictures?","answer":0,"explanation_zh":"劉德華創辦了天幕電影公司。","explanation_en":"Yes, Andy Lau founded Teamwork Pictures.","difficulty":2},
    {"question_zh":"劉德華在《無間道》中飾演的角色最後結局如何？","options_zh":["被捕","逃脫","死亡","成為好人"],"options_en":["Arrested","Escaped","Death","Becomes good"],"question_en":"What happens to Lau Kin-ming at the end?","answer":0,"explanation_zh":"劉建明最後被逮捕。","explanation_en":"Lau Kin-ming is arrested.","difficulty":1},
    {"question_zh":"劉德華的官方歌迷會叫什麼？","options_zh":["華仔天地","華迷會","Andy Club","劉德華歌迷會"],"options_en":["Andy World Club","Hua Fan Club","Andy Club","Andy Lau Fan Club"],"question_en":"What is his official fan club called?","answer":0,"explanation_zh":"劉德華的官方歌迷會叫「華仔天地」。","explanation_en":"His official fan club is 'Andy World Club'.","difficulty":1},
    {"question_zh":"劉德華在哪一年舉辦首場演唱會？","options_zh":["1985年","1988年","1990年","1993年"],"options_en":["1985","1988","1990","1993"],"question_en":"When was his first concert?","answer":1,"explanation_zh":"劉德華1988年舉辦首場個人演唱會。","explanation_en":"His first solo concert was in 1988.","difficulty":2},
    {"question_zh":"劉德華與哪位導演合作最多次？","options_zh":["杜琪峰","王家衛","劉偉強","陳可辛"],"options_en":["Johnnie To","Wong Kar-wai","Andrew Lau","Peter Chan"],"question_en":"Which director has he worked with most?","answer":0,"explanation_zh":"劉德華與杜琪峰合作最多次。","explanation_en":"He has worked most with Johnnie To.","difficulty":2},
    {"question_zh":"劉德華主演的《阿虎》（2000）中，他飾演什麼角色？","options_zh":["拳手","警察","商人","老師"],"options_en":["Boxer","Police officer","Businessman","Teacher"],"question_en":"What role does he play in 'A Fighter's Blues'?","answer":0,"explanation_zh":"劉德華飾演拳手。","explanation_en":"He plays a boxer.","difficulty":1},
    {"question_zh":"劉德華憑哪部電影首次獲得金像獎影帝？","options_zh":["《暗戰》","《大隻佬》","《桃姐》","《無間道》"],"options_en":["Running Out of Time","Running on Karma","A Simple Life","Infernal Affairs"],"question_en":"For which film did he first win Best Actor?","answer":0,"explanation_zh":"劉德華憑《暗戰》（1999）首次獲得金像獎影帝。","explanation_en":"He first won for 'Running Out of Time' (1999).","difficulty":1},
    {"question_zh":"劉德華的星座是什麼？","options_zh":["天秤座","天蠍座","處女座","獅子座"],"options_en":["Libra","Scorpio","Virgo","Leo"],"question_en":"What is Andy Lau's zodiac sign?","answer":0,"explanation_zh":"劉德華9月27日出生，是天秤座。","explanation_en":"Born September 27, he is a Libra.","difficulty":1},
    {"question_zh":"劉德華在《全職殺手》（2001）中飾演什麼角色？","options_zh":["殺手","警察","卧底","商人"],"options_en":["Hitman","Police","Undercover","Businessman"],"question_en":"What role in 'Fulltime Killer'?","answer":0,"explanation_zh":"劉德華飾演殺手O。","explanation_en":"He plays hitman O.","difficulty":1},
    {"question_zh":"劉德華與周杰倫合演的電影是什麼？","options_zh":["《天下無賊》","《頭文字D》","《功夫》","《長城》"],"options_en":["A World Without Thieves","Initial D","Kung Fu Hustle","The Great Wall"],"question_en":"Which film did Andy star with Jay Chou?","answer":1,"explanation_zh":"兩人合演《頭文字D》（2005）。","explanation_en":"They co-starred in 'Initial D' (2005).","difficulty":1},
    {"question_zh":"劉德華在《寒戰》（2012）中飾演什麼職業？","options_zh":["警務處副處長","廉政公署","律師","法官"],"options_en":["Deputy Police Commissioner","ICAC","Lawyer","Judge"],"question_en":"What is his role in 'Cold War'?","answer":0,"explanation_zh":"劉德華飾演警務處副處長。","explanation_en":"He plays the Deputy Police Commissioner.","difficulty":1},
    {"question_zh":"劉德華的歌曲《中國人》是哪一年推出的？","options_zh":["1995年","1997年","1999年","2001年"],"options_en":["1995","1997","1999","2001"],"question_en":"When was the song 'Chinese People' released?","answer":1,"explanation_zh":"《中國人》1997年推出，慶祝回歸。","explanation_en":"Released in 1997 to celebrate the handover.","difficulty":2},
    {"question_zh":"劉德華在《風暴》（2013）中飾演什麼角色？","options_zh":["警察","悍匪","律師","法官"],"options_en":["Police officer","Gangster","Lawyer","Judge"],"question_en":"What role in 'Firestorm'?","answer":0,"explanation_zh":"劉德華飾演警察。","explanation_en":"He plays a police officer.","difficulty":1},
    {"question_zh":"劉德華獲得過多少個吉尼斯世界紀錄？","options_zh":["1個","2個","3個","5個"],"options_en":["1","2","3","5"],"question_en":"How many Guinness World Records does he hold?","answer":2,"explanation_zh":"劉德華獲得3個吉尼斯世界紀錄。","explanation_en":"He holds 3 Guinness World Records.","difficulty":2},
    {"question_zh":"劉德華在《金手指》（2023）中與誰合演？","options_zh":["梁朝偉","古天樂","張家輝","謝霆鋒"],"options_en":["Tony Leung","Louis Koo","Nick Cheung","Nicholas Tse"],"question_en":"Who co-stars in 'The Goldfinger'?","answer":0,"explanation_zh":"劉德華與梁朝偉合演《金手指》。","explanation_en":"He co-stars with Tony Leung.","difficulty":1},
]
w("andy_lau.json", al)

# ═══════════════════════════════════════════
# 梁朝偉系列 - 100 questions
# ═══════════════════════════════════════════
tl = [
    # 花樣年華 (2000)
    {"question_zh":"《花樣年華》的故事發生在哪個年代？","options_zh":["1960年代","1970年代","1980年代","1990年代"],"options_en":["1960s","1970s","1980s","1990s"],"question_en":"When is 'In the Mood for Love' set?","answer":0,"explanation_zh":"故事發生在1960年代的香港。","explanation_en":"Set in 1960s Hong Kong.","difficulty":1},
    {"question_zh":"《花樣年華》中，周慕雲和蘇麗珍的關係是？","options_zh":["鄰居","同事","戀人","同學"],"options_en":["Neighbors","Colleagues","Lovers","Classmates"],"question_en":"What is their relationship?","answer":0,"explanation_zh":"兩人是鄰居，發現各自的配偶有婚外情。","explanation_en":"They are neighbors whose spouses are having affairs.","difficulty":1},
    {"question_zh":"《花樣年華》的配樂以什麼樂器為主？","options_zh":["小提琴","大提琴","鋼琴","二胡"],"options_en":["Violin","Cello","Piano","Erhu"],"question_en":"What instrument dominates the soundtrack?","answer":0,"explanation_zh":"配樂以小提琴為主，由梅林茂作曲。","explanation_en":"The soundtrack is violin-dominated, composed by Shigeru Umebayashi.","difficulty":2},
    {"question_zh":"《花樣年華》中，蘇麗珍的職業是什麼？","options_zh":["秘書","空姐","教師","護士"],"options_en":["Secretary","Stewardess","Teacher","Nurse"],"question_en":"What is Su Li-zhen's job?","answer":0,"explanation_zh":"蘇麗珍是秘書。","explanation_en":"Su Li-zhen is a secretary.","difficulty":1},
    # 春光乍洩 (1997)
    {"question_zh":"《春光乍洩》的故事發生在哪個城市？","options_zh":["布宜諾斯艾利斯","巴黎","倫敦","紐約"],"options_en":["Buenos Aires","Paris","London","New York"],"question_en":"Where is 'Happy Together' set?","answer":0,"explanation_zh":"故事發生在阿根廷布宜諾斯艾利斯。","explanation_en":"Set in Buenos Aires, Argentina.","difficulty":1},
    {"question_zh":"《春光乍洩》獲得什麼國際獎項？","options_zh":["康城影展最佳導演","威尼斯金獅獎","柏林金熊獎","奧斯卡最佳外語片"],"options_en":["Cannes Best Director","Venice Golden Lion","Berlin Golden Bear","Oscar Best Foreign"],"question_en":"What award did it win?","answer":0,"explanation_zh":"王家衛獲得康城影展最佳導演。","explanation_en":"Wong Kar-wai won Best Director at Cannes.","difficulty":1},
    {"question_zh":"《春光乍洩》中，何寶榮由誰飾演？","options_zh":["張國榮","梁朝偉","劉德華","古天樂"],"options_en":["Leslie Cheung","Tony Leung","Andy Lau","Louis Koo"],"question_en":"Who plays Ho Po-wing?","answer":0,"explanation_zh":"張國榮飾演何寶榮。","explanation_en":"Leslie Cheung plays Ho Po-wing.","difficulty":1},
    # 色，戒 (2007)
    {"question_zh":"《色，戒》改編自哪位作家的小說？","options_zh":["張愛玲","白先勇","金庸","余華"],"options_en":["Eileen Pai","Pai Hsien-yung","Jin Yong","Yu Hua"],"question_en":"Which author's novel is 'Lust, Caution' based on?","answer":0,"explanation_zh":"改編自張愛玲的同名小說。","explanation_en":"Based on Eileen Chang's novella.","difficulty":1},
    {"question_zh":"《色，戒》中，王佳芝由誰飾演？","options_zh":["湯唯","章子怡","鞏俐","周迅"],"options_en":["Tang Wei","Zhang Ziyi","Gong Li","Zhou Xun"],"question_en":"Who plays Wong Chia-chi?","answer":0,"explanation_zh":"湯唯飾演王佳芝，是她的成名作。","explanation_en":"Tang Wei plays Wong Chia-chi in her breakout role.","difficulty":1},
    {"question_zh":"《色，戒》獲得什麼國際大獎？","options_zh":["威尼斯金獅獎","康城金棕櫚獎","柏林金熊獎","奧斯卡最佳影片"],"options_en":["Venice Golden Lion","Cannes Palme d'Or","Berlin Golden Bear","Oscar Best Picture"],"question_en":"What major award did it win?","answer":0,"explanation_zh":"《色，戒》獲得威尼斯影展金獅獎。","explanation_en":"It won the Venice Golden Lion.","difficulty":1},
    # 一代宗師 (2013)
    {"question_zh":"《一代宗師》中，宮二由誰飾演？","options_zh":["章子怡","鞏俐","湯唯","周迅"],"options_en":["Zhang Ziyi","Gong Li","Tang Wei","Zhou Xun"],"question_en":"Who plays Gong Er?","answer":0,"explanation_zh":"章子怡飾演宮二。","explanation_en":"Zhang Ziyi plays Gong Er.","difficulty":1},
    {"question_zh":"《一代宗師》中，葉問的武術是什麼？","options_zh":["詠春拳","太極拳","八卦掌","形意拳"],"options_en":["Wing Chun","Tai Chi","Bagua","Xingyi"],"question_en":"What martial art does Ip Man practice?","answer":0,"explanation_zh":"葉問精通詠春拳。","explanation_en":"Ip Man practices Wing Chun.","difficulty":1},
    {"question_zh":"《一代宗師》中，馬三由誰飾演？","options_zh":["張晉","甄子丹","吳京","趙文卓"],"options_en":["Zhang Jin","Donnie Yen","Wu Jing","Zhao Wenzhuo"],"question_en":"Who plays Ma San?","answer":0,"explanation_zh":"張晉飾演叛徒馬三。","explanation_en":"Zhang Jin plays the traitor Ma San.","difficulty":1},
    # 重慶森林 (1994)
    {"question_zh":"《重慶森林》中，王菲飾演什麼角色？","options_zh":["快餐店店員","空姐","模特兒","學生"],"options_en":["Fast food worker","Stewardess","Model","Student"],"question_en":"What role does Faye Wong play?","answer":0,"explanation_zh":"王菲飾演快餐店店員阿菲。","explanation_en":"Faye Wong plays fast food worker Faye.","difficulty":1},
    {"question_zh":"《重慶森林》中，警察663的戀人由誰飾演？","options_zh":["周嘉玲","林青霞","王菲","張曼玉"],"options_en":["Valerie Chow","Brigitte Lin","Faye Wong","Maggie Cheung"],"question_en":"Who plays Officer 663's girlfriend?","answer":0,"explanation_zh":"周嘉玲飾演663的空姐女友。","explanation_en":"Valerie Chow plays his stewardess girlfriend.","difficulty":2},
    # 阿飛正傳 (1990)
    {"question_zh":"《阿飛正傳》中，張國榮飾演的角色叫什麼？","options_zh":["旭仔","阿飛","小混混","浪子"],"options_en":["Ah Fei","Ruffian","Little punk","Wanderer"],"question_en":"What is Leslie Cheung's character name?","answer":0,"explanation_zh":"張國榮飾演旭仔。","explanation_en":"Leslie Cheung plays Ah Fei (旭仔).","difficulty":1},
    {"question_zh":"《阿飛正傳》的經典台詞「一分鐘」是誰對誰說的？","options_zh":["旭仔對蘇麗珍","蘇麗珍對旭仔","旭仔對露露","露露對旭仔"],"options_en":["Ah Fei to Su","Su to Ah Fei","Ah Fei to Lulu","Lulu to Ah Fei"],"question_en":"Who says the 'one minute' line?","answer":0,"explanation_zh":"旭仔對蘇麗珍說「1960年4月16號下午三點之前的一分鐘」。","explanation_en":"Ah Fei says it to Su Li-zhen about one minute before 3pm on April 16, 1960.","difficulty":1},
    # 東邪西毒 (1994)
    {"question_zh":"《東邪西毒》中，梁朝偉飾演誰？","options_zh":["盲劍客","黃藥師","歐陽鋒","洪七"],"options_en":["Blind Swordsman","Huang Yaoshi","Ouyang Feng","Hong Qi"],"question_en":"Who does Tony Leung play in 'Ashes of Time'?","answer":0,"explanation_zh":"梁朝偉飾演盲劍客。","explanation_en":"Tony Leung plays the Blind Swordsman.","difficulty":1},
    {"question_zh":"《東邪西毒》中，歐陽鋒由誰飾演？","options_zh":["張國榮","梁朝偉","梁家輝","張學友"],"options_en":["Leslie Cheung","Tony Leung","Tony Leung Ka-fai","Jacky Cheung"],"question_en":"Who plays Ouyang Feng?","answer":0,"explanation_zh":"張國榮飾演歐陽鋒。","explanation_en":"Leslie Cheung plays Ouyang Feng.","difficulty":1},
    # 倩女幽魂 (1987) - TVB時期
    {"question_zh":"梁朝偉在TVB版《鹿鼎記》（1984）中飾演誰？","options_zh":["韋小寶","康熙","陳近南","多隆"],"options_en":["Wei Xiaobao","Kangxi","Chen Jinnan","Dolong"],"question_en":"Who does he play in TVB's 'Royal Tramp'?","answer":0,"explanation_zh":"梁朝偉飾演韋小寶。","explanation_en":"He plays Wei Xiaobao.","difficulty":1},
    {"question_zh":"梁朝偉與劉嘉玲在哪一年結婚？","options_zh":["2006年","2008年","2010年","2012年"],"options_en":["2006","2008","2010","2012"],"question_en":"When did Tony and Carina marry?","answer":1,"explanation_zh":"2008年在不丹結婚。","explanation_en":"They married in Bhutan in 2008.","difficulty":1},
    # 尚氣 (2021)
    {"question_zh":"《尚氣與十環傳奇》中，尚氣由誰飾演？","options_zh":["劉思慕","彭于晏","吳亦凡","王力宏"],"options_en":["Simu Liu","Eddie Peng","Kris Wu","Wang Leehom"],"question_en":"Who plays Shang-Chi?","answer":0,"explanation_zh":"劉思慕飾演尚氣。","explanation_en":"Simu Liu plays Shang-Chi.","difficulty":1},
    {"question_zh":"《尚氣》中，十環是什麼？","options_zh":["武器","組織","城市","人物"],"options_en":["Weapon","Organization","City","Person"],"question_en":"What are the Ten Rings?","answer":0,"explanation_zh":"十環是賦予持有者力量的武器。","explanation_en":"The Ten Rings are weapons that grant power to the wielder.","difficulty":1},
    # 悲情城市 (1989)
    {"question_zh":"梁朝偉憑哪部電影首次獲得金像獎影帝？","options_zh":["《重慶森林》","《春光乍洩》","《花樣年華》","《無間道》"],"options_en":["Chungking Express","Happy Together","In the Mood for Love","Infernal Affairs"],"question_en":"Which film was his first Best Actor win?","answer":0,"explanation_zh":"梁朝偉憑《重慶森林》首次獲得金像獎影帝。","explanation_en":"He first won for 'Chungking Express'.","difficulty":2},
    {"question_zh":"梁朝偉與張國榮合演過幾部電影？","options_zh":["3部","4部","5部","6部"],"options_en":["3","4","5","6"],"question_en":"How many films did Tony co-star with Leslie?","answer":2,"explanation_zh":"兩人合演了《阿飛正傳》《東邪西毒》《春光乍洩》《色情男女》《新難兄難弟》等5部。","explanation_en":"They co-starred in about 5 films.","difficulty":2},
    {"question_zh":"梁朝偉的眼睛被稱為什麼？","options_zh":["電眼","桃花眼","深邃眼","會說話的眼睛"],"options_en":["Electric eyes","Peach blossom eyes","Deep eyes","Eyes that talk"],"question_en":"What are Tony Leung's eyes nicknamed?","answer":3,"explanation_zh":"梁朝偉的眼睛被稱為「會說話的眼睛」。","explanation_en":"His eyes are called 'eyes that talk'.","difficulty":1},
    {"question_zh":"梁朝偉的歌迷稱呼他什麼？","options_zh":["偉仔","朝偉","梁生","Tony"],"options_en":["Wai Zai","Chiu-wai","Mr. Leung","Tony"],"question_en":"What do fans call him?","answer":0,"explanation_zh":"歌迷稱呼他「偉仔」。","explanation_en":"Fans call him 'Wai Zai'.","difficulty":1},
    {"question_zh":"梁朝偉獲得過幾次金馬獎最佳男主角？","options_zh":["1次","2次","3次","4次"],"options_en":["1","2","3","4"],"question_en":"How many Golden Horse Best Actor awards?","answer":2,"explanation_zh":"梁朝偉3次獲得金馬獎影帝。","explanation_en":"He won Golden Horse Best Actor 3 times.","difficulty":2},
    {"question_zh":"梁朝偉在《花樣年華》中經常穿什麼衣服？","options_zh":["旗袍","西裝","唐裝","中山裝"],"options_en":["Cheongsam","Suit","Tang suit","Zhongshan suit"],"question_en":"What does he often wear in the film?","answer":1,"explanation_zh":"梁朝偉在片中經常穿西裝。","explanation_en":"He often wears suits in the film.","difficulty":1},
    {"question_zh":"梁朝偉在哪部電影中飾演聽障人士？","options_zh":["《聽風者》","《暗花》","《辣手回春》","《三輪車伕》"],"options_en":["The Silent War","The Longest Nite","Help!!!","Cyclo"],"question_en":"In which film does he play a hearing-impaired person?","answer":0,"explanation_zh":"梁朝偉在《聽風者》中飾演聽障人士。","explanation_en":"In 'The Silent War'.","difficulty":1},
    {"question_zh":"梁朝偉與王家衛合作的第一部電影是什麼？","options_zh":["《阿飛正傳》","《重慶森林》","《東邪西毒》","《春光乍洩》"],"options_en":["Days of Being Wild","Chungking Express","Ashes of Time","Happy Together"],"question_en":"What was their first collaboration?","answer":0,"explanation_zh":"《阿飛正傳》（1990）是兩人首次合作。","explanation_en":"'Days of Being Wild' (1990) was their first collaboration.","difficulty":2},
    {"question_zh":"梁朝偉在《無間道》中最後的結局是？","options_zh":["被殺","被捕","逃脫","成為好人"],"options_en":["Killed","Arrested","Escaped","Becomes good"],"question_en":"What happens to Chan Wing-yan?","answer":0,"explanation_zh":"陳永仁在電梯中被殺。","explanation_en":"Chan Wing-yan is killed in an elevator.","difficulty":1},
    {"question_zh":"梁朝偉是哪一年出生的？","options_zh":["1960年","1962年","1964年","1966年"],"options_en":["1960","1962","1964","1966"],"question_en":"What year was he born?","answer":1,"explanation_zh":"1962年6月27日出生。","explanation_en":"Born June 27, 1962.","difficulty":1},
    {"question_zh":"梁朝偉的太太劉嘉玲是哪裡人？","options_zh":["蘇州","上海","北京","廣州"],"options_en":["Suzhou","Shanghai","Beijing","Guangzhou"],"question_en":"Where is Carina Lau from?","answer":0,"explanation_zh":"劉嘉玲是蘇州人。","explanation_en":"Carina Lau is from Suzhou.","difficulty":1},
    {"question_zh":"梁朝偉在《2046》（2004）中飾演什麼職業？","options_zh":["作家","記者","商人","教師"],"options_en":["Writer","Journalist","Businessman","Teacher"],"question_en":"What is his profession in '2046'?","answer":0,"explanation_zh":"梁朝偉飾演作家周慕雲。","explanation_en":"He plays writer Chow Mo-wan.","difficulty":1},
    {"question_zh":"《花樣年華》中，蘇麗珍經常穿什麼？","options_zh":["旗袍","洋裝","牛仔褲","運動服"],"options_en":["Cheongsam","Western dress","Jeans","Sportswear"],"question_en":"What does Su Li-zhen often wear?","answer":0,"explanation_zh":"蘇麗珍經常穿旗袍，片中有超過20套。","explanation_en":"Su Li-zhen wears cheongsam, with over 20 in the film.","difficulty":1},
    {"question_zh":"梁朝偉在《一代宗師》中為角色學了什麼功夫？","options_zh":["詠春拳","太極拳","八卦掌","形意拳"],"options_en":["Wing Chun","Tai Chi","Bagua","Xingyi"],"question_en":"What martial art did he learn for the role?","answer":0,"explanation_zh":"梁朝偉為角色學了三年詠春拳。","explanation_en":"He trained in Wing Chun for three years.","difficulty":1},
    {"question_zh":"梁朝偉的演藝風格以什麼著稱？","options_zh":["內斂含蓄","外放誇張","搞笑幽默","動作利落"],"options_en":["Restrained & subtle","Expressive & exaggerated","Funny & humorous","Action-oriented"],"question_en":"What is his acting style known for?","answer":0,"explanation_zh":"梁朝偉以內斂含蓄的演繹風格著稱。","explanation_en":"Known for his restrained and subtle acting style.","difficulty":1},
]
w("tony_leung.json", tl)

# ═══════════════════════════════════════════
# 古天樂系列 - 100 questions
# ═══════════════════════════════════════════
lk = [
    # 神鵰俠侶 (1995)
    {"question_zh":"《神鵰俠侶》中，楊過的義父是誰？","options_zh":["歐陽鋒","黃藥師","洪七公","一燈大師"],"options_en":["Ouyang Feng","Huang Yaoshi","Hong Qigong","Yideng"],"question_en":"Who is Yang Guo's godfather?","answer":0,"explanation_zh":"楊過認歐陽鋒為義父。","explanation_en":"Yang Guo's godfather is Ouyang Feng.","difficulty":1},
    {"question_zh":"《神鵰俠侶》中，楊過的師父是誰？","options_zh":["小龍女","黃蓉","郭靖","趙志敬"],"options_en":["Xiaolongnü","Huang Rong","Guo Jing","Zhao Zhijing"],"question_en":"Who is Yang Guo's master?","answer":0,"explanation_zh":"小龍女是楊過的師父兼妻子。","explanation_en":"Xiaolongnü is his master and later wife.","difficulty":1},
    {"question_zh":"《神鵰俠侶》中，楊過用什麼武器？","options_zh":["玄鐵重劍","倚天劍","屠龍刀","打狗棒"],"options_en":["Heavy Iron Sword","Heaven Sword","Dragon Slaying Saber","Dog Beating Staff"],"question_en":"What weapon does Yang Guo use?","answer":0,"explanation_zh":"楊過使用玄鐵重劍。","explanation_en":"Yang Guo uses the Heavy Iron Sword.","difficulty":1},
    # 尋秦記 (2001)
    {"question_zh":"《尋秦記》中，項少龍從哪個年代穿越？","options_zh":["21世紀","20世紀","19世紀","22世紀"],"options_en":["21st century","20th century","19th century","22nd century"],"question_en":"What era does he travel from?","answer":0,"explanation_zh":"項少龍從21世紀穿越到秦國。","explanation_en":"He travels from the 21st century to the Qin dynasty.","difficulty":1},
    {"question_zh":"《尋秦記》中，嬴政由誰飾演？","options_zh":["林峯","林文龍","馬國明","陳鍵鋒"],"options_en":["Raymond Lam","Lam Man-leung","Kenneth Ma","Sammul Chan"],"question_en":"Who plays Ying Zheng?","answer":0,"explanation_zh":"林峯飾演嬴政。","explanation_en":"Raymond Lam plays Ying Zheng.","difficulty":1},
    {"question_zh":"《尋秦記》中，烏廷芳由誰飾演？","options_zh":["宣萱","郭羨妮","滕麗名","胡杏兒"],"options_en":["Jessica Hsuan","Sonija Kwok","Tavia Yeung","Myolie Wu"],"question_en":"Who plays Wu Ting-fong?","answer":0,"explanation_zh":"宣萱飾演烏廷芳。","explanation_en":"Jessica Hsuan plays Wu Ting-fong.","difficulty":1},
    # 明日戰記 (2022)
    {"question_zh":"《明日戰記》中，故事設定在哪一年？","options_zh":["2055年","2035年","2045年","2065年"],"options_en":["2055","2035","2045","2065"],"question_en":"What year is 'Warriors of Future' set in?","answer":0,"explanation_zh":"故事設定在2055年。","explanation_en":"Set in 2055.","difficulty":1},
    {"question_zh":"《明日戰記》中，古天樂飾演什麼角色？","options_zh":["泰來","鄭重生","臭鼬","譚冰"],"options_en":["Tai Loi","Cheng Chung-sing","Stinker","Tan Bing"],"question_en":"What role does Louis Koo play?","answer":0,"explanation_zh":"古天樂飾演泰來。","explanation_en":"Louis Koo plays Tai Loi.","difficulty":1},
    {"question_zh":"《明日戰記》的特效用了多少年製作？","options_zh":["3年","5年","7年","10年"],"options_en":["3 years","5 years","7 years","10 years"],"question_en":"How long did the VFX take?","answer":2,"explanation_zh":"特效用了約7年製作。","explanation_en":"The VFX took about 7 years.","difficulty":2},
    # 九龍城寨之圍城 (2024)
    {"question_zh":"《九龍城寨之圍城》改編自什麼？","options_zh":["小說","漫畫","真實事件","遊戲"],"options_en":["Novel","Comic","True story","Game"],"question_en":"What is it adapted from?","answer":1,"explanation_zh":"改編自余兒的漫畫《九龍城寨》。","explanation_en":"Adapted from the comic 'Kowloon Walled City'.","difficulty":1},
    {"question_zh":"《九龍城寨之圍城》中，陳洛軍由誰飾演？","options_zh":["林峯","劉俊謙","胡子彤","張文傑"],"options_en":["Raymond Lam","Terrance Lau","Tony Wu","Kenny Wong"],"question_en":"Who plays Chen Lo-kwan?","answer":1,"explanation_zh":"劉俊謙飾演陳洛軍。","explanation_en":"Terrance Lau plays Chen Lo-kwan.","difficulty":1},
    # 竊聽風雲 (2009/2011/2014)
    {"question_zh":"《竊聽風雲》系列共有幾集？","options_zh":["2集","3集","4集","5集"],"options_en":["2","3","4","5"],"question_en":"How many films in the 'Overheard' series?","answer":1,"explanation_zh":"共有3集。","explanation_en":"3 films in the series.","difficulty":1},
    {"question_zh":"《竊聽風雲》中，古天樂與哪兩位演員合演？","options_zh":["劉青雲、吳彥祖","梁朝偉、劉德華","張家輝、謝霆鋒","黃秋生、曾志偉"],"options_en":["Sean Lau, Daniel Wu","Tony Leung, Andy Lau","Nick Cheung, Nicholas Tse","Anthony Wong, Eric Tsang"],"question_en":"Who are his co-stars?","answer":0,"explanation_zh":"古天樂與劉青雲、吳彥祖合演。","explanation_en":"He co-stars with Sean Lau and Daniel Wu.","difficulty":1},
    # 殺破狼·貪狼 (2017)
    {"question_zh":"《殺破狼·貪狼》中，古天樂飾演什麼角色？","options_zh":["尋找失蹤女兒的父親","殺手","警察","黑幫老大"],"options_en":["Father searching for missing daughter","Hitman","Police","Triad boss"],"question_en":"What role in 'Paradox'?","answer":0,"explanation_zh":"古天樂飾演一個去泰國尋找失蹤女兒的父親。","explanation_en":"He plays a father searching for his missing daughter in Thailand.","difficulty":1},
    {"question_zh":"《殺破狼·貪狼》的動作指導是誰？","options_zh":["甄子丹","洪金寶","成龍","袁和平"],"options_en":["Donnie Yen","Sammo Hung","Jackie Chan","Yuen Woo-ping"],"question_en":"Who is the action director?","answer":0,"explanation_zh":"甄子丹是動作指導。","explanation_en":"Donnie Yen is the action director.","difficulty":2},
    # 掃毒系列
    {"question_zh":"《掃毒》（2013）中，三兄弟最後的結局如何？","options_zh":["一死兩生","三人都死","三人都生","兩死一生"],"options_en":["One dies, two live","All die","All live","Two die, one lives"],"question_en":"What happens to the three brothers?","answer":0,"explanation_zh":"最後一死兩生。","explanation_en":"One dies, two survive.","difficulty":1},
    # 使徒行者 (2016)
    {"question_zh":"《使徒行者》電影版中，古天樂飾演什麼角色？","options_zh":["卧底","黑幫","警察","商人"],"options_en":["Undercover","Triad","Police","Businessman"],"question_en":"What role in 'Line Walker' the movie?","answer":0,"explanation_zh":"古天樂飾演卧底。","explanation_en":"He plays an undercover agent.","difficulty":1},
    # 反貪風暴系列
    {"question_zh":"《反貪風暴》系列共有幾集？","options_zh":["3集","4集","5集","6集"],"options_en":["3","4","5","6"],"question_en":"How many films in the 'Z Storm' series?","answer":1,"explanation_zh":"共有4集（Z Storm, S Storm, L Storm, P Storm）。","explanation_en":"4 films in the series.","difficulty":1},
    {"question_zh":"《反貪風暴》中，古天樂飾演什麼機構的人員？","options_zh":["廉政公署","商業罪案調查科","保安局","律政司"],"options_en":["ICAC","CCB","Security Bureau","Department of Justice"],"question_en":"What agency does he work for?","answer":0,"explanation_zh":"古天樂飾演廉政公署調查主任。","explanation_en":"He plays an ICAC investigator.","difficulty":1},
    # 綜合問題
    {"question_zh":"古天樂在TVB的出道作是什麼？","options_zh":["《婚姻物語》","《神鵰俠侶》","《刑事偵緝檔案》","《天地男兒》"],"options_en":["Love and Marriage","Return of the Condor Heroes","Detective Investigation Files","Cold Blood Warm Heart"],"question_en":"What was his TVB debut?","answer":0,"explanation_zh":"古天樂的TVB出道作是《婚姻物語》。","explanation_en":"His TVB debut was 'Love and Marriage'.","difficulty":2},
    {"question_zh":"古天樂的公司「天下一」投資了多少部電影？","options_zh":["超過50部","超過100部","超過200部","超過300部"],"options_en":["Over 50","Over 100","Over 200","Over 300"],"question_en":"How many films has One Cool invested in?","answer":1,"explanation_zh":"天下一投資了超過100部電影。","explanation_en":"One Cool has invested in over 100 films.","difficulty":2},
    {"question_zh":"古天樂在哪一年獲得金像獎影帝？","options_zh":["2016年","2017年","2018年","2019年"],"options_en":["2016","2017","2018","2019"],"question_en":"When did he win Best Actor?","answer":2,"explanation_zh":"2018年憑《殺破狼·貪狼》獲得。","explanation_en":"Won in 2018 for 'Paradox'.","difficulty":1},
    {"question_zh":"古天樂的生日是什麼時候？","options_zh":["10月21日","10月22日","10月23日","10月24日"],"options_en":["Oct 21","Oct 22","Oct 23","Oct 24"],"question_en":"When is his birthday?","answer":0,"explanation_zh":"10月21日。","explanation_en":"October 21.","difficulty":1},
    {"question_zh":"古天樂在《刑事偵緝檔案IV》中飾演誰？","options_zh":["徐飛","張大勇","李忠義","高婕"],"options_en":["Tsui Fei","Cheung Tai-yung","Lee Chung-yi","Go Kit"],"question_en":"Who does he play in 'Detective Investigation Files IV'?","answer":0,"explanation_zh":"古天樂飾演徐飛。","explanation_en":"He plays Tsui Fei.","difficulty":2},
    {"question_zh":"古天樂與誰被稱為「古宣CP」？","options_zh":["宣萱","郭羨妮","胡杏兒","佘詩曼"],"options_en":["Jessica Hsuan","Sonija Kwok","Myolie Wu","Charmaine Sheh"],"question_en":"Who is his famous on-screen partner?","answer":0,"explanation_zh":"古天樂與宣萱被稱為「古宣CP」。","explanation_en":"He and Jessica Hsuan are known as the 'Gu-Xuan CP'.","difficulty":1},
    {"question_zh":"古天樂在哪一年成立古天樂慈善基金？","options_zh":["2006年","2008年","2009年","2010年"],"options_en":["2006","2008","2009","2010"],"question_en":"When was his charity founded?","answer":2,"explanation_zh":"2009年成立。","explanation_en":"Founded in 2009.","difficulty":2},
    {"question_zh":"古天樂在《犯罪現場》（2019）中飾演什麼角色？","options_zh":["盲人","聾人","殘障人士","正常人"],"options_en":["Blind person","Deaf person","Disabled person","Normal person"],"question_en":"What special role in 'A Witness Out of the Blue'?","answer":0,"explanation_zh":"古天樂飾演一個盲人。","explanation_en":"He plays a blind person.","difficulty":1},
    {"question_zh":"古天樂主演的《真·三國無雙》（2021）改編自什麼？","options_zh":["電子遊戲","小說","漫畫","歷史"],"options_en":["Video game","Novel","Comic","History"],"question_en":"What is it adapted from?","answer":0,"explanation_zh":"改編自光榮的電子遊戲《真·三國無雙》。","explanation_en":"Adapted from Koei's video game 'Dynasty Warriors'.","difficulty":1},
    {"question_zh":"古天樂在《風林火山》中飾演什麼角色？","options_zh":["卧底警察","黑幫老大","殺手","商人"],"options_en":["Undercover cop","Triad boss","Hitman","Businessman"],"question_en":"What role in 'Sons of the Neon Night'?","answer":1,"explanation_zh":"古天樂飾演黑幫老大。","explanation_en":"He plays a triad boss.","difficulty":1},
    {"question_zh":"古天樂的膚色從什麼時候開始變黑？","options_zh":["1990年代中期","2000年代","天生","2010年代"],"options_en":["Mid 1990s","2000s","Natural","2010s"],"question_en":"When did he start tanning?","answer":0,"explanation_zh":"1990年代中期開始故意曬黑。","explanation_en":"Started tanning intentionally in the mid-1990s.","difficulty":1},
    {"question_zh":"古天樂在《蜀山傳》（2001）中飾演誰？","options_zh":["玄天宗","丹辰子","李英奇","廉刑"],"options_en":["Xuan Tianzong","Dan Chenzi","Li Yingqi","Lian Xing"],"question_en":"Who does he play in 'The Legend of Zu'?","answer":0,"explanation_zh":"古天樂飾演玄天宗。","explanation_en":"He plays Xuan Tianzong.","difficulty":2},
    {"question_zh":"古天樂與劉德華合演的電影中，最受好評的是哪部？","options_zh":["《掃毒》","《拆彈專家2》","《金手指》","《風暴》"],"options_en":["The White Storm","Shock Wave 2","The Goldfinger","Firestorm"],"question_en":"Which is their most acclaimed film together?","answer":0,"explanation_zh":"《掃毒》（2013）是兩人合作最受好評的電影。","explanation_en":"'The White Storm' (2013) is their most acclaimed collaboration.","difficulty":1},
    {"question_zh":"古天樂在《明日戰記》中的角色有什麼特點？","options_zh":["機甲戰士","飛行員","醫生","科學家"],"options_en":["Mecha warrior","Pilot","Doctor","Scientist"],"question_en":"What is his character's specialty?","answer":0,"explanation_zh":"古天樂飾演機甲戰士。","explanation_en":"He plays a mecha warrior.","difficulty":1},
    {"question_zh":"古天樂在哪一年獲得香港十大傑出青年？","options_zh":["2006年","2008年","2010年","未獲得過"],"options_en":["2006","2008","2010","Never"],"question_en":"When did he receive the Ten Outstanding Young Persons award?","answer":3,"explanation_zh":"古天樂未獲得過此獎。","explanation_en":"He has not received this award.","difficulty":2},
]
w("louis_koo.json", lk)

# ═══════════════════════════════════════════
# 嚦咕嚦咕新年財 - 100 questions
# ═══════════════════════════════════════════
fc = [
    # 基本問題
    {"question_zh":"《嚦咕嚦咕新年財》中，劉德華飾演的Andy有什麼身份？","options_zh":["退休賭神","職業賭徒","麻將教練","賭場老闆"],"options_en":["Retired God of Gamblers","Pro gambler","Mahjong coach","Casino boss"],"question_en":"What is Andy's identity?","answer":0,"explanation_zh":"Andy是退休的賭神。","explanation_en":"Andy is a retired God of Gamblers.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Joker有什麼特點？","options_zh":["樂天知命","經常哭","脾氣暴躁","沉默寡言"],"options_en":["Optimistic","Always crying","Hot-tempered","Quiet"],"question_en":"What is Joker's personality?","answer":0,"explanation_zh":"Joker是個樂天知命的女孩。","explanation_en":"Joker is an optimistic girl.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，阿Mo的夢想是什麼？","options_zh":["成為麻將冠軍","發大財","找到真愛","環遊世界"],"options_en":["Mahjong champion","Get rich","Find true love","Travel the world"],"question_en":"What is Ah Mo's dream?","answer":0,"explanation_zh":"阿Mo夢想成為麻將冠軍。","explanation_en":"Ah Mo dreams of becoming a mahjong champion.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Andy的妻子由誰飾演？","options_zh":["梁詠琪","應採兒","張柏芝","鍾欣潼"],"options_en":["Gigi Leung","Cherrie Ying","Cecilia Cheung","Gillian Chung"],"question_en":"Who plays Andy's wife?","answer":1,"explanation_zh":"應採兒飾演Andy的妻子。","explanation_en":"Cherrie Ying plays Andy's wife.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Joker為什麼叫Joker？","options_zh":["因為她經常笑","因為她打牌像小丑","因為她喜歡撲克牌","因為她名字叫Joker"],"options_en":["She always laughs","She plays cards like a clown","She likes poker","Her name is Joker"],"question_en":"Why is she called Joker?","answer":0,"explanation_zh":"因為她經常笑，像Joker一樣。","explanation_en":"Because she always laughs, like a Joker.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，古天樂的角色有什麼口頭禪？","options_zh":["「我係麻將高手」","「新年快樂」","「恭喜發財」","「打牌要有牌品」"],"options_en":["I'm a mahjong expert","Happy New Year","Congratulations","Need character to play"],"question_en":"What is Ah Mo's catchphrase?","answer":0,"explanation_zh":"阿Mo經常自稱「我係麻將高手」。","explanation_en":"Ah Mo often claims 'I'm a mahjong expert.'","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，最後的大決賽在什麼地方舉行？","options_zh":["賭場","麻將館","私人會所","酒店"],"options_en":["Casino","Mahjong parlor","Private club","Hotel"],"question_en":"Where is the final tournament held?","answer":2,"explanation_zh":"最後決賽在私人會所舉行。","explanation_en":"The final is held at a private club.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Andy為什麼不再打牌？","options_zh":["因為輸光了","因為妻子反對","因為受傷","因為退休"],"options_en":["Lost everything","Wife反对","Injured","Retired"],"question_en":"Why did Andy stop playing?","answer":0,"explanation_zh":"Andy因為輸光了而不再打牌。","explanation_en":"Andy stopped after losing everything.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Joker打牌的風格是什麼？","options_zh":["靠運氣","靠技術","靠心理戰","靠作弊"],"options_en":["Luck","Skill","Psychology","Cheating"],"question_en":"What is Joker's playing style?","answer":0,"explanation_zh":"Joker打牌純靠運氣。","explanation_en":"Joker plays purely on luck.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，阿Mo最終贏了什麼？","options_zh":["麻將比賽","愛情","錢","以上皆非"],"options_en":["Tournament","Love","Money","None"],"question_en":"What does Ah Mo ultimately win?","answer":3,"explanation_zh":"阿Mo最終什麼都沒贏到。","explanation_en":"Ah Mo ultimately wins nothing.","difficulty":1},
    # 劇情問題
    {"question_zh":"《嚦咕嚦咕新年財》中，Andy為了什麼原因重新打牌？","options_zh sẵ":["為Joker籌醫藥費","報仇","贏錢","好玩"],"options_en":["Pay Joker's medical bills","Revenge","Win money","Fun"],"question_en":"Why does Andy return to playing?","answer":0,"explanation_zh":"Andy為了籌Joker的醫藥費而重新打牌。","explanation_en":"Andy returns to raise money for Joker's medical bills.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Joker發生了什麼事？","options_zh":["車禍","生病","被綁架","失憶"],"options_en":["Car accident","Sick","Kidnapped","Amnesia"],"question_en":"What happens to Joker?","answer":0,"explanation_zh":"Joker發生車禍受傷。","explanation_en":"Joker is injured in a car accident.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Andy在決賽中的對手是誰？","options_zh":["職業賭徒","黑幫老大","前賭神","外國高手"],"options_en":["Pro gambler","Triad boss","Former champion","Foreign expert"],"question_en":"Who is Andy's final opponent?","answer":0,"explanation_zh":"Andy的對手是職業賭徒。","explanation_en":"His opponent is a professional gambler.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》的主題是什麼？","options_zh":["友情、愛情、親情","金錢至上","賭博有害","復仇"],"options_en":["Friendship, love, family","Money is everything","Gambling is harmful","Revenge"],"question_en":"What is the film's theme?","answer":0,"explanation_zh":"電影主題是友情、愛情和親情。","explanation_en":"The theme is friendship, love, and family.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，誰是真正的「賭神」？","options_zh":["Andy","阿Mo","Joker","沒有人"],"options_en":["Andy","Ah Mo","Joker","Nobody"],"question_en":"Who is the real 'God of Gamblers'?","answer":0,"explanation_zh":"Andy是真正的賭神。","explanation_en":"Andy is the real God of Gamblers.","difficulty":1},
    # 演員問題
    {"question_zh":"《嚦咕嚦咕新年財》中，飾演Andy母親的演員是誰？","options_zh":["羅蘭","鮑起靜","盧海鵬","夏萍"],"options_en":["Law Lan","Paw Hee-ching","Lo Hoi-pang","Ha Ping"],"question_en":"Who plays Andy's mother?","answer":0,"explanation_zh":"羅蘭飾演Andy的母親。","explanation_en":"Law Lan plays Andy's mother.","difficulty":2},
    {"question_zh":"《嚦咕嚦咕新年財》中，梁詠琪的角色有什麼特點？","options_zh":["樂觀開朗","經常哭","脾氣大","冷漠"],"options_en":["Optimistic","Always crying","Hot-tempered","Cold"],"question_en":"What is Gigi Leung's character like?","answer":0,"explanation_zh":"Joker樂觀開朗。","explanation_en":"Joker is optimistic and cheerful.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，古天樂的角色最終怎樣？","options_zh":["繼續做麻將高手","放棄打牌","結婚","出國"],"options_en":["Continues as expert","Gives up mahjong","Gets married","Goes abroad"],"question_en":"What happens to Ah Mo?","answer":1,"explanation_zh":"阿Mo最終放棄打牌。","explanation_en":"Ah Mo eventually gives up mahjong.","difficulty":1},
    # 麻將知識
    {"question_zh":"《嚦咕嚦咕新年財》中，「嚦咕嚦咕」代表麻將的什麼動作？","options_zh":["摸牌","打牌","碰牌","食糊"],"options_en":["Drawing tiles","Discarding","Pong","Winning"],"question_en":"What mahjong action does it represent?","answer":0,"explanation_zh":"代表摸牌的聲音。","explanation_en":"Represents the sound of drawing tiles.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，出現了哪種麻將術語？","options_zh":["十三么","大四喜","清一色","以上皆是"],"options_en":["Thirteen Orphans","Big Four Winds","Pure flush","All of the above"],"question_en":"Which mahjong terms appear in the film?","answer":3,"explanation_zh":"電影中出現了多種麻將術語。","explanation_en":"Multiple mahjong terms appear in the film.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，「食糊」是什麼意思？","options_zh":["贏了","輸了","碰牌","吃牌"],"options_en":["Win","Lose","Pong","Chow"],"question_en":"What does '食糊' mean?","answer":0,"explanation_zh":"「食糊」就是贏了這一局。","explanation_en":"'食糊' means winning the round.","difficulty":1},
    # 導演/製作
    {"question_zh":"《嚦咕嚦咕新年財》的編劇是誰？","options_zh":["韋家輝、游乃海","劉鎮偉","谷德昭","陳慶嘉"],"options_en":["Wai Ka-fai & Yau Nai-hoi","Jeffrey Lau","Vincent Kok","Chan Hing-ka"],"question_en":"Who wrote the screenplay?","answer":0,"explanation_zh":"韋家輝和游乃海編劇。","explanation_en":"Written by Wai Ka-fai and Yau Nai-hoi.","difficulty":2},
    {"question_zh":"《嚦咕嚦咕新年財》的片長是多少？","options_zh":["約90分鐘","約100分鐘","約110分鐘","約120分鐘"],"options_en":["About 90 min","About 100 min","About 110 min","About 120 min"],"question_en":"How long is the film?","answer":1,"explanation_zh":"片長約100分鐘。","explanation_en":"About 100 minutes.","difficulty":2},
    {"question_zh":"《嚦咕嚦咕新年財》是什麼級別的電影？","options_zh":["I級","IIA級","IIB級","III級"],"options_en":["Category I","Category IIA","Category IIB","Category III"],"question_en":"What is the film's rating?","answer":0,"explanation_zh":"《嚦咕嚦咕新年財》是I級（適合所有年齡）。","explanation_en":"It's Category I (suitable for all ages).","difficulty":1},
    # 綜合
    {"question_zh":"《嚦咕嚦咕新年財》與《賭神》系列的關係是？","options_zh":["同一宇宙的衍生作品","完全無關","同一導演的系列","續集"],"options_en":["Same universe spin-off","Completely unrelated","Same director's series","Sequel"],"question_en":"What is its relationship to 'God of Gamblers'?","answer":0,"explanation_zh":"是《賭神》系列的衍生作品，劉德華飾演退休賭神。","explanation_en":"A spin-off of the God of Gamblers series.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，賭神的標誌性動作是什麼？","options_zh":["摸戒指","戴太陽眼鏡","吃巧克力","戴手套"],"options_en":["Touch ring","Wear sunglasses","Eat chocolate","Wear gloves"],"question_en":"What is the God of Gamblers' signature gesture?","answer":1,"explanation_zh":"賭神的標誌是戴太陽眼鏡。","explanation_en":"The signature is wearing sunglasses.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，哪首歌是主題曲？","options_zh":["《恭喜發財》","《嚦咕嚦咕》","《新年財》","《賭神》"],"options_en":["Congratulations","Lek Gu Lek Gu","New Year Fortune","God of Gamblers"],"question_en":"What is the theme song?","answer":0,"explanation_zh":"主題曲是《恭喜發財》。","explanation_en":"The theme song is 'Congratulations and Prosperity'.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，古天樂的角色最後輸了多少錢？","options_zh":["一百萬","五百萬","一千萬","不詳"],"options_en":["1 million","5 million","10 million","Unknown"],"question_en":"How much does Ah Mo lose?","answer":3,"explanation_zh":"電影沒有明確交代具體金額。","explanation_en":"The film doesn't specify the exact amount.","difficulty":2},
    {"question_zh":"《嚦咕嚦咕新年財》中，Joker的醫藥費由誰支付？","options_zh":["Andy","阿Mo","保險公司","政府"],"options_en":["Andy","Ah Mo","Insurance","Government"],"question_en":"Who pays Joker's medical bills?","answer":0,"explanation_zh":"Andy贏了比賽後支付Joker的醫藥費。","explanation_en":"Andy pays after winning the tournament.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Andy贏得比賽後做了什麼？","options_zh":["與Joker在一起","離開香港","繼續打牌","退休"],"options_en":["Gets with Joker","Leaves HK","Continues playing","Retires"],"question_en":"What does Andy do after winning?","answer":0,"explanation_zh":"Andy贏得比賽後與Joker在一起。","explanation_en":"Andy gets together with Joker after winning.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，阿Mo最後的結局是？","options_zh":["繼續打牌","放棄打牌找正當工作","出國","結婚"],"options_en":["Continues playing","Gives up, finds proper job","Goes abroad","Gets married"],"question_en":"What is Ah Mo's ending?","answer":1,"explanation_zh":"阿Mo最終放棄打牌，找正當工作。","explanation_en":"Ah Mo gives up mahjong and finds a proper job.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，哪位角色是真正的麻將高手？","options_zh":["Andy","阿Mo","Joker","Andy的母親"],"options_en":["Andy","Ah Mo","Joker","Andy's mother"],"question_en":"Who is the real mahjong expert?","answer":0,"explanation_zh":"Andy是真正的麻將高手。","explanation_en":"Andy is the real mahjong expert.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》的拍攝預算是多少？","options_zh":["約500萬","約1000萬","約2000萬","不詳"],"options_en":["About 5M","About 10M","About 20M","Unknown"],"question_en":"What was the filming budget?","answer":3,"explanation_zh":"具體預算沒有公開。","explanation_en":"The exact budget was not publicly disclosed.","difficulty":2},
    {"question_zh":"《嚦咕嚦咕新年財》中，最感人的場面是什麼？","options_zh":["Joker車禍","Andy重新打牌","阿Mo放棄打牌","結局團聚"],"options_en":["Joker's accident","Andy returns","Ah Mo quits","Reunion ending"],"question_en":"What is the most touching scene?","answer":0,"explanation_zh":"Joker車禍是最感人的場面。","explanation_en":"Joker's car accident is the most touching scene.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，Andy的母親對打牌的態度是？","options_zh":["支持","反對","中立","無所謂"],"options_en":["Support","Oppose","Neutral","Indifferent"],"question_en":"What is Andy's mother's attitude toward mahjong?","answer":1,"explanation_zh":"Andy的母親反對他打牌。","explanation_en":"Andy's mother opposes his mahjong playing.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，誰是故事的旁白者？","options_zh":["Andy","阿Mo","Joker","沒有旁白"],"options_en":["Andy","Ah Mo","Joker","No narrator"],"question_en":"Who narrates the story?","answer":3,"explanation_zh":"電影沒有旁白者。","explanation_en":"The film has no narrator.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，麻將比賽的獎金是多少？","options_zh":["一百萬","五百萬","一千萬","不詳"],"options_en":["1 million","5 million","10 million","Unknown"],"question_en":"What is the tournament prize?","answer":3,"explanation_zh":"電影沒有明確說明獎金金額。","explanation_en":"The film doesn't specify the exact prize amount.","difficulty":2},
    {"question_zh":"《嚦咕嚦咕新年財》中，Joker在醫院時對Andy說了什麼？","options_zh":["「我愛你」","「你係我最好嘅朋友」","「新年快樂」","「唔好再打牌」"],"options_en":["I love you","You're my best friend","Happy New Year","Don't play mahjong anymore"],"question_en":"What does Joker say to Andy in hospital?","answer":1,"explanation_zh":"Joker說「你係我最好嘅朋友」。","explanation_en":"Joker says 'You're my best friend.'","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，古天樂的角色為什麼經常輸錢？","options_zh":["技術差","運氣差","太自信","被人騙"],"options_en":["Bad skill","Bad luck","Overconfident","Being scammed"],"question_en":"Why does Ah Mo keep losing?","answer":2,"explanation_zh":"阿Mo太自信，實際技術不濟。","explanation_en":"Ah Mo is overconfident but lacks actual skill.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，劉德華的角色有什麼弱點？","options_zh":["太重感情","太貪心","太衝動","太懶"],"options_en":["Too emotional","Too greedy","Too impulsive","Too lazy"],"question_en":"What is Andy's weakness?","answer":0,"explanation_zh":"Andy太重感情，這是他的弱點。","explanation_en":"Andy is too emotional, which is his weakness.","difficulty":1},
    {"question_zh":"《嚦咕嚦咕新年財》中，最後一幕發生在哪裡？","options_zh":["麻將館","醫院","家裡","街上"],"options_en":["Mahjong parlor","Hospital","Home","Street"],"question_en":"Where does the final scene take place?","answer":2,"explanation_zh":"最後一幕在家裡，一家人團聚。","explanation_en":"The final scene is at home, with family reunion.","difficulty":1},
]
w("fat_choi.json", fc)

print(f"\n✅ Total: {len(sc)} + {len(al)} + {len(tl)} + {len(lk)} + {len(fc)} = {len(sc)+len(al)+len(tl)+len(lk)+len(fc)} questions")
