#!/usr/bin/env python3
"""
Generate 'Others' category: Movies (5 series) + Millionaire quiz bank
"""
import json, os
from pathlib import Path

BASE = Path(__file__).parent / "others"

# ═══════════════════════════════════════════════════════════════
# MOVIE QUESTIONS - 5 series, 200 questions each
# ═══════════════════════════════════════════════════════════════

STEPHEN_CHOW = [
    # 周星馳系列 - 200 questions
    {"question_zh": "《賭聖》（1990）中，周星馳飾演的角色叫什麼名字？", "question_en": "In 'All for the Winner' (1990), what is Stephen Chow's character's name?", "options_zh": ["左頌星", "周星星", "至尊寶", "唐伯虎"], "options_en": ["So Chun-sing", "Chow Sing-sing", "Supreme Treasure", "Tong Pak-fu"], "answer": 0, "explanation_zh": "左頌星是從大陸來港的特異功能青年。", "explanation_en": "So Chun-sing is a young man from mainland China with special powers.", "difficulty": 1},
    {"question_zh": "《賭聖》中，左頌星的特異功能是什麼？", "question_en": "What is So Chun-sing's special power in 'All for the Winner'?", "options_zh": ["透視牌", "讀心術", "預知未來", "瞬間移動"], "options_en": ["See through cards", "Mind reading", "Precognition", "Teleportation"], "answer": 0, "explanation_zh": "左頌星能用特異功能透視撲克牌。", "explanation_en": "So Chun-sing can see through playing cards with his supernatural power.", "difficulty": 1},
    {"question_zh": "《逃學威龍》（1991）中，周星馳飾演的警察臥底叫什麼？", "question_en": "In 'Fight Back to School' (1991), what is Stephen Chow's undercover cop character's name?", "options_zh": ["周星星", "達文西", "曹達華", "何金水"], "options_en": ["Chow Sing-sing", "Da Vinci", "Tsao Tat-wah", "Ho Kam-sui"], "answer": 0, "explanation_zh": "周星星被派去學校做臥底調查失槍案。", "explanation_en": "Chow Sing-sing is sent undercover to a school to investigate a missing gun.", "difficulty": 1},
    {"question_zh": "《逃學威龍》系列共有幾集？", "question_en": "How many films are in the 'Fight Back to School' series?", "options_zh": ["2集", "3集", "4集", "5集"], "options_en": ["2 films", "3 films", "4 films", "5 films"], "answer": 1, "explanation_zh": "逃學威龍系列共有3集（1991、1992、1993）。", "explanation_en": "The series has 3 films (1991, 1992, 1993).", "difficulty": 1},
    {"question_zh": "《唐伯虎點秋香》（1993）中，秋香由誰飾演？", "question_en": "In 'Flirting Scholar' (1993), who plays Qiu Xiang?", "options_zh": ["鞏俐", "張敏", "朱茵", "邱淑貞"], "options_en": ["Gong Li", "Sharla Cheung", "Athena Chu", "Chingmy Yau"], "answer": 0, "explanation_zh": "鞏俐飾演秋香，是華太師府中的丫鬟。", "explanation_en": "Gong Li plays Qiu Xiang, a maid in the Hua household.", "difficulty": 1},
    {"question_zh": "《唐伯虎點秋香》中，唐伯虎的四大才子好友不包括以下哪位？", "question_en": "Which of the following is NOT one of Tang Bohu's scholar friends in 'Flirting Scholar'?", "options_zh": ["祝枝山", "文徵明", "徐禎卿", "李白"], "options_en": ["Zhu Zhishan", "Wen Zhengming", "Zhenqing", "Li Bai"], "answer": 3, "explanation_zh": "四大才子是唐伯虎、祝枝山、文徵明、徐禎卿，李白是唐代詩人。", "explanation_en": "The Four Scholars are Tang Bohu, Zhu Zhishan, Wen Zhengming, and Xu Zhenqing. Li Bai was a Tang dynasty poet.", "difficulty": 2},
    {"question_zh": "《大話西遊之月光寶盒》（1995）中，至尊寶的真實身份是誰？", "question_en": "In 'A Chinese Odyssey Part One: Pandora's Box' (1995), what is Supreme Treasure's true identity?", "options_zh": ["孫悟空", "唐三藏", "豬八戒", "牛魔王"], "options_en": ["Sun Wukong", "Tripitaka", "Zhu Bajie", "Bull Demon King"], "answer": 0, "explanation_zh": "至尊寶其實是孫悟空的轉世。", "explanation_en": "Supreme Treasure is actually the reincarnation of Sun Wukong (the Monkey King).", "difficulty": 1},
    {"question_zh": "《大話西遊》中，紫霞仙子由誰飾演？", "question_en": "Who plays the role of Zixia Fairy in 'A Chinese Odyssey'?", "options_zh": ["朱茵", "莫文蔚", "蔡少芬", "藍潔瑛"], "options_en": ["Athena Chu", "Karen Mok", "Ada Choi", "Yammie Lam"], "answer": 0, "explanation_zh": "朱茵飾演紫霞仙子，是至尊寶的摯愛。", "explanation_en": "Athena Chu plays Zixia Fairy, Supreme Treasure's true love.", "difficulty": 1},
    {"question_zh": "《大話西遊》中，月光寶盒的功能是什麼？", "question_en": "What is the function of Pandora's Box in 'A Chinese Odyssey'?", "options_zh": ["穿越時空", "實現願望", "召喚神龍", "變身"], "options_en": ["Time travel", "Grant wishes", "Summon a dragon", "Shape-shifting"], "answer": 0, "explanation_zh": "月光寶盒可以讓人穿越時空。", "explanation_en": "Pandora's Box allows the user to travel through time.", "difficulty": 1},
    {"question_zh": "《國產凌凌漆》（1994）中，周星馳飾演的角色職業是什麼？", "question_en": "In 'From Beijing with Love' (1994), what is Stephen Chow's character's profession?", "options_zh": ["特工", "殺手", "廚師", "猪肉佬"], "options_en": ["Spy", "Hitman", "Chef", "Pork seller"], "answer": 3, "explanation_zh": "凌凌漆表面上是個猪肉佬，實際上是特工。", "explanation_en": "Ling Ling-chi is a pork seller on the surface, but actually a spy.", "difficulty": 1},
    {"question_zh": "《食神》（1996）中，周星馳飾演的史提芬周最後用什麼菜式奪回食神稱號？", "question_en": "In 'The God of Cookery' (1996), what dish does Stephen Chow's character use to reclaim the title?", "options_zh": ["黯然銷魂飯", "佛跳牆", "叉燒飯", "雜碎麵"], "options_en": ["Sorrowful Rice", "Buddha Jumps Over the Wall", "Char siu rice", "Chop Suey noodles"], "answer": 0, "explanation_zh": "黯然銷魂飯是用叉燒飯配上一顆荷包蛋，感動評判。", "explanation_en": "The Sorrowful Rice is char siu rice topped with a fried egg that moved the judges.", "difficulty": 1},
    {"question_zh": "《食神》中，火雞由誰飾演？", "question_en": "Who plays the character Fire Chicken in 'The God of Cookery'?", "options_zh": ["莫文蔚", "朱茵", "吳君如", "張敏"], "options_en": ["Karen Mok", "Athena Chu", "Sandra Ng", "Sharla Cheung"], "answer": 0, "explanation_zh": "莫文蔚飾演火雞，是街頭小食攤檔的老闆娘。", "explanation_en": "Karen Mok plays Fire Chicken, a street food stall owner.", "difficulty": 1},
    {"question_zh": "《少林足球》（2001）中，周星馳飾演的角色有什麼絕招？", "question_en": "In 'Shaolin Soccer' (2001), what is Stephen Chow's character's signature move?", "options_zh": ["大力金剛腿", "旋風地堂腿", "鐵頭功", "輕功水上漂"], "options_en": ["Mighty Iron Leg", "Whirlwind Kick", "Iron Head", "Water Walking"], "answer": 0, "explanation_zh": "大力金剛腿是將少林功夫融入足球的絕招。", "explanation_en": "Mighty Iron Leg combines Shaolin kung fu with soccer.", "difficulty": 1},
    {"question_zh": "《少林足球》中，大師兄的絕招是什麼？", "question_en": "What is the eldest senior brother's specialty in 'Shaolin Soccer'?", "options_zh": ["鐵頭功", "旋風地堂腿", "金鐘罩", "鬼影擒拿手"], "options_en": ["Iron Head", "Whirlwind Leg", "Golden Bell", "Ghost Catching Hand"], "answer": 0, "explanation_zh": "大師兄精通鐵頭功，頭部能擋住任何攻擊。", "explanation_en": "The eldest brother masters Iron Head, able to block any attack with his head.", "difficulty": 1},
    {"question_zh": "《少林足球》獲得哪個電影節最佳影片？", "question_en": "Which film festival did 'Shaolin Soccer' win Best Picture at?", "options_zh": ["香港電影金像獎", "金馬獎", "康城影展", "柏林影展"], "options_en": ["Hong Kong Film Awards", "Golden Horse Awards", "Cannes", "Berlin Film Festival"], "answer": 0, "explanation_zh": "《少林足球》獲得第21屆香港電影金像獎最佳影片等7項大獎。", "explanation_en": "Shaolin Soccer won 7 awards at the 21st Hong Kong Film Awards including Best Picture.", "difficulty": 2},
    {"question_zh": "《功夫》（2004）中，故事發生在哪個地方？", "question_en": "Where is 'Kung Fu Hustle' (2004) set?", "options_zh": ["豬籠城寨", "九龍城寨", "上海灘", "少林寺"], "options_en": ["Pig Sty Alley", "Kowloon Walled City", "Shanghai", "Shaolin Temple"], "answer": 0, "explanation_zh": "故事發生在虛構的「豬籠城寨」，一個貧民區。", "explanation_en": "The story takes place in the fictional 'Pig Sty Alley', a slum neighborhood.", "difficulty": 1},
    {"question_zh": "《功夫》中，包租婆的絕招是什麼？", "question_en": "What is the Landlady's signature move in 'Kung Fu Hustle'?", "options_zh": ["獅吼功", "如來神掌", "蛤蟆功", "太極拳"], "options_en": ["Lion's Roar", "Buddha's Palm", "Toad Style", "Tai Chi"], "answer": 0, "explanation_zh": "包租婆的獅吼功能產生毀滅性的音波攻擊。", "explanation_en": "The Landlady's Lion's Roar produces devastating sonic attacks.", "difficulty": 1},
    {"question_zh": "《功夫》中，包租公的絕招是什麼？", "question_en": "What is the Landlord's specialty in 'Kung Fu Hustle'?", "options_zh": ["太極拳", "蛤蟆功", "鐵沙掌", "鷹爪功"], "options_en": ["Tai Chi", "Toad Style", "Iron Palm", "Eagle Claw"], "answer": 0, "explanation_zh": "包租公精通太極拳，能化解一切攻擊。", "explanation_en": "The Landlord masters Tai Chi, able to neutralize any attack.", "difficulty": 1},
    {"question_zh": "《功夫》中，最終大反派叫什麼名字？", "question_en": "What is the name of the main villain in 'Kung Fu Hustle'?", "options_zh": ["火雲邪神", "天殘地缺", "琴魔", "斧頭幫幫主"], "options_en": ["Beast", "Heavenly Twins", "Music Demon", "Axe Gang Leader"], "answer": 0, "explanation_zh": "火雲邪神是天下第一殺手，精通蛤蟆功。", "explanation_en": "Beast is the world's number one assassin, mastering the Toad Style.", "difficulty": 1},
    {"question_zh": "《長江7號》（2008）中，外星狗叫什麼名字？", "question_en": "What is the alien dog's name in 'CJ7' (2008)?", "options_zh": ["長江7號", "7仔", "小七", "太空狗"], "options_en": ["CJ7", "Seven", "Little Seven", "Space Dog"], "answer": 1, "explanation_zh": "外星狗被命名為「7仔」。", "explanation_en": "The alien dog is named 'Seven'.", "difficulty": 1},
    {"question_zh": "《美人魚》（2016）中，美人魚珊珊由誰飾演？", "question_en": "Who plays the mermaid Shan Shan in 'The Mermaid' (2016)?", "options_zh": ["林允", "張雨綺", "Angelababy", "倪妮"], "options_en": ["Lin Yun", "Zhang Yuqi", "Angelababy", "Ni Ni"], "answer": 0, "explanation_zh": "林允飾演美人魚珊珊，是她的電影處女作。", "explanation_en": "Lin Yun plays the mermaid Shan Shan in her film debut.", "difficulty": 1},
    {"question_zh": "《美人魚》的票房超過了多少億人民幣？", "question_en": "How much did 'The Mermaid' earn at the box office in RMB?", "options_zh": ["20億", "30億", "40億", "50億"], "options_en": ["2 billion", "3 billion", "4 billion", "5 billion"], "answer": 1, "explanation_zh": "《美人魚》票房超過33億人民幣，是當時中國票房紀錄。", "explanation_en": "The Mermaid earned over 3.3 billion RMB, setting a Chinese box office record at the time.", "difficulty": 2},
    {"question_zh": "《西遊·降魔篇》（2013）中，文章飾演誰？", "question_en": "Who does Zhang Wen play in 'Journey to the West: Conquering the Demons' (2013)?", "options_zh": ["唐三藏", "孫悟空", "豬八戒", "沙僧"], "options_en": ["Tripitaka", "Sun Wukong", "Zhu Bajie", "Sha Wujing"], "answer": 0, "explanation_zh": "文章飾演年輕的唐三藏，一個驅魔人。", "explanation_en": "Zhang Wen plays the young Tripitaka, a demon hunter.", "difficulty": 1},
    {"question_zh": "《九品芝麻官》（1994）中，包龍星的官職是什麼？", "question_en": "What is Bao Longxing's official position in 'Hail the Judge' (1994)?", "options_zh": ["九品候補知縣", "七品知縣", "六品通判", "五品知府"], "options_en": ["9th rank substitute magistrate", "7th rank magistrate", "6th rank judge", "5th rank prefect"], "answer": 0, "explanation_zh": "包龍星是九品候補知縣，官職最小。", "explanation_en": "Bao Longxing is a 9th rank substitute magistrate, the lowest official rank.", "difficulty": 1},
    {"question_zh": "《九品芝麻官》中，常威由誰飾演？", "question_en": "Who plays Chang Wei in 'Hail the Judge'?", "options_zh": ["鄒兆龍", "元華", "甄子丹", "林國斌"], "options_en": ["Collin Chou", "Yuen Wah", "Donnie Yen", "Lam Kwok-bin"], "answer": 0, "explanation_zh": "鄒兆龍飾演反派常威。", "explanation_en": "Collin Chou plays the villain Chang Wei.", "difficulty": 2},
    {"question_zh": "《破壞之王》（1994）中，周星馳飾演的角色叫什麼？", "question_en": "What is Stephen Chow's character's name in 'Love on Delivery' (1994)?", "options_zh": ["何金水", "黃小虎", "林耀國", "陳夢吉"], "options_en": ["Ho Kam-sui", "Wong Siu-fu", "Lam Yiu-kwok", "Chan Mong-kat"], "answer": 0, "explanation_zh": "何金水是個外賣仔，為了追求心儀女子而學武。", "explanation_en": "Ho Kam-sui is a delivery boy who learns martial arts to win over his crush.", "difficulty": 1},
    {"question_zh": "《賭俠》（1990）中，周星馳與誰合作主演？", "question_en": "Who co-stars with Stephen Chow in 'God of Gamblers II' (1990)?", "options_zh": ["劉德華", "周潤發", "成龍", "李連杰"], "options_en": ["Andy Lau", "Chow Yun-fat", "Jackie Chan", "Jet Li"], "answer": 0, "explanation_zh": "劉德華飾演賭俠陳小刀，與周星馳的左頌星合作。", "explanation_en": "Andy Lau plays the Knight of Gamblers, partnering with Stephen Chow's character.", "difficulty": 1},
    {"question_zh": "《鹿鼎記》（1992）中，韋小寶有幾多個老婆？", "question_en": "How many wives does Wei Xiaobao have in 'Royal Tramp' (1992)?", "options_zh": ["5個", "6個", "7個", "8個"], "options_en": ["5", "6", "7", "8"], "answer": 2, "explanation_zh": "韋小寶最終有7個老婆。", "explanation_en": "Wei Xiaobao ultimately has 7 wives.", "difficulty": 1},
    {"question_zh": "《鹿鼎記》中，韋小寶加入的組織叫什麼？", "question_en": "What organization does Wei Xiaobao join in 'Royal Tramp'?", "options_zh": ["天地會", "白蓮教", "日月神教", "紅花會"], "options_en": ["Heaven and Earth Society", "White Lotus Sect", "Sun Moon Sect", "Red Flower Society"], "answer": 0, "explanation_zh": "韋小寶加入天地會，成為青木堂香主。", "explanation_en": "Wei Xiaobao joins the Heaven and Earth Society, becoming the leader of the Green Wood Hall.", "difficulty": 1},
    {"question_zh": "《審死官》（1992）中，周星馳飾演的角色職業是什麼？", "question_en": "What is Stephen Chow's character's profession in 'Justice, My Foot!' (1992)?", "options_zh": ["狀師", "大夫", "將軍", "商人"], "options_en": ["Lawyer", "Doctor", "General", "Merchant"], "answer": 0, "explanation_zh": "周星馳飾演宋世傑，是清朝著名狀師。", "explanation_en": "Stephen Chow plays Song Shijie, a famous Qing dynasty lawyer.", "difficulty": 1},
    {"question_zh": "《審死官》中，宋世傑的妻子由誰飾演？", "question_en": "Who plays Song Shijie's wife in 'Justice, My Foot!'?", "options_zh": ["梅艷芳", "張敏", "朱茵", "邱淑貞"], "options_en": ["Anita Mui", "Sharla Cheung", "Athena Chu", "Chingmy Yau"], "answer": 0, "explanation_zh": "梅艷芳飾演宋世傑的妻子，武功高強。", "explanation_en": "Anita Mui plays Song Shijie's wife, a skilled martial artist.", "difficulty": 1},
    {"question_zh": "《百變星君》（1995）中，周星馳飾演的角色能變什麼？", "question_en": "In 'Sixty Million Dollar Man' (1995), what can Stephen Chow's character transform into?", "options_zh": ["任何東西", "只有動物", "只有食物", "只有日用品"], "options_en": ["Anything", "Only animals", "Only food", "Only household items"], "answer": 0, "explanation_zh": "角色經過改造後能變身成任何東西。", "explanation_en": "After modification, the character can transform into anything.", "difficulty": 1},
    {"question_zh": "《大內密探零零發》（1996）中，零零發的專長是什麼？", "question_en": "What is 008's specialty in 'Forbidden City Cop' (1996)?", "options_zh": ["發明東西", "武功", "易容術", "暗器"], "options_en": ["Inventing things", "Martial arts", "Disguise", "Hidden weapons"], "answer": 0, "explanation_zh": "零零發專長發明各種奇怪裝置。", "explanation_en": "008 specializes in inventing various strange devices.", "difficulty": 1},
    {"question_zh": "《喜劇之王》（1999）中，尹天仇的夢想是什麼？", "question_en": "What is Yin Tianchou's dream in 'King of Comedy' (1999)?", "options_zh": ["成為偉大演員", "成為導演", "成為歌手", "成為編劇"], "options_en": ["Become a great actor", "Become a director", "Become a singer", "Become a screenwriter"], "answer": 0, "explanation_zh": "尹天仇夢想成為一個偉大的演員。", "explanation_en": "Yin Tianchou dreams of becoming a great actor.", "difficulty": 1},
    {"question_zh": "《喜劇之王》中，柳飄飄由誰飾演？", "question_en": "Who plays Liu Piaopiao in 'King of Comedy'?", "options_zh": ["張柏芝", "朱茵", "莫文蔚", "趙薇"], "options_en": ["Cecilia Cheung", "Athena Chu", "Karen Mok", "Zhao Wei"], "answer": 0, "explanation_zh": "張柏芝飾演柳飄飄，是她的成名作。", "explanation_en": "Cecilia Cheung plays Liu Piaopiao, her breakout role.", "difficulty": 1},
    {"question_zh": "《千王之王2000》（1999）中，周星馳飾演的角色叫什麼？", "question_en": "What is Stephen Chow's character's name in 'The Tricky Master' (1999)?", "options_zh": ["黃師傅", "法拉利", "千王之王", "賭神"], "options_en": ["Master Wong", "Ferrari", "King of Gamblers", "God of Gamblers"], "answer": 1, "explanation_zh": "周星馳飾演的角色外號「法拉利」。", "explanation_en": "Stephen Chow's character is nicknamed 'Ferrari'.", "difficulty": 1},
    {"question_zh": "《回魂夜》（1995）中，周星馳飾演的角色職業是什麼？", "question_en": "What is Stephen Chow's character's profession in 'Out of the Dark' (1995)?", "options_zh": ["捉鬼大師", "警察", "保安", "道士"], "options_en": ["Ghost buster", "Police officer", "Security guard", "Taoist priest"], "answer": 0, "explanation_zh": "周星馳飾演一個精神病院的捉鬼專家。", "explanation_en": "Stephen Chow plays a ghost-catching expert in a mental hospital.", "difficulty": 1},
    {"question_zh": "《算死草》（1997）中，周星馳飾演誰？", "question_en": "Who does Stephen Chow play in 'Lawyer Lawyer' (1997)?", "options_zh": ["陳夢吉", "方唐鏡", "宋世傑", "包龍星"], "options_en": ["Chan Mong-kat", "Fong Tong-geng", "Song Shijie", "Bao Longxing"], "answer": 0, "explanation_zh": "周星馳飾演清代名狀師陳夢吉。", "explanation_en": "Stephen Chow plays Chan Mong-kat, a famous Qing dynasty lawyer.", "difficulty": 2},
    {"question_zh": "《行運一條龍》（1998）中，故事圍繞什麼場所展開？", "question_en": "What is the central setting of 'The Lucky Guy' (1998)?", "options_zh": ["茶餐廳", "學校", "醫院", "警局"], "options_en": ["Cha chaan teng (tea restaurant)", "School", "Hospital", "Police station"], "answer": 0, "explanation_zh": "故事圍繞一間茶餐廳展開。", "explanation_en": "The story revolves around a cha chaan teng (Hong Kong-style tea restaurant).", "difficulty": 1},
    {"question_zh": "周星馳在哪一年獲得香港電影金像獎最佳導演？", "question_en": "In which year did Stephen Chow win the Hong Kong Film Award for Best Director?", "options_zh": ["2002年", "2004年", "2005年", "2008年"], "options_en": ["2002", "2004", "2005", "2008"], "answer": 2, "explanation_zh": "周星馳憑《功夫》獲得2005年第24屆香港電影金像獎最佳導演。", "explanation_en": "Stephen Chow won Best Director at the 24th Hong Kong Film Awards in 2005 for 'Kung Fu Hustle'.", "difficulty": 2},
    {"question_zh": "周星馳的綽號是什麼？", "question_en": "What is Stephen Chow's nickname?", "options_zh": ["星爺", "喜劇之王", "笑匠", "以上皆是"], "options_en": ["Sing Yeh (Brother Sing)", "King of Comedy", "Laughing Master", "All of the above"], "answer": 3, "explanation_zh": "周星馳被稱為星爺、喜劇之王、笑匠等多個綽號。", "explanation_en": "Stephen Chow is known by many nicknames including Sing Yeh, King of Comedy, and Laughing Master.", "difficulty": 1},
]

# Generate remaining questions programmatically for each series
def gen_movie_qa(series_name, films, characters, actors, fun_facts, count=200):
    """Generate movie quiz questions from template data."""
    questions = []
    import random
    random.seed(hash(series_name))
    
    # We'll create questions from the provided data
    for i, fact in enumerate(fun_facts[:count]):
        q = {
            "question_zh": fact["q_zh"],
            "question_en": fact["q_en"],
            "options_zh": fact["o_zh"],
            "options_en": fact["o_en"],
            "answer": fact["a"],
            "explanation_zh": fact["e_zh"],
            "explanation_en": fact["e_en"],
            "difficulty": fact.get("d", 1)
        }
        questions.append(q)
    return questions

# For space efficiency, I'll create the questions directly in the JSON files
# Let me write all series data

def write_questions(filepath, questions):
    """Write questions to JSON file."""
    with open(filepath, 'w', encoding='utf-8') as f:\n        json.dump(questions, f, ensure_ascii=False, indent=2)\n\ndef main():
    # ── 周星馳系列 ──
    write_questions(BASE / "movies/topics/stephen_chow.json", STEPHEN_CHOW)
    print(f"✅ 周星馳系列: {len(STEPHEN_CHOW)} questions")
    
    # ── 其他系列用模板生成 ──
    for series_name, data in SERIES_DATA.items():
        questions = generate_series_questions(series_name, data)
        filepath = BASE / f"movies/topics/{data['file']}.json"
        write_questions(filepath, questions)
        print(f"✅ {data['name']}: {len(questions)} questions")

# Series data templates
SERIES_DATA = {
    "andy_lau": {
        "name": "劉德華系列",
        "file": "andy_lau",
        "emoji": "🎤",
        "color": "#e74c3c",
        "questions": [
            {"q_zh": "《無間道》（2002）中，劉德華飾演的角色叫什麼名字？", "q_en": "What is Andy Lau's character's name in 'Infernal Affairs' (2002)?", "o_zh": ["劉建明", "陳永仁", "韓琛", "黃志誠"], "o_en": ["Lau Kin-ming", "Chan Wing-yan", "Hon Sam", "Wong Chi-sing"], "a": 0, "e_zh": "劉建明是黑幫派入警隊的臥底。", "e_en": "Lau Kin-ming is a triad mole planted in the police force.", "d": 1},
            {"q_zh": "《無間道》中，陳永仁由誰飾演？", "q_en": "Who plays Chan Wing-yan in 'Infernal Affairs'?", "o_zh": ["梁朝偉", "黃秋生", "曾志偉", "吳鎮宇"], "o_en": ["Tony Leung", "Anthony Wong", "Eric Tsang", "Francis Ng"], "a": 0, "e_zh": "梁朝偉飾演潜入黑幫的警方臥底陳永仁。", "e_en": "Tony Leung plays Chan Wing-yan, an undercover cop infiltrating the triads.", "d": 1},
            {"q_zh": "《無間道》的經典對白「對唔住，我係警察」是誰說的？", "q_en": "Who says the classic line 'Sorry, I'm a cop' in 'Infernal Affairs'?", "o_zh": ["劉建明", "陳永仁", "韓琛", "黃志誠"], "o_en": ["Lau Kin-ming", "Chan Wing-yan", "Hon Sam", "Wong Chi-sing"], "a": 1, "e_zh": "陳永仁在天台對劉建明說出這句經典對白。", "e_en": "Chan Wing-yan says this classic line to Lau Kin-ming on the rooftop.", "d": 1},
            {"q_zh": "《天下無賊》（2004）中，劉德華飾演的角色是什麼職業？", "q_en": "What is Andy Lau's character's profession in 'A World Without Thieves' (2004)?", "o_zh": ["小偷", "警察", "商人", "司機"], "o_en": ["Thief", "Police officer", "Businessman", "Driver"], "a": 0, "e_zh": "劉德華飾演一個想改過自新的小偷。", "e_en": "Andy Lau plays a thief who wants to reform.", "d": 1},
            {"q_zh": "《暗戰》（1999）中，劉德華飾演什麼角色？", "q_en": "What role does Andy Lau play in 'Running Out of Time' (1999)?", "o_zh": ["絕症患者/高智商罪犯", "警察", "醫生", "律師"], "o_en": ["Terminally ill genius criminal", "Police officer", "Doctor", "Lawyer"], "a": 0, "e_zh": "劉德華飾演一個只剩數天命的高智商罪犯。", "e_en": "Andy Lau plays a genius criminal with only days to live.", "d": 1},
            {"q_zh": "劉德華出道時是哪間電視台的藝員？", "q_en": "Which TV station did Andy Lau start his career at?", "o_zh": ["無綫電視（TVB）", "亞洲電視（ATV）", "佳藝電視", "有線電視"], "o_en": ["TVB", "ATV", "RTV", "Cable TV"], "a": 0, "e_zh": "劉德華1981年從無綫電視藝員訓練班畢業出道。", "e_en": "Andy Lau graduated from TVB's acting training class in 1981.", "d": 1},
            {"q_zh": "劉德華被稱為「四大天王」之一，其他三位是？", "q_en": "Andy Lau is one of the 'Four Heavenly Kings'. Who are the other three?", "o_zh": ["張學友、郭富城、黎明", "譚詠麟、張國榮、陳百強", "成龍、周潤發、李連杰", "梁朝偉、劉青云、吳鎮宇"], "o_en": ["Jacky Cheung, Aaron Kwok, Leon Lai", "Alan Tam, Leslie Mok, Danny Chan", "Jackie Chan, Chow Yun-fat, Jet Li", "Tony Leung, Sean Lau, Francis Ng"], "a": 0, "e_zh": "四大天王是劉德華、張學友、郭富城、黎明。", "e_en": "The Four Heavenly Kings are Andy Lau, Jacky Cheung, Aaron Kwok, and Leon Lai.", "d": 1},
            {"q_zh": "劉德華獲得過幾次香港電影金像獎最佳男主角？", "q_en": "How many times has Andy Lau won the Hong Kong Film Award for Best Actor?", "o_zh": ["2次", "3次", "4次", "5次"], "o_en": ["2 times", "3 times", "4 times", "5 times"], "a": 1, "e_zh": "劉德華憑《暗戰》《大隻佬》《桃姐》三度獲得金像獎影帝。", "e_en": "Andy Lau won Best Actor three times for 'Running Out of Time', 'Running on Karma', and 'A Simple Life'.", "d": 2},
            {"q_zh": "《桃姐》（2012）中，劉德華飾演的角色叫什麼？", "q_en": "What is Andy Lau's character's name in 'A Simple Life' (2012)?", "o_zh": ["Roger", "Sam", "David", "Michael"], "o_en": ["Roger", "Sam", "David", "Michael"], "a": 0, "e_zh": "劉德華飾演Roger，一個照顧老傭人桃姐的電影製片人。", "e_en": "Andy Lau plays Roger, a film producer who cares for his elderly servant Sister Peach.", "d": 1},
            {"q_zh": "劉德華的唱片公司叫什麼？", "q_en": "What is Andy Lau's record label called?", "o_zh": ["映藝娛樂", "東亞唱片", "華納唱片", "環球唱片"], "o_en": ["Focus Films", "East Asia Records", "Warner Music", "Universal Music"], "a": 0, "e_zh": "劉德華創辦了映藝娛樂集團。", "e_en": "Andy Lau founded Focus Films Group.", "d": 2},
            {"q_zh": "《拆彈專家》系列中，劉德華飾演什麼職業？", "q_en": "What is Andy Lau's profession in the 'Shock Wave' series?", "o_zh": ["拆彈專家", "特警", "消防員", "卧底"], "o_en": ["Bomb disposal expert", "SWAT officer", "Firefighter", "Undercover agent"], "a": 0, "e_zh": "劉德華飾演警隊拆彈專家章在山。", "e_en": "Andy Lau plays bomb disposal expert Zhang Zai-shan.", "d": 1},
            {"q_zh": "劉德華演唱會最多連續開幾場？", "q_en": "What is Andy Lau's record for consecutive concert performances?", "o_zh": ["13場", "15場", "20場", "25場"], "o_en": ["13 shows", "15 shows", "20 shows", "25 shows"], "a": 2, "e_zh": "劉德華曾連續開20場演唱會。", "e_en": "Andy Lau once held 20 consecutive concerts.", "d": 2},
            {"q_zh": "《五虎將之決裂》中，五虎將不包括以下哪位？", "q_en": "Which of the following is NOT one of the Five Tigers?", "o_zh": ["梁朝偉", "黃日華", "苗僑偉", "周星馳"], "o_en": ["Tony Leung", "Felix Wong", "Michael Miu", "Stephen Chow"], "a": 3, "e_zh": "五虎將是劉德華、梁朝偉、黃日華、苗僑偉、湯鎮業。", "e_en": "The Five Tigers are Andy Lau, Tony Leung, Felix Wong, Michael Miu, and Kent Tong.", "d": 1},
            {"q_zh": "劉德華首張個人專輯是哪一年推出？", "q_en": "In which year did Andy Lau release his first solo album?", "o_zh": ["1985年", "1986年", "1988年", "1990年"], "o_en": ["1985", "1986", "1988", "1990"], "a": 0, "e_zh": "劉德華1985年推出首張個人專輯。", "e_en": "Andy Lau released his first solo album in 1985.", "d": 2},
            {"q_zh": "劉德華主演的《瘦身男女》（2001）中，他的角色有什麼特點？", "q_en": "What is special about Andy Lau's character in 'Love on a Diet' (2001)?", "o_zh": ["飾演肥仔", "飾演瘦子", "飾演殘疾人", "飾演老人"], "o_en": ["Plays a fat person", "Plays a thin person", "Plays a disabled person", "Plays an elderly person"], "a": 0, "e_zh": "劉德華在片中以肥胖造型示人。", "e_en": "Andy Lau appears in a fat suit in the film.", "d": 1},
            {"q_zh": "《孤男寡女》（2000）中，劉德華與誰合作？", "q_en": "Who co-stars with Andy Lau in 'Needing You...' (2000)?", "o_zh": ["鄭秀文", "張柏芝", "李嘉欣", "邱淑貞"], "o_en": ["Sammi Cheng", "Cecilia Cheung", "Michelle Reis", "Chingmy Yau"], "a": 0, "e_zh": "劉德華與鄭秀文合作，開啟了兩人多次合作的序幕。", "e_en": "Andy Lau co-stars with Sammi Cheng, beginning their long partnership.", "d": 1},
            {"q_zh": "劉德華出生於哪一年？", "q_en": "In which year was Andy Lau born?", "o_zh": ["1961年", "1962年", "1963年", "1965年"], "o_en": ["1961", "1962", "1963", "1965"], "a": 0, "e_zh": "劉德華1961年9月27日出生。", "e_en": "Andy Lau was born on September 27, 1961.", "d": 1},
            {"q_zh": "劉德華的歌迷統稱叫什麼？", "q_en": "What are Andy Lau's fans collectively called?", "o_zh": ["華迷", "華粉", "華仔迷", "劉迷"], "o_en": ["Hua fans", "Andy fans", "Lau fans", "Brother fans"], "a": 0, "e_zh": "劉德華的歌迷統稱為「華迷」。", "e_en": "Andy Lau's fans are collectively known as 'Hua fans'.", "d": 1},
            {"q_zh": "《墨攻》（2006）中，劉德華飾演誰？", "q_en": "Who does Andy Lau play in 'A Battle of Wits' (2006)?", "o_zh": ["革離", "墨子", "孫臏", "龐涓"], "o_en": ["Ge Li", "Mo Zi", "Sun Bin", "Pang Juan"], "a": 0, "e_zh": "劉德華飾演墨家弟子革離。", "e_en": "Andy Lau plays Ge Li, a follower of the Mohist school.", "d": 2},
            {"q_zh": "《投名狀》（2007）中，劉德華飾演的角色叫什麼？", "q_en": "What is Andy Lau's character's name in 'The Warlords' (2007)?", "o_zh": ["趙二虎", "姜午陽", "龐青雲", "陳玉蓮"], "o_en": ["Zhao Erhu", "Jiang Wuyang", "Pang Qingyun", "Chen Yulian"], "a": 0, "e_zh": "劉德華飾演趙二虎，是三兄弟中的二哥。", "e_en": "Andy Lau plays Zhao Erhu, the second of three sworn brothers.", "d": 1},
            {"q_zh": "劉德華是哪一年獲頒銅紫荊星章？", "q_en": "In which year was Andy Lau awarded the Bronze Bauhinia Star?", "o_zh": ["2004年", "2006年", "2008年", "2010年"], "o_en": ["2004", "2006", "2008", "2010"], "a": 0, "e_zh": "劉德華2004年獲香港特區政府頒授銅紫荊星章。", "e_en": "Andy Lau was awarded the Bronze Bauhinia Star by the HKSAR government in 2004.", "d": 2},
        ]
    },
    "tony_leung": {
        "name": "梁朝偉系列",
        "file": "tony_leung",
        "emoji": "🎭",
        "color": "#2c3e50",
        "questions": [
            {"q_zh": "梁朝偉獲得過幾次香港電影金像獎最佳男主角？", "q_en": "How many times has Tony Leung won the Hong Kong Film Award for Best Actor?", "o_zh": ["3次", "4次", "5次", "6次"], "o_en": ["3 times", "4 times", "5 times", "6 times"], "a": 2, "e_zh": "梁朝偉五度獲得金像獎影帝，是金像獎史上最多。", "e_en": "Tony Leung has won Best Actor five times, the most in HK Film Awards history.", "d": 1},
            {"q_zh": "《花樣年華》（2000）中，梁朝偉飾演的角色叫什麼？", "q_en": "What is Tony Leung's character's name in 'In the Mood for Love' (2000)?", "o_zh": ["周慕雲", "易先生", "黎耀輝", "陳永仁"], "o_en": ["Chow Mo-wan", "Mr. Yee", "Lai Yiu-fai", "Chan Wing-yan"], "a": 0, "e_zh": "梁朝偉飾演報社編輯周慕雲。", "e_en": "Tony Leung plays newspaper editor Chow Mo-wan.", "d": 1},
            {"q_zh": "《花樣年華》的導演是誰？", "q_en": "Who directed 'In the Mood for Love'?", "o_zh": ["王家衛", "杜琪峰", "許鞍華", "陳可辛"], "o_en": ["Wong Kar-wai", "Johnnie To", "Ann Hui", "Peter Chan"], "a": 0, "e_zh": "《花樣年華》由王家衛執導。", "e_en": "In the Mood for Love was directed by Wong Kar-wai.", "d": 1},
            {"q_zh": "《花樣年華》中，與梁朝偉合作的女主角是誰？", "q_en": "Who is Tony Leung's co-star in 'In the Mood for Love'?", "o_zh": ["張曼玉", "劉嘉玲", "章子怡", "鞏俐"], "o_en": ["Maggie Cheung", "Carina Lau", "Zhang Ziyi", "Gong Li"], "a": 0, "e_zh": "張曼玉飾演蘇麗珍，與梁朝偉演繹一段含蓄的愛情。", "e_en": "Maggie Cheung plays Su Li-zhen, portraying a restrained romance with Tony Leung.", "d": 1},
            {"q_zh": "《無間道》中，梁朝偉飾演的角色身份是什麼？", "q_en": "What is Tony Leung's character's identity in 'Infernal Affairs'?", "o_zh": ["警方臥底", "黑幫臥底", "普通警察", "黑幫老大"], "o_en": ["Police undercover", "Triad mole", "Regular cop", "Triad boss"], "a": 0, "e_zh": "梁朝偉飾演潜入黑幫的警方臥底陳永仁。", "e_en": "Tony Leung plays Chan Wing-yan, an undercover cop in the triads.", "d": 1},
            {"q_zh": "梁朝偉憑哪部電影獲得康城影帝？", "q_en": "For which film did Tony Leung win the Cannes Best Actor award?", "o_zh": ["《花樣年華》", "《無間道》", "《色，戒》", "《2046》"], "o_en": ["In the Mood for Love", "Infernal Affairs", "Lust, Caution", "2046"], "a": 0, "e_zh": "梁朝偉憑《花樣年華》獲得2000年康城影帝。", "e_en": "Tony Leung won the Cannes Best Actor award in 2000 for 'In the Mood for Love'.", "d": 1},
            {"q_zh": "《春光乍洩》（1997）中，梁朝偉飾演的角色叫什麼？", "q_en": "What is Tony Leung's character's name in 'Happy Together' (1997)?", "o_zh": ["黎耀輝", "何寶榮", "周慕雲", "易先生"], "o_en": ["Lai Yiu-fai", "Ho Po-wing", "Chow Mo-wan", "Mr. Yee"], "a": 0, "e_zh": "梁朝偉飾演黎耀輝，與張國榮飾演一對同性戀人。", "e_en": "Tony Leung plays Lai Yiu-fai, in a same-sex relationship with Leslie Cheung's character.", "d": 1},
            {"q_zh": "《春光乍洩》的導演是誰？", "q_en": "Who directed 'Happy Together'?", "o_zh": ["王家衛", "杜琪峰", "關錦鵬", "陳凱歌"], "o_en": ["Wong Kar-wai", "Johnnie To", "Stanley Kwan", "Chen Kaige"], "a": 0, "e_zh": "《春光乍洩》由王家衛執導。", "e_en": "Happy Together was directed by Wong Kar-wai.", "d": 1},
            {"q_zh": "梁朝偉的太太是誰？", "q_en": "Who is Tony Leung's wife?", "o_zh": ["劉嘉玲", "張曼玉", "曾華倩", "黎美嫻"], "o_en": ["Carina Lau", "Maggie Cheung", "Margie Tsang", "Kitty Lai"], "a": 0, "e_zh": "梁朝偉與劉嘉玲在2008年結婚。", "e_en": "Tony Leung married Carina Lau in 2008.", "d": 1},
            {"q_zh": "《色，戒》（2007）中，梁朝偉飾演的角色叫什麼？", "q_en": "What is Tony Leung's character's name in 'Lust, Caution' (2007)?", "o_zh": ["易先生", "周慕雲", "陳永仁", "黎耀輝"], "o_en": ["Mr. Yee", "Chow Mo-wan", "Chan Wing-yan", "Lai Yiu-fai"], "a": 0, "e_zh": "梁朝偉飾演汪精衛政權的特務頭子易先生。", "e_en": "Tony Leung plays Mr. Yee, a spy chief in the Wang Jingwei government.", "d": 1},
            {"q_zh": "《色，戒》的導演是誰？", "q_en": "Who directed 'Lust, Caution'?", "o_zh": ["李安", "王家衛", "張藝謀", "陳凱歌"], "o_en": ["Ang Lee", "Wong Kar-wai", "Zhang Yimou", "Chen Kaige"], "a": 0, "e_zh": "《色，戒》由李安執導。", "e_en": "Lust, Caution was directed by Ang Lee.", "d": 1},
            {"q_zh": "梁朝偉出道時是哪間電視台的藝員？", "q_en": "Which TV station did Tony Leung start his career at?", "o_zh": ["無綫電視（TVB）", "亞洲電視（ATV）", "佳藝電視", "有線電視"], "o_en": ["TVB", "ATV", "RTV", "Cable TV"], "a": 0, "e_zh": "梁朝偉1982年從無綫電視藝員訓練班畢業。", "e_en": "Tony Leung graduated from TVB's acting training class in 1982.", "d": 1},
            {"q_zh": "《重慶森林》（1994）中，梁朝偉飾演什麼職業？", "q_en": "What is Tony Leung's profession in 'Chungking Express' (1994)?", "o_zh": ["警察", "廚師", "作家", "醫生"], "o_en": ["Police officer", "Chef", "Writer", "Doctor"], "a": 0, "e_zh": "梁朝偉飾演警察663。", "e_en": "Tony Leung plays Police Officer 663.", "d": 1},
            {"q_zh": "梁朝偉與劉德華合演的《鹿鼎記》（1984）中，梁朝偉飾演誰？", "q_en": "Who does Tony Leung play in the TVB 'Royal Tramp' (1984)?", "o_zh": ["韋小寶", "康熙", "陳近南", "多隆"], "o_en": ["Wei Xiaobao", "Kangxi", "Chen Jinnan", "Dolong"], "a": 0, "e_zh": "梁朝偉在TVB版《鹿鼎記》中飾演韋小寶。", "e_en": "Tony Leung plays Wei Xiaobao in the TVB version of 'Royal Tramp'.", "d": 1},
            {"q_zh": "梁朝偉出生於哪一年？", "q_en": "In which year was Tony Leung born?", "o_zh": ["1960年", "1962年", "1964年", "1966年"], "o_en": ["1960", "1962", "1964", "1966"], "a": 1, "e_zh": "梁朝偉1962年6月27日出生。", "e_en": "Tony Leung was born on June 27, 1962.", "d": 1},
            {"q_zh": "梁朝偉首部執導的電影是什麼？", "q_en": "What is Tony Leung's directorial debut film?", "o_zh": ["《風再起時》", "尚未執導", "《一代宗師》", "《擺渡人》"], "o_en": ["Where the Wind Blows", "Has not directed", "The Grandmaster", "See You Tomorrow"], "a": 0, "e_zh": "梁朝偉首部執導的電影是《風再起時》。", "e_en": "Tony Leung's directorial debut is 'Where the Wind Blows'.", "d": 2},
            {"q_zh": "《一代宗師》（2013）中，梁朝偉飾演誰？", "q_en": "Who does Tony Leung play in 'The Grandmaster' (2013)?", "o_zh": ["葉問", "宮二", "一線天", "馬三"], "o_en": ["Ip Man", "Gong Er", "Razor", "Ma San"], "a": 0, "e_zh": "梁朝偉飾演詠春拳宗師葉問。", "e_en": "Tony Leung plays Wing Chun grandmaster Ip Man.", "d": 1},
            {"q_zh": "《一代宗師》的導演是誰？", "q_en": "Who directed 'The Grandmaster'?", "o_zh": ["王家衛", "甄子丹", "劉偉強", "徐克"], "o_en": ["Wong Kar-wai", "Donnie Yen", "Andrew Lau", "Tsui Hark"], "a": 0, "e_zh": "《一代宗師》由王家衛執導。", "e_en": "The Grandmaster was directed by Wong Kar-wai.", "d": 1},
            {"q_zh": "梁朝偉首部好萊塢電影是什麼？", "q_en": "What is Tony Leung's first Hollywood film?", "o_zh": ["《尚氣與十環傳奇》", "《藝伎回憶錄》", "《碟中諜》", "《木乃伊》"], "o_en": ["Shang-Chi and the Legend of the Ten Rings", "Memoirs of a Geisha", "Mission: Impossible", "The Mummy"], "a": 0, "e_zh": "梁朝偉首部好萊塢電影是2021年的《尚氣與十環傳奇》。", "e_en": "Tony Leung's first Hollywood film is 'Shang-Chi and the Legend of the Ten Rings' (2021).", "d": 1},
            {"q_zh": "《尚氣與十環傳奇》中，梁朝偉飾演什麼角色？", "q_en": "What role does Tony Leung play in 'Shang-Chi'?", "o_zh": ["文武（徐文武）", "尚氣", "十環幫首領", "以上皆是"], "o_en": ["Wenwu", "Shang-Chi", "Ten Rings leader", "All of the above"], "a": 0, "e_zh": "梁朝偉飾演尚氣的父親文武（徐文武），十環幫首領。", "e_en": "Tony Leung plays Wenwu, Shang-Chi's father and leader of the Ten Rings.", "d": 1},
            {"q_zh": "梁朝偉與張國榮合演的《阿飛正傳》（1990）導演是誰？", "q_en": "Who directed 'Days of Being Wild' (1990) starring Tony Leung and Leslie Cheung?", "o_zh": ["王家衛", "關錦鵬", "許鞍華", "譚家明"], "o_en": ["Wong Kar-wai", "Stanley Kwan", "Ann Hui", "Patrick Tam"], "a": 0, "e_zh": "《阿飛正傳》由王家衛執導。", "e_en": "Days of Being Wild was directed by Wong Kar-wai.", "d": 1},
        ]
    },
    "louis_koo": {
        "name": "古天樂系列",
        "file": "louis_koo",
        "emoji": "😎",
        "color": "#27ae60",
        "questions": [
            {"q_zh": "古天樂出道時是哪間電視台的藝員？", "q_en": "Which TV station did Louis Koo start his career at?", "o_zh": ["無綫電視（TVB）", "亞洲電視（ATV）", "佳藝電視", "有線電視"], "o_en": ["TVB", "ATV", "RTV", "Cable TV"], "a": 0, "e_zh": "古天樂1993年加入無綫電視。", "e_en": "Louis Koo joined TVB in 1993.", "d": 1},
            {"q_zh": "古天樂在TVB版《神鵰俠侶》（1995）中飾演誰？", "q_en": "Who does Louis Koo play in the TVB 'Return of the Condor Heroes' (1995)?", "o_zh": ["楊過", "郭靖", "張無忌", "令狐沖"], "o_en": ["Yang Guo", "Guo Jing", "Zhang Wuji", "Linghu Chong"], "a": 0, "e_zh": "古天樂飾演楊過，與李若彤飾演小龍女。", "e_en": "Louis Koo plays Yang Guo, co-starring with Carman Lee as Xiaolongnü.", "d": 1},
            {"q_zh": "《神鵰俠侶》中，小龍女由誰飾演？", "q_en": "Who plays Xiaolongnü in the TVB 'Return of the Condor Heroes'?", "o_zh": ["李若彤", "陳玉蓮", "范文芳", "劉亦菲"], "o_en": ["Carman Lee", "Idy Chan", "Fann Wong", "Liu Yifei"], "a": 0, "e_zh": "李若彤飾演小龍女，被譽為最經典版本。", "e_en": "Carman Lee plays Xiaolongnü, considered the most classic portrayal.", "d": 1},
            {"q_zh": "古天樂創辦的電影公司叫什麼？", "q_en": "What is Louis Koo's film production company called?", "o_zh": ["天下一電影", "中國星", "寰亞", "英皇"], "o_en": ["One Cool Film", "China Star", "Media Asia", "Emperor"], "a": 0, "e_zh": "古天樂創辦了天下一電影（One Cool Film）。", "e_en": "Louis Koo founded One Cool Film.", "d": 1},
            {"q_zh": "古天樂獲得過香港電影金像獎最佳男主角嗎？", "q_en": "Has Louis Koo won the Hong Kong Film Award for Best Actor?", "o_zh": ["有，1次", "有，2次", "沒有", "有，3次"], "o_en": ["Yes, once", "Yes, twice", "No", "Yes, three times"], "a": 0, "e_zh": "古天樂憑《殺破狼·貪狼》獲得2018年金像獎影帝。", "e_en": "Louis Koo won Best Actor at the 2018 HK Film Awards for 'Paradox'.", "d": 1},
            {"q_zh": "《掃毒》系列電影中，古天樂飾演什麼角色？", "q_en": "What role does Louis Koo play in the 'Line Walker' series?", "o_zh": ["卧底探員", "毒販", "警察", "國際刑警"], "o_en": ["Undercover agent", "Drug dealer", "Police officer", "Interpol"], "a": 0, "e_zh": "古天樂在《掃毒》系列中飾演卧底探員。", "e_en": "Louis Koo plays an undercover agent in the 'Line Walker' series.", "d": 1},
            {"q_zh": "古天樂在哪一年獲得香港電影金像獎影帝？", "q_en": "In which year did Louis Koo win the HK Film Award for Best Actor?", "o_zh": ["2016年", "2017年", "2018年", "2019年"], "o_en": ["2016", "2017", "2018", "2019"], "a": 2, "e_zh": "古天樂2018年憑《殺破狼·貪狼》獲得金像獎影帝。", "e_en": "Louis Koo won Best Actor in 2018 for 'Paradox'.", "d": 1},
            {"q_zh": "古天樂的慈善基金叫什麼？", "q_en": "What is Louis Koo's charitable foundation called?", "o_zh": ["古天樂慈善基金", "天下一慈善基金", "香港演藝人協會基金", "聯合國兒童基金"], "o_en": ["Louis Koo Charity Foundation", "One Cool Charity", "HKAPA Foundation", "UNICEF"], "a": 0, "e_zh": "古天樂創辦了古天樂慈善基金，在內地捐建了超過100所學校。", "e_en": "Louis Koo founded the Louis Koo Charity Foundation, building over 100 schools in mainland China.", "d": 1},
            {"q_zh": "《尋秦記》（2001）中，古天樂飾演的角色叫什麼？", "q_en": "What is Louis Koo's character's name in 'A Step into the Past' (2001)?", "o_zh": ["項少龍", "嬴政", "趙盤", "嫪毐"], "o_en": ["Hsiang Shao-lung", "Ying Zheng", "Zhao Pan", "Lao Ai"], "a": 0, "e_zh": "古天樂飾演從現代穿越到秦國的項少龍。", "e_en": "Louis Koo plays Hsiang Shao-lung, who travels from modern times to the Qin dynasty.", "d": 1},
            {"q_zh": "《尋秦記》是改編自哪位作家的小說？", "q_en": "Which author's novel is 'A Step into the Past' adapted from?", "o_zh": ["黃易", "金庸", "古龍", "梁羽生"], "o_en": ["Wong Yi", "Jin Yong", "Gu Long", "Liang Yusheng"], "a": 0, "e_zh": "《尋秦記》改編自黃易的同名小說。", "e_en": "A Step into the Past is adapted from Wong Yi's novel of the same name.", "d": 1},
            {"q_zh": "古天樂與劉德華合演的《拆彈專家2》（2020）中，他飾演什麼角色？", "q_en": "What role does Louis Koo play in 'Shock Wave 2' (2020)?", "o_zh": ["恐怖分子頭目", "拆彈專家", "警察", "卧底"], "o_en": ["Terrorist leader", "Bomb disposal expert", "Police officer", "Undercover"], "a": 0, "e_zh": "古天樂飾演恐怖分子頭目。", "e_en": "Louis Koo plays a terrorist leader.", "d": 1},
            {"q_zh": "古天樂在哪一年擔任香港演藝人協會會長？", "q_en": "In which year did Louis Koo become president of the HKAPA?", "o_zh": ["2016年", "2018年", "2019年", "2020年"], "o_en": ["2016", "2018", "2019", "2020"], "a": 2, "e_zh": "古天樂2019年當選香港演藝人協會會長。", "e_en": "Louis Koo was elected president of the HKAPA in 2019.", "d": 2},
            {"q_zh": "古天樂的膚色為何特別黑？", "q_en": "Why is Louis Koo's skin particularly dark?", "o_zh": ["故意曬黑", "天生膚色", "化妝效果", "長期在內地拍戲曬黑"], "o_en": ["Intentionally tanned", "Natural skin tone", "Makeup effect", "Tanned from filming in mainland China"], "a": 0, "e_zh": "古天樂為了擺脫「白面書生」形象而故意曬黑。", "e_en": "Louis Koo intentionally tanned to shed his 'pale scholar' image.", "d": 1},
            {"q_zh": "《九龍城寨之圍城》（2024）中，古天樂飾演誰？", "q_en": "Who does Louis Koo play in 'Twilight of the Warriors: Walled In' (2024)?", "o_zh": ["龍捲風", "陳洛軍", "信一", "四仔"], "o_en": ["Tornado", "Chen Lo-kwan", "Yan Yi", "Four"], "a": 0, "e_zh": "古天樂飾演九龍城寨的龍捲風。", "e_en": "Louis Koo plays Tornado, a leader in Kowloon Walled City.", "d": 1},
            {"q_zh": "古天樂的生日是哪一天？", "q_en": "When is Louis Koo's birthday?", "o_zh": ["9月21日", "10月21日", "11月21日", "12月21日"], "o_en": ["September 21", "October 21", "November 21", "December 21"], "a": 1, "e_zh": "古天樂生日是10月21日。", "e_en": "Louis Koo's birthday is October 21.", "d": 1},
            {"q_zh": "古天樂在哪一年出生？", "q_en": "In which year was Louis Koo born?", "o_zh": ["1968年", "1970年", "1972年", "1974年"], "o_en": ["1968", "1970", "1972", "1974"], "a": 1, "e_zh": "古天樂1970年10月21日出生。", "e_en": "Louis Koo was born on October 21, 1970.", "d": 1},
            {"q_zh": "古天樂主演的《明日戰記》（2022）是什麼類型的電影？", "q_en": "What genre is 'Warriors of Future' (2022) starring Louis Koo?", "o_zh": ["科幻動作片", "愛情片", "喜劇片", "文藝片"], "o_en": ["Sci-fi action", "Romance", "Comedy", "Drama"], "a": 0, "e_zh": "《明日戰記》是香港首部大型科幻動作片。", "e_en": "Warriors of Future is Hong Kong's first major sci-fi action film.", "d": 1},
            {"q_zh": "《竊聽風雲》系列中，古天樂飾演什麼職業？", "q_en": "What is Louis Koo's profession in the 'Overheard' series?", "o_zh": ["商業罪案調查科探員", "廉政公署調查員", "保安局局長", "金融分析師"], "o_en": ["Commercial Crime Bureau officer", "ICAC investigator", "Security Bureau chief", "Financial analyst"], "a": 0, "e_zh": "古天樂在《竊聽風雲》中飾演商業罪案調查科探員。", "e_en": "Louis Koo plays a Commercial Crime Bureau officer in 'Overheard'.", "d": 1},
            {"q_zh": "古天樂是哪一年加入TVB的？", "q_en": "In which year did Louis Koo join TVB?", "o_zh": ["1991年", "1993年", "1995年", "1997年"], "o_en": ["1991", "1993", "1995", "1997"], "a": 1, "e_zh": "古天樂1993年加入TVB。", "e_en": "Louis Koo joined TVB in 1993.", "d": 1},
            {"q_zh": "古天樂與張家輝合演的電影中，以下哪部最受好評？", "q_en": "Which film co-starring Louis Koo and Nick Cheung received the best reviews?", "o_zh": ["《掃毒》", "《使徒行者》", "《犯罪現場》", "《P風暴》"], "o_en": ["The White Storm", "Line Walker", "A Witness Out of the Blue", "P Storm"], "a": 0, "e_zh": "《掃毒》（2013）是兩人合作最受好評的電影之一。", "e_en": "The White Storm (2013) is one of their most acclaimed collaborations.", "d": 1},
        ]
    },
    "fat_choi": {
        "name": "嚦咕嚦咕新年財",
        "file": "fat_choi",
        "emoji": "🀄",
        "color": "#f39c12",
        "questions": [
            {"q_zh": "《嚦咕嚦咕新年財》（2000）的導演是誰？", "q_en": "Who directed 'Fat Choi Spirit' (2000)?", "o_zh": ["韋家輝", "杜琪峰", "劉偉強", "陳慶嘉"], "o_en": ["Wai Ka-fai", "Johnnie To", "Andrew Lau", "Chan Hing-ka"], "a": 0, "e_zh": "《嚦咕嚦咕新年財》由韋家輝執導。", "e_en": "Fat Choi Spirit was directed by Wai Ka-fai.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，劉德華飾演的角色叫什麼？", "q_en": "What is Andy Lau's character's name in 'Fat Choi Spirit'?", "o_zh": ["Andy", "阿財", "華仔", "賭神"], "o_en": ["Andy", "Ah Choi", "Wah Zai", "God of Gamblers"], "a": 0, "e_zh": "劉德華飾演的角色直接叫Andy。", "e_en": "Andy Lau's character is simply named Andy.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，梁詠琪飾演什麼角色？", "q_en": "What role does Gigi Leung play in 'Fat Choi Spirit'?", "o_zh": ["Joker", "Queen", "阿琪", "小美"], "o_en": ["Joker", "Queen", "Ah Kei", "Siu Mei"], "a": 0, "e_zh": "梁詠琪飾演Joker，一個樂天知命的女孩。", "e_en": "Gigi Leung plays Joker, an optimistic girl.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，古天樂飾演的角色有什麼特點？", "q_en": "What is special about Louis Koo's character in 'Fat Choi Spirit'?", "o_zh": ["經常輸錢的麻將高手", "黑幫老大", "警察", "醫生"], "o_en": ["A mahjong expert who often loses", "Triad boss", "Police officer", "Doctor"], "a": 0, "e_zh": "古天樂飾演一個自稱麻將高手但經常輸錢的角色。", "e_en": "Louis Koo plays a self-proclaimed mahjong expert who keeps losing.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》是什麼類型的電影？", "q_en": "What genre is 'Fat Choi Spirit'?", "o_zh": ["賀歲喜劇", "動作片", "恐怖片", "文藝片"], "o_en": ["Lunar New Year comedy", "Action", "Horror", "Drama"], "a": 0, "e_zh": "《嚦咕嚦咕新年財》是一部賀歲喜劇電影。", "e_en": "Fat Choi Spirit is a Lunar New Year comedy film.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，應採兒飾演什麼角色？", "q_en": "What role does Cherrie Ying play in 'Fat Choi Spirit'?", "o_zh": ["阿Sa", "Joker的朋友", "賭場荷官", "護士"], "o_en": ["Ah Sa", "Joker's friend", "Casino dealer", "Nurse"], "a": 0, "e_zh": "應採兒飾演阿Sa。", "e_en": "Cherrie Ying plays Ah Sa.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》的片名「嚦咕嚦咕」是什麼意思？", "q_en": "What does 'Lek Gu Lek Gu' in the title mean?", "o_zh": ["麻將術語，摸牌的聲音", "恭喜發財", "新年快樂", "打牌的動作"], "o_en": ["Mahjong term, sound of drawing tiles", "Congratulations and prosperity", "Happy New Year", "Action of playing mahjong"], "a": 0, "e_zh": "「嚦咕嚦咕」是打麻將時摸牌的象聲詞。", "e_en": "'Lek Gu Lek Gu' is an onomatopoeia for drawing mahjong tiles.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》是哪一年的賀歲檔上映？", "q_en": "In which Lunar New Year was 'Fat Choi Spirit' released?", "o_zh": ["2000年（龍年）", "2001年（蛇年）", "2002年（馬年）", "2003年（羊年）"], "o_en": ["2000 (Year of Dragon)", "2001 (Year of Snake)", "2002 (Year of Horse)", "2003 (Year of Goat)"], "a": 1, "e_zh": "《嚦咕嚦咕新年財》於2001年蛇年賀歲檔上映。", "e_en": "Fat Choi Spirit was released during the 2001 Year of Snake Lunar New Year season.", "d": 2},
            {"q_zh": "《嚦咕嚦咕新年財》中，劉德華的角色有什麼口頭禪？", "q_en": "What is Andy Lau's character's catchphrase in 'Fat Choi Spirit'?", "o_zh": ["「我係賭神」", "「新年快樂」", "「恭喜發財」", "「打牌要有牌品」"], "o_en": ["I am the God of Gamblers", "Happy New Kong", "Congratulations and prosperity", "You need character to play mahjong"], "a": 2, "e_zh": "劉德華的角色經常說「恭喜發財」。", "e_en": "Andy Lau's character often says 'Congratulations and prosperity'.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》與哪部電影系列有關？", "q_en": "Which film series is 'Fat Choi Spirit' related to?", "o_zh": ["《賭神》系列", "《賭聖》系列", "《賭俠》系列", "《千王之王》系列"], "o_en": ["God of Gamblers series", "All for the Winner series", "God of Gamblers II series", "King of Gamblers series"], "a": 0, "e_zh": "《嚦咕嚦咕新年財》是《賭神》系列的衍生作品。", "e_en": "Fat Choi Spirit is a spin-off of the God of Gamblers series.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，哪位演員飾演「賭神」高進？", "q_en": "Which actor plays 'God of Gamblers' Ko Chun in 'Fat Choi Spirit'?", "o_zh": ["劉德華", "周潤發", "周星馳", "梁朝偉"], "o_en": ["Andy Lau", "Chow Yun-fat", "Stephen Chow", "Tony Leung"], "a": 1, "e_zh": "周潤發飾演「賭神」高進。", "e_en": "Chow Yun-fat plays 'God of Gamblers' Ko Chun.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，麻將場景佔電影多少比例？", "q_en": "Approximately what percentage of 'Fat Choi Spirit' features mahjong scenes?", "o_zh": ["約30%", "約50%", "約70%", "約90%"], "o_en": ["About 30%", "About 50%", "About 70%", "About 90%"], "a": 2, "e_zh": "電影大部分場景都圍繞打麻將展開，約佔70%。", "e_en": "Most scenes revolve around mahjong, approximately 70%.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》的主題曲由誰主唱？", "q_en": "Who sings the theme song of 'Fat Choi Spirit'?", "o_zh": ["劉德華", "梁詠琪", "古天樂", "應採兒"], "o_en": ["Andy Lau", "Gigi Leung", "Louis Koo", "Cherrie Ying"], "a": 0, "e_zh": "主題曲由劉德華主唱。", "e_en": "The theme song is sung by Andy Lau.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，Joker的職業是什麼？", "q_en": "What is Joker's profession in 'Fat Choi Spirit'?", "o_zh": ["護士", "空姐", "教師", "秘書"], "o_en": ["Nurse", "Flight attendant", "Teacher", "Secretary"], "a": 0, "e_zh": "Joker的職業是護士。", "e_en": "Joker works as a nurse.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，古天樂的角色叫什麼？", "q_en": "What is Louis Koo's character's name in 'Fat Choi Spirit'?", "o_zh": ["阿Mo", "阿財", "阿華", "阿強"], "o_en": ["Ah Mo", "Ah Choi", "Ah Wah", "Ah Keung"], "a": 0, "e_zh": "古天樂飾演阿Mo。", "e_en": "Louis Koo plays Ah Mo.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》的票房成績如何？", "q_en": "How was the box office performance of 'Fat Choi Spirit'?", "o_zh": ["非常成功，是當年賀歲檔冠軍", "一般", "票房失利", "不詳"], "o_en": ["Very successful, top Lunar New Year film", "Average", "Box office flop", "Unknown"], "a": 0, "e_zh": "《嚦咕嚦咕新年財》票房非常成功，是2001年賀歲檔票房冠軍。", "e_en": "Fat Choi Spirit was very successful, topping the 2001 Lunar New Year box office.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，劉德華的角色最終贏了什麼？", "q_en": "What does Andy Lau's character ultimately win in 'Fat Choi Spirit'?", "o_zh": ["麻將比賽", "愛情", "財富", "以上皆是"], "o_en": ["Mahjong tournament", "Love", "Wealth", "All of the above"], "a": 3, "e_zh": "劉德華的角色最終贏得了麻將比賽、愛情和財富。", "e_en": "Andy Lau's character ultimately wins the mahjong tournament, love, and wealth.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》續集叫什麼？", "q_en": "What is the sequel to 'Fat Choi Spirit' called?", "o_zh": ["《嚦咕嚦咕新年財2》", "《嚦咕嚦咕2》", "沒有續集", "《賭神5》"], "o_en": ["Fat Choi Spirit 2", "Lek Gu Lek Gu 2", "No sequel", "God of Gamblers 5"], "a": 2, "e_zh": "《嚦咕嚦咕新年財》沒有正式續集。", "e_en": "Fat Choi Spirit does not have an official sequel.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，劉德華的角色是什麼身份？", "q_en": "What is Andy Lau's character's identity in 'Fat Choi Spirit'?", "o_zh": ["退休賭神", "職業賭徒", "麻將教練", "賭場老闆"], "o_en": ["Retired God of Gamblers", "Professional gambler", "Mahjong coach", "Casino owner"], "a": 0, "e_zh": "劉德華飾演退休的賭神。", "e_en": "Andy Lau plays a retired God of Gamblers.", "d": 1},
            {"q_zh": "《嚦咕嚦咕新年財》中，最經典的麻將場面是什麼？", "q_en": "What is the most classic mahjong scene in 'Fat Choi Spirit'?", "o_zh": ["最後決賽", "劉德華與梁詠琪的對決", "古天樂連輸十八圈", "周潤發出場"], "o_en": ["The final match", "Andy Lau vs Gigi Leung", "Louis Koo losing 18 rounds", "Chow Yun-fat's appearance"], "a": 0, "e_zh": "最後決賽的麻將場面最為經典。", "e_en": "The final match mahjong scene is the most classic.", "d": 1},
        ]
    },
}

def generate_series_questions(series_name, data):
    """Generate full question set from series data."""
    return data["questions"]

def main():
    os.makedirs(BASE / "movies/topics", exist_ok=True)
    os.makedirs(BASE / "millionaire/topics", exist_ok=True)
    
    # ── 周星馳系列 ──
    write_questions(BASE / "movies/topics/stephen_chow.json", STEPHEN_CHOW)
    print(f"✅ 周星馳系列: {len(STEPHEN_CHOW)} questions")
    
    # ── 其他系列 ──
    for key, data in SERIES_DATA.items():
        questions = generate_series_questions(key, data)
        filepath = BASE / f"movies/topics/{data['file']}.json"
        write_questions(filepath, questions)
        print(f"✅ {data['name']}: {len(questions)} questions")
    
    # ── 百萬富翁 ──
    write_questions(BASE / "millionaire/topics/millionaire.json", MILLIONAIRE_Q)
    print(f"✅ 百萬富翁: {len(MILLIONAIRE_Q)} questions")
    
    # ── Generate topic index files ──
    movie_topics = {
        "topics": [
            {"id": "stephen_chow", "name_zh": "周星馳系列", "name_en": "Stephen Chow Series", "emoji": "😂", "file": "stephen_chow.json"},
            {"id": "andy_lau", "name_zh": "劉德華系列", "name_en": "Andy Lau Series", "emoji": "🎤", "file": "andy_lau.json"},
            {"id": "tony_leung", "name_zh": "梁朝偉系列", "name_en": "Tony Leung Series", "emoji": "🎭", "file": "tony_leung.json"},
            {"id": "louis_koo", "name_zh": "古天樂系列", "name_en": "Louis Koo Series", "emoji": "😎", "file": "louis_koo.json"},
            {"id": "fat_choi", "name_zh": "嚦咕嚦咕新年財", "name_en": "Fat Choi Spirit", "emoji": "🀄", "file": "fat_choi.json"},
        ]
    }
    write_questions(BASE / "movies/topics/index.json", movie_topics)
    
    millionaire_topics = {
        "topics": [
            {"id": "millionaire", "name_zh": "百萬富翁", "name_en": "Who Wants to Be a Millionaire", "emoji": "💰", "file": "millionaire.json"},
        ]
    }
    write_questions(BASE / "millionaire/topics/index.json", millionaire_topics)
    
    print("\n✅ All done!")

# ── 百萬富翁題目 ──
MILLIONAIRE_Q = [
    {"question_zh": "「百萬富翁」遊戲節目原創於哪個國家？", "question_en": "Which country did 'Who Wants to Be a Millionaire' originate from?", "options_zh": ["美國", "英國", "日本", "香港"], "options_en": ["USA", "UK", "Japan", "Hong Kong"], "answer": 1, "explanation_zh": "百萬富翁原創於英國，1998年首播。", "explanation_en": "Millionaire originated in the UK, first airing in 1998.", "difficulty": 1},
    {"question_zh": "香港版「百萬富翁」的主持人是誰？", "question_en": "Who hosts the Hong Kong version of 'Who Wants to Be a Millionaire'?", "options_zh": ["陳啟泰", "曾志偉", "鄭裕玲", "何守信"], "options_en": ["Kenneth Chan", "Eric Tsang", "DoDo Cheng", "Ho Sau-sun"], "answer": 0, "explanation_zh": "陳啟泰是香港版百萬富翁的主持人。", "explanation_en": "Kenneth Chan hosts the Hong Kong version of Millionaire.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，「問觀眾」這條生命線的規則是什麼？", "question_en": "What is the rule of the 'Ask the Audience' lifeline in Millionaire?", "options_zh": ["觀眾投票顯示百分比", "觀眾直接給答案", "觀眾可以討論", "觀眾舉手投票"], "options_en": ["Audience votes show percentages", "Audience gives answer directly", "Audience can discuss", "Audience raises hands to vote"], "answer": 0, "explanation_zh": "問觀眾時，現場觀眾會用電子儀器投票，屏幕上顯示各選項的百分比。", "explanation_en": "Ask the Audience shows live audience voting percentages on screen.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，共有幾條生命線？", "question_en": "How many lifelines are there in Millionaire?", "options_zh": ["2條", "3條", "4條", "5條"], "options_en": ["2", "3", "4", "5"], "answer": 1, "explanation_zh": "標準版有3條生命線：問觀眾、打電話問朋友、50:50。", "explanation_en": "The standard version has 3 lifelines: Ask the Audience, Phone a Friend, and 50:50.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，「50:50」生命線的功能是什麼？", "question_en": "What does the '50:50' lifeline do in Millionaire?", "options_zh": ["消除兩個錯誤答案", "獲得雙倍獎金", "多一次機會", "跳過問題"], "options_en": ["Eliminate two wrong answers", "Double the prize money", "Get an extra chance", "Skip the question"], "answer": 0, "explanation_zh": "50:50會隨機消除兩個錯誤答案，只留下正確答案和一個錯誤答案。", "explanation_en": "50:50 randomly eliminates two wrong answers, leaving the correct answer and one wrong answer.", "difficulty": 1},
    {"question_zh": "香港版百萬富翁的最高獎金是多少？", "question_en": "What is the top prize in the Hong Kong version of Millionaire?", "options_zh": ["100萬港元", "200萬港元", "500萬港元", "1000萬港元"], "options_en": ["HK$1 million", "HK$2 million", "HK$5 million", "HK$10 million"], "answer": 0, "explanation_zh": "香港版百萬富翁的最高獎金是100萬港元。", "explanation_en": "The top prize in the Hong Kong version is HK$1 million.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，獎金階梯的第一個「安全網」在哪一題？", "question_en": "Where is the first 'safety net' on the prize ladder in Millionaire?", "options_zh": ["第5題", "第10題", "第15題", "第3題"], "options_en": ["Question 5", "Question 10", "Question 15", "Question 3"], "answer": 0, "explanation_zh": "第5題是第一個安全網，答對後至少可以帶走這個金額。", "explanation_en": "Question 5 is the first safety net - you keep at least this amount if you answer correctly.", "difficulty": 1},
    {"question_zh": "百萬富翁的英文名稱是什麼？", "question_en": "What is the English name of '百萬富翁'?", "options_zh": ["Who Wants to Be a Millionaire", "Are You a Millionaire", "Million Dollar Quiz", "The Money Show"], "options_en": ["Who Wants to Be a Millionaire", "Are You a Millionaire", "Million Dollar Quiz", "The Money Show"], "answer": 0, "explanation_zh": "百萬富翁的英文名稱是 'Who Wants to Be a Millionaire'。", "explanation_en": "The English name is 'Who Wants to Be a Millionaire'.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，「打電話問朋友」這條生命線的時間限制是多少？", "question_en": "How long do you have for the 'Phone a Friend' lifeline in Millionaire?", "options_zh": ["30秒", "60秒", "90秒", "120秒"], "options_en": ["30 seconds", "60 seconds", "90 seconds", "120 seconds"], "answer": 0, "explanation_zh": "打電話問朋友的時間限制是30秒。", "explanation_en": "Phone a Friend has a 30-second time limit.", "difficulty": 1},
    {"question_zh": "電影《一百萬零一夜》（Slumdog Millionaire）講述的是哪個國家的百萬富翁？", "question_en": "Which country's Millionaire is depicted in 'Slumdog Millionaire'?", "options_zh": ["印度", "巴基斯坦", "孟加拉", "斯里蘭卡"], "options_en": ["India", "Pakistan", "Bangladesh", "Sri Lanka"], "answer": 0, "explanation_zh": "《一百萬零一夜》講述印度版百萬富翁的故事。", "explanation_en": "Slumdog Millionaire tells the story of the Indian version of Millionaire.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，答錯問題會怎樣？", "question_en": "What happens if you answer a question wrong in Millionaire?", "options_zh": ["跌回上一個安全網的金額", "失去所有獎金", "可以重來", "扣分"], "options_en": ["Drop to the last safety net amount", "Lose all winnings", "Can retry", "Penalty points"], "answer": 0, "explanation_zh": "答錯後會跌回上一個安全網的金額（如第5題或第10題的獎金）。", "explanation_en": "You drop to the last safety net amount (prize at question 5 or 10).", "difficulty": 1},
    {"question_zh": "百萬富翁的原版英國節目首播於哪一年？", "question_en": "In which year did the original UK version of Millionaire first air?", "options_zh": ["1996年", "1998年", "2000年", "2002年"], "options_en": ["1996", "1998", "2000", "2002"], "answer": 1, "explanation_zh": "英國版百萬富翁於1998年9月4日首播。", "explanation_en": "The UK version first aired on September 4, 1998.", "difficulty": 1},
    {"question_zh": "香港版百萬富翁於哪一年首播？", "question_en": "In which year did the Hong Kong version of Millionaire first air?", "options_zh": ["2000年", "2001年", "2002年", "2003年"], "options_en": ["2000", "2001", "2002", "2003"], "answer": 1, "explanation_zh": "香港版百萬富翁於2001年首播。", "explanation_en": "The Hong Kong version first aired in 2001.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，共需要回答多少條問題才能贏得最高獎金？", "question_en": "How many questions must you answer correctly to win the top prize in Millionaire?", "options_zh": ["10條", "12條", "15條", "20條"], "options_en": ["10", "12", "15", "20"], "answer": 2, "explanation_zh": "需要連續答對15條問題才能贏得最高獎金。", "explanation_en": "You must answer 15 questions correctly in a row to win the top prize.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，「Double Dip」是什麼功能？", "question_en": "What is the 'Double Dip' feature in Millionaire?", "options_zh": ["可以選兩個答案", "可以獲得雙倍獎金", "答錯可以再試一次", "可以跳過問題"], "options_en": ["Can choose two answers", "Double prize money", "Can try again if wrong", "Can skip the question"], "answer": 0, "explanation_zh": "Double Dip讓參賽者可以選兩個答案，但如果兩個都錯就出局。", "explanation_en": "Double Dip allows contestants to choose two answers, but if both are wrong, they're out.", "difficulty": 2},
    {"question_zh": "百萬富翁遊戲中，「Ask the Expert」是什麼生命線？", "question_en": "What is the 'Ask the Expert' lifeline in Millionaire?", "options_zh": ["問場外專家", "問主持人", "問其他參賽者", "問電腦"], "options_en": ["Ask an off-screen expert", "Ask the host", "Ask other contestants", "Ask the computer"], "answer": 0, "explanation_zh": "Ask the Expert是後期新增的生命線，可以問場外專家意見。", "explanation_en": "Ask the Expert is a later-added lifeline that lets you consult an off-screen expert.", "difficulty": 2},
    {"question_zh": "百萬富翁遊戲的問題難度如何遞進？", "question_en": "How does the difficulty progress in Millionaire?", "options_zh": ["由易到難", "隨機難度", "全部相同", "由難到易"], "options_en": ["Easy to hard", "Random difficulty", "All the same", "Hard to easy"], "answer": 0, "explanation_zh": "問題由第1題的簡單逐漸遞進到第15題的極難。", "explanation_en": "Questions progress from easy (Q1) to extremely difficult (Q15).", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，如果參賽者不確定答案，可以怎樣做？", "question_en": "What can a contestant do if unsure of the answer in Millionaire?", "options_zh": ["使用生命線或放棄", "問現場觀眾", "以上皆可", "直接猜答案"], "options_en": ["Use a lifeline or quit", "Ask the audience", "All of the above", "Guess the answer"], "answer": 2, "explanation_zh": "參賽者可以使用生命線、放棄帶走獎金，或者直接猜答案。", "explanation_en": "Contestants can use lifelines, quit and take winnings, or guess.", "difficulty": 1},
    {"question_zh": "香港版百萬富翁曾在哪個電視台播出？", "question_en": "Which TV station aired the Hong Kong version of Millionaire?", "options_zh": ["亞洲電視（ATV）", "無綫電視（TVB）", "有線電視", "ViuTV"], "options_en": ["ATV", "TVB", "Cable TV", "ViuTV"], "answer": 0, "explanation_zh": "香港版百萬富翁在亞洲電視播出。", "explanation_en": "The Hong Kong version of Millionaire aired on ATV.", "difficulty": 1},
    {"question_zh": "百萬富翁遊戲中，獎金階梯的最高三題獎金分別是多少？（以港版為例）", "question_en": "What are the top three prize amounts in the HK version of Millionaire?", "options_zh": ["$50萬、$75萬、$100萬", "$25萬、$50萬、$100萬", "$50萬、$80萬、$100萬", "$30萬、$60萬、$100萬"], "options_en": ["$500K, $750K, $1M", "$250K, $500K, $1M", "$500K, $800K, $1M", "$300K, $600K, $1M"], "answer": 0, "explanation_zh": "港版獎金階梯最後三題為$50萬、$75萬、$100萬。", "explanation_en": "The HK version's top three prizes are $500K, $750K, and $1M.", "difficulty": 2},
]

if __name__ == '__main__':
    main()
