#!/usr/bin/env python3
"""Generate Scrum exam questions - 10,000 total + HTML quiz interface"""
import json, os

scr_topics = {
    "Scrum Framework": {
        "zh": "Scrum 框架",
        "questions": [
            ("According to the Scrum Guide 2020, the Sprint is:", "根據2020年Scrum指南，Sprint是：", ["A time-box of one month or less during which a 'Done' product Increment is created", "A flexible period with no fixed end date", "A planning phase that lasts one week", "Only for software development"], ["一個月或更短的時間盒，期間創建「完成」的產品增量", "沒有固定結束日期的靈活期間", "持續一週的規劃階段", "僅用於軟件開發"], 0, "The Scrum Guide 2020 defines the Sprint as a time-box of one month or less that creates a usable product Increment. All other Scrum events occur within the Sprint.", "2020年Scrum指南將Sprint定義為一個月或更短的時間盒，創建可用的產品增量。所有其他Scrum事件在Sprint內進行。"),
            ("The maximum duration of a Sprint is:", "Sprint的最長持續時間為：", ["One month", "Two weeks", "Three weeks", "No maximum"], ["一個月", "兩週", "三週", "無上限"], 0, "Sprints are limited to one calendar month. Shorter Sprints can be used to generate more learning cycles and limit risk.", "Sprint限制為一個日曆月。較短的Sprint可用於產生更多學習週期並限制風險。"),
            ("During the Sprint, what happens if the Sprint Goal becomes obsolete?", "在Sprint期間，如果Sprint目標變得過時會怎樣？", ["The Product Owner can cancel the Sprint", "The Scrum Master cancels the Sprint", "The Developers cancel the Sprint", "The Sprint continues regardless"], ["產品負責人可以取消Sprint", "Scrum Master取消Sprint", "開發人員取消Sprint", "Sprint無論如何繼續"], 0, "A Sprint can be cancelled by the Product Owner if the Sprint Goal becomes obsolete. Only the PO has this authority. Remaining completed items are reviewed.", "如果Sprint目標變得過時，產品負責人可以取消Sprint。只有PO有此權限。剩餘已完成項目會被審查。"),
            ("Sprint Planning addresses all of the following topics EXCEPT:", "Sprint Planning處理以下所有主題，除了：", ["Assigning tasks to individual Developers", "Why is this Sprint valuable?", "What can be done this Sprint?", "How will the chosen work get done?"], ["將任務分配給個別開發人員", "這個Sprint為什麼有價值？", "這個Sprint可以做什麼？", "所選工作如何完成？"], 0, "Sprint Planning addresses three topics: 1) Why is this Sprint valuable? 2) What can be done? 3) How will the work get done? Task assignment is up to Developers.", "Sprint Planning處理三個主題：1）這個Sprint為什麼有價值？2）可以做什麼？3）工作如何完成？任務分配由開發人員自行決定。"),
            ("The Sprint Goal is crafted during:", "Sprint目標在以下時間制定：", ["Sprint Planning", "Sprint Review", "Sprint Retrospective", "Daily Scrum"], ["Sprint Planning", "Sprint Review", "Sprint Retrospective", "每日Scrum"], 0, "The Sprint Goal is crafted during Sprint Planning as part of addressing why the Sprint is valuable. It provides guidance to the Developers on why they are building the Increment.", "Sprint目標在Sprint Planning期間制定，作為解決Sprint為什麼有價值的一部分。它為開發人員提供構建增量的指導。"),
            ("The Daily Scrum is a:", "每日Scrum是一個：", ["15-minute event for Developers to inspect progress toward the Sprint Goal", "1-hour status meeting for the whole organization", "Planning session for the next Sprint", "Review of the Product Backlog"], ["15分鐘的事件，開發人員檢查朝著Sprint目標的進展", "整個組織的1小時狀態會議", "下一個Sprint的規劃會議", "產品待辦列表的審查"], 0, "Daily Scrum is a 15-minute time-boxed event for Developers. It's not a status meeting but an opportunity to inspect progress and adapt the Sprint Backlog.", "每日Scrum是開發人員的15分鐘時間盒事件。它不是狀態會議，而是檢查進展和調整Sprint Backlog的機會。"),
            ("The Sprint Review is held:", "Sprint Review在以下時間舉行：", ["At the end of the Sprint to inspect the Increment and adapt the Product Backlog", "At the beginning of each Sprint", "Only when requested by stakeholders", "Every day during the Sprint"], ["在Sprint結束時檢查增量並調整產品待辦列表", "在每個Sprint開始時", "僅在利害關係人要求時", "Sprint期間每天"], 0, "Sprint Review is held at the end of the Sprint. Its purpose is to inspect the Increment and adapt the Product Backlog if needed. It's a working session, not a presentation.", "Sprint Review在Sprint結束時舉行。其目的是檢查增量並在需要時調整產品待辦列表。它是工作會議，而非演示。"),
            ("The Sprint Retrospective focuses on:", "Sprint Retrospective關注：", ["Improving the team's process, tools, and Definition of Done", "Reviewing the product Increment", "Planning the next Sprint's work", "Updating stakeholders on progress"], ["改進團隊的流程、工具和完成的定義", "審查產品增量", "規劃下一個Sprint的工作", "向利害關係人更新進展"], 0, "Sprint Retrospective plans ways to increase quality and effectiveness. The Scrum Team inspects how the last Sprint went regarding individuals, interactions, processes, and tools.", "Sprint Retrospective計劃提高質量和效率的方法。Scrum團隊檢視上一個Sprint在個人、互動、流程和工具方面的表現。"),
            ("The output of Sprint Planning includes:", "Sprint Planning的產出包括：", ["The Sprint Goal and the Sprint Backlog", "The Product Backlog", "The Increment", "The Retrospective agenda"], ["Sprint目標和Sprint Backlog", "產品待辦列表", "增量", "Retrospective議程"], 0, "Sprint Planning produces: 1) the Sprint Goal (why), 2) selected Product Backlog items (what), 3) a plan for delivering them as the Increment (how) = Sprint Backlog.", "Sprint Planning產生：1）Sprint目標（為什麼），2）選定的產品待辦列表項目（什麼），3）將其作為增量交付的計劃（如何）= Sprint Backlog。"),
            ("What is the maximum length of the Sprint Retrospective?", "Sprint Retrospective的最長時間為？", ["3 hours for a one-month Sprint", "4 hours", "1 hour", "30 minutes"], ["一個月Sprint為3小時", "4小時", "1小時", "30分鐘"], 0, "Sprint Retrospective time-box: 3 hours for one-month Sprints, shorter for shorter Sprints. It occurs after the Sprint Review and before the next Sprint Planning.", "Sprint Retrospective時間盒：一個月Sprint為3小時，較短的Sprint則更短。它在Sprint Review之後、下一個Sprint Planning之前進行。"),
        ]
    },
    "Scrum Roles": {
        "zh": "Scrum 角色",
        "questions": [
            ("The Scrum Team consists of:", "Scrum團隊由以下組成：", ["Product Owner, Scrum Master, and Developers", "Project Manager, Business Analyst, and Developers", "Product Owner, Project Manager, and Testers", "Only Developers"], ["產品負責人、Scrum Master和開發人員", "項目經理、業務分析師和開發人員", "產品負責人、項目經理和測試人員", "僅開發人員"], 0, "The Scrum Guide 2020 defines the Scrum Team as: Product Owner + Scrum Master + Developers. No sub-teams or hierarchies.", "2020年Scrum指南將Scrum團隊定義為：產品負責人 + Scrum Master + 開發人員。無子團隊或層級結構。"),
            ("The Product Owner is accountable for:", "產品負責人對以下負責：", ["Maximizing the value of the product through effective Product Backlog management", "Writing all user stories", "Managing the Developers", "All technical decisions"], ["通過有效的產品待辦列表管理最大化產品價值", "撰寫所有用戶故事", "管理開發人員", "所有技術決策"], 0, "The PO is accountable for maximizing product value through ordering the Product Backlog, clearly communicating items, and ensuring the team understands items to the level needed.", "PO通過排列產品待辦列表優先順序、清晰溝通項目以及確保團隊理解項目至所需程度來最大化產品價值。"),
            ("The Scrum Master is accountable for:", "Scrum Master對以下負責：", ["Establishing Scrum as defined in the Scrum Guide and helping the team be effective", "Writing code for the team", "Assigning tasks to Developers", "Reporting to management"], ["按照Scrum指南建立Scrum並幫助團隊有效運作", "為團隊編寫代碼", "將任務分配給開發人員", "向管理層匯報"], 0, "The SM serves the PO, Developers, and organization by coaching, facilitating, removing impediments, and ensuring Scrum events are productive and time-boxed.", "SM通過教練、引導、消除障礙並確保Scrum事件富有成效和遵守時間盒來服務PO、開發人員和組織。"),
            ("In Scrum, the Developers are accountable for:", "在Scrum中，開發人員對以下負責：", ["Creating a plan for the Sprint, the Sprint Backlog, instilling quality, and adapting their plan daily", "Only coding", "Testing only", "Only following the PO's instructions"], ["創建Sprint計劃、Sprint Backlog、灌輸質量意識並每天調整計劃", "僅編碼", "僅測試", "僅遵循PO的指示"], 0, "Developers are accountable for: creating Sprint Backlog, instilling quality via Definition of Done, adapting plan daily, and holding each other accountable.", "開發人員負責：創建Sprint Backlog、通過完成的定義灌輸質量、每天調整計劃並互相問責。"),
            ("The Scrum Team size should be:", "Scrum團隊規模應為：", ["Small enough to remain nimble (typically 10 or fewer)", "At least 20 people", "Exactly 7 people", "No limit"], ["足夠小以保持敏捷（通常10人或更少）", "至少20人", "恰好7人", "無限制"], 0, "The Scrum Guide recommends 10 or fewer people. Too few reduces interaction and productivity gains; too many increases complexity.", "Scrum指南建議10人或更少。太少會減少互動和生產力收益；太多會增加複雜性。"),
            ("Who is responsible for ordering the Product Backlog?", "誰負責排列產品待辦列表的優先順序？", ["The Product Owner", "The Scrum Master", "The Developers", "The stakeholders"], ["產品負責人", "Scrum Master", "開發人員", "利害關係人"], 0, "The Product Owner has sole accountability for ordering the Product Backlog to maximize value. They may delegate the work but remain accountable.", "產品負責人對排列產品待辦列表優先順序以最大化價值承擔唯一責任。可以委派工作但仍然負責。"),
            ("The Scrum Master serves the organization by:", "Scrum Master通過以下方式服務組織：", ["Leading, training, and coaching the organization in its Scrum adoption", "Firing underperforming team members", "Writing status reports for management", "Making all business decisions"], ["在組織採用Scrum的過程中領導、培訓和教練組織", "解僱表現不佳的團隊成員", "為管理層撰寫狀態報告", "做出所有業務決策"], 0, "SM serves the organization by: planning Scrum implementation, helping employees/stakeholders understand Scrum, causing change that increases productivity, and working with other SMs.", "SM通過以下方式服務組織：規劃Scrum實施、幫助員工/利害關係人理解Scrum、引發提高生產力的變革以及與其他SM合作。"),
            ("Can the Scrum Master also be a Developer on the same team?", "Scrum Master可以同時擔任同一團隊的開發人員嗎？", ["Yes, but it is not recommended as it may compromise effectiveness", "No, this is strictly forbidden", "Yes, this is the recommended approach", "Only for small teams"], ["可以，但不推薦，因為可能影響有效性", "不可以，這是嚴格禁止的", "可以，這是推薦的方法", "僅適用於小型團隊"], 0, "The Scrum Guide doesn't forbid it, but notes the focus on two very different accountabilities may reduce effectiveness in both areas. It's not recommended.", "Scrum指南不禁止，但指出專注於兩個非常不同的責任可能降低兩個領域的有效性。不推薦。"),
            ("Stakeholders in Scrum are:", "Scrum中的利害關係人是：", ["Anyone with a stake in the product who provides input but is not on the Scrum Team", "Only the Product Owner", "Only company executives", "Only end users"], ["對產品有利益關係、提供意見但不在Scrum團隊中的任何人", "僅產品負責人", "僅公司高管", "僅最終用戶"], 0, "Stakeholders include users, customers, sponsors, management, and anyone affected by or interested in the product. They interact primarily through Sprint Review.", "利害關係人包括用戶、客戶、贊助人、管理層以及受產品影響或對產品有興趣的任何人。主要通過Sprint Review互動。"),
            ("The Developers are:", "開發人員是：", ["The people in the Scrum Team committed to creating any aspect of a usable Increment each Sprint", "Only software programmers", "Only testers", "A separate department from the Scrum Team"], ["Scrum團隊中致力於每個Sprint創建可用增量任何方面的人員", "僅軟件程序員", "僅測試人員", "與Scrum團隊分開的部門"], 0, "Developers are the people in the Scrum Team who are committed to creating any aspect of a usable Increment each Sprint. They have all skills needed—no sub-teams.", "開發人員是Scrum團隊中致力於每個Sprint創建可用增量任何方面的人員。他們具備所需的所有技能——無子團隊。"),
        ]
    },
    "Scrum Artifacts": {
        "zh": "Scrum 工件",
        "questions": [
            ("The Product Backlog is:", "產品待辦列表是：", ["An ordered list of everything known to be needed in the product, the single source of requirements", "A fixed plan that cannot change", "Only a list of bugs", "A Gantt chart"], ["已知產品所需一切內容的有序列表，是需求的唯一來源", "不能更改的固定計劃", "僅錯誤列表", "甘特圖"], 0, "The Product Backlog is dynamic, constantly evolving to identify what the product needs. It's the single source of work for the Scrum Team.", "產品待辦列表是動態的，不斷演變以識別產品需求。它是Scrum團隊工作的唯一來源。"),
            ("The Sprint Backlog consists of:", "Sprint Backlog由以下組成：", ["The Sprint Goal, selected Product Backlog items, and an actionable plan for delivering the Increment", "All items in the Product Backlog", "Only the Sprint Goal", "A list of completed work"], ["Sprint目標、選定的產品待辦列表項目以及交付增量的可行動計劃", "產品待辦列表中的所有項目", "僅Sprint目標", "已完成工作的列表"], 0, "Sprint Backlog = Sprint Goal + selected PBIs + plan to deliver them as Increment. It's a real-time picture of the work Developers plan to accomplish.", "Sprint Backlog = Sprint目標 + 選定的PBI + 將其作為增量交付的計劃。它是開發人員計劃完成工作的實時圖片。"),
            ("The Increment is:", "增量是：", ["The sum of all Product Backlog items completed during a Sprint and all prior Sprints, meeting the Definition of Done", "Only the items completed in the current Sprint", "A prototype", "A draft version"], ["在當前Sprint和所有先前Sprint中完成的所有產品待辦列表項目的總和，符合完成的定義", "僅在當前Sprint中完成的項目", "原型", "草稿版本"], 0, "An Increment is a concrete stepping stone toward the Product Goal. Each Increment is additive and must work together. Multiple Increments can be created within a Sprint.", "增量是邁向產品目標的具體墊腳石。每個增量是累加的，必須協同工作。一個Sprint內可以創建多個增量。"),
            ("Each artifact in Scrum has a corresponding commitment. The commitment for the Product Backlog is:", "Scrum中的每個工件都有對應的承諾。產品待辦列表的承諾是：", ["The Product Goal", "The Sprint Goal", "The Definition of Done", "The Increment"], ["產品目標", "Sprint目標", "完成的定義", "增量"], 0, "Product Goal → Product Backlog commitment; Sprint Goal → Sprint Backlog commitment; Definition of Done → Increment commitment.", "產品目標 → 產品待辦列表承諾；Sprint目標 → Sprint Backlog承諾；完成的定義 → 增量承諾。"),
            ("The Definition of Done (DoD) is:", "完成的定義（DoD）是：", ["A formal description of the state of the Increment when it meets the quality measures required for the product", "A to-do list for Developers", "The Sprint Goal", "Only a test plan"], ["增量狀態的正式描述，當增量滿足產品所需的質量標準時", "開發人員的待辦事項列表", "Sprint目標", "僅測試計劃"], 0, "DoD is a quality standard. When a PBI meets the DoD, an Increment is born. It creates transparency about what state each item must be in to be considered complete.", "DoD是質量標準。當PBI符合DoD時，增量就誕生了。它為每個項目必須處於何種狀態才能被視為完成創造了透明度。"),
            ("Multiple Scrum Teams working on the same product should:", "多個Scrum團隊在同一產品上工作時應：", ["Share the same Product Goal and Definition of Done, but have separate Sprint Backlogs", "Have separate Product Backlogs", "Never communicate with each other", "Have one Sprint Backlog for all teams"], ["共享相同的產品目標和完成的定義，但有各自的Sprint Backlog", "有各自的產品待辦列表", "永遠不互相溝通", "所有團隊共用一個Sprint Backlog"], 0, "Multiple teams on one product share the same Product Backlog, Product Goal, and Definition of Done. Each team has its own Sprint Backlog.", "多個團隊在同一產品上工作時共享相同的產品待辦列表、產品目標和完成的定義。每個團隊有自己的Sprint Backlog。"),
            ("Product Backlog refinement is:", "產品待辦列表梳理是：", ["The act of breaking down and further defining items into smaller, more precise items", "Only re-ordering items", "A formal Scrum event", "Removing items from the backlog"], ["將項目分解並進一步定義為更小、更精確項目的行為", "僅重新排列項目", "正式的Scrum事件", "從待辦列表中移除項目"], 0, "Refinement involves adding details, estimates, and order to items. The Scrum Team decides how, when, and how much refinement is needed. It typically consumes ~10% of capacity.", "梳理涉及為項目添加詳細信息、估算和優先順序。Scrum團隊決定如何、何時以及需要多少梳理。通常消耗約10%的產能。"),
            ("If the Developers determine they have too much or too little work during the Sprint, they should:", "如果開發人員在Sprint期間確定工作量過多或過少，應：", ["Negotiate scope with the Product Owner without affecting the Sprint Goal", "Cancel the Sprint", "Add more work from the Product Backlog without consulting anyone", "Extend the Sprint duration"], ["與產品負責人協商範圍，不影響Sprint目標", "取消Sprint", "不經任何人同意從產品待辦列表添加更多工作", "延長Sprint持續時間"], 0, "Developers can negotiate scope with the PO as they learn more. The Sprint Goal cannot be compromised. If scope is removed, it goes back to the Product Backlog.", "開發人員可以在了解更多情況後與PO協商範圍。Sprint目標不能妥協。如果範圍被移除，它回到產品待辦列表。"),
            ("The Product Goal is:", "產品目標是：", ["The long-term objective for the Scrum Team, providing a target for planning", "The same as the Sprint Goal", "Set by the Scrum Master", "Only about revenue targets"], ["Scrum團隊的長期目標，為規劃提供目標", "與Sprint目標相同", "由Scrum Master設定", "僅關於收入目標"], 0, "Product Goal describes the future state of the product and serves as a target for the Scrum Team to plan against. Only one Product Goal at a time.", "產品目標描述產品的未來狀態，作為Scrum團隊規劃的目標。一次只有一個產品目標。"),
            ("An Increment cannot be released until:", "增量在以下情況之前不能發布：", ["There is no rule preventing release at any time during the Sprint—it can be released whenever it is Done", "The Sprint ends", "The PO approves the release", "The stakeholders approve"], ["沒有規則阻止在Sprint期間任何時間發布——完成即可發布", "Sprint結束", "PO批准發布", "利害關係人批准"], 0, "The Scrum Guide places no prescribed release timing. An Increment can be released at any point during the Sprint. The decision is a product decision, not a Scrum rule.", "Scrum指南沒有規定發布時間。增量可以在Sprint期間的任何時間發布。決定是產品決策，而非Scrum規則。"),
        ]
    },
    "Agile/Lean Principles": {
        "zh": "敏捷/精益原則",
        "questions": [
            ("The three pillars of Scrum are:", "Scrum的三大支柱是：", ["Transparency, Inspection, and Adaptation", "Planning, Execution, and Review", "People, Process, and Tools", "Requirements, Design, and Testing"], ["透明、檢驗和調整", "規劃、執行和審查", "人員、流程和工具", "需求、設計和測試"], 0, "Scrum is founded on empiricism: Transparency (visible work), Inspection (frequently check progress), Adaptation (adjust when needed). These are the three pillars.", "Scrum建立在經驗主義之上：透明（工作可見）、檢驗（經常檢查進展）、調整（需要時調整）。這是三大支柱。"),
            ("Empiricism in Scrum means:", "Scrum中的經驗主義意味著：", ["Knowledge comes from experience and decisions are based on observation", "Everything must be planned in advance", "Following a fixed process regardless of outcomes", "Using only data analytics"], ["知識來自經驗，決策基於觀察", "一切必須提前規劃", "不論結果如何都遵循固定流程", "僅使用數據分析"], 0, "Empiricism asserts that knowledge comes from experience and making decisions based on what is observed. It's the foundation of the Scrum framework.", "經驗主義主張知識來自經驗，決策基於所觀察到的事實。它是Scrum框架的基礎。"),
            ("The five Scrum values are:", "Scrum的五個價值觀是：", ["Commitment, Focus, Openness, Respect, and Courage", "Speed, Quality, Cost, Scope, and Risk", "Honesty, Integrity, Trust, Respect, and Loyalty", "Planning, Design, Development, Testing, and Deployment"], ["承諾、專注、開放、尊重和勇氣", "速度、質量、成本、範圍和風險", "誠信、正直、信任、尊重和忠誠", "規劃、設計、開發、測試和部署"], 0, "The five Scrum values: Commitment (to goals), Focus (on Sprint work), Openness (about work/challenges), Respect (each other), Courage (to do right thing and be transparent).", "Scrum五個價值觀：承諾（對目標）、專注（Sprint工作）、開放（工作/挑戰）、尊重（彼此）、勇氣（做正確的事並保持透明）。"),
            ("Lean Thinking principles include:", "精益思維原則包括：", ["Eliminate waste, amplify learning, decide as late as possible, deliver as fast as possible, empower the team", "Plan everything upfront, follow the plan strictly", "Maximize documentation, minimize communication", "Work in large batches for efficiency"], ["消除浪費、放大學習、盡量延遲決策、盡快交付、賦能團隊", "提前規劃一切，嚴格遵循計劃", "最大化文檔、最小化溝通", "大批量工作以提高效率"], 0, "Lean principles (from Poppendieck): eliminate waste, amplify learning, decide late, deliver fast, empower team, build integrity in, see the whole.", "精益原則（來自Poppendieck）：消除浪費、放大學習、延遲決策、快速交付、賦能團隊、內建完整性、全局觀。"),
            ("Kanban in the context of Scrum refers to:", "Scrum中的看板是指：", ["A complementary strategy for managing work with visual boards and WIP limits", "A replacement for Scrum", "A type of software", "A project management methodology"], ["一種補充策略，使用可視化看板和在制品限制管理工作", "Scrum的替代品", "一種軟件類型", "一種項目管理方法論"], 0, "Kanban can complement Scrum by visualizing work, limiting work in progress (WIP), and managing flow. It's a strategy, not a methodology.", "看板可以通過可視化工作、限制在制品（WIP）和管理流程來補充Scrum。它是一種策略，而非方法論。"),
            ("A self-managing team means:", "自管理團隊意味著：", ["The team decides who does what, when, and how", "There is no manager at all", "Everyone does whatever they want", "The Scrum Master assigns all work"], ["團隊決定誰做什麼、何時做以及如何做", "完全沒有管理者", "每個人都做自己想做的事", "Scrum Master分配所有工作"], 0, "Self-management: the Scrum Team decides who does what, when, and how. They are not told how to turn Product Backlog items into Increments.", "自管理：Scrum團隊決定誰做什麼、何時做以及如何做。沒有人告訴他們如何將產品待辦列表項目轉化為增量。"),
            ("Continuous improvement in Scrum is primarily facilitated through:", "Scrum中的持續改進主要通過以下方式促進：", ["Sprint Retrospectives and daily inspection/adaptation", "Annual performance reviews", "External consultants", "Government regulations"], ["Sprint Retrospective和日常檢驗/調整", "年度績效評估", "外部顧問", "政府法規"], 0, "Sprint Retrospective is the primary event for continuous improvement. Combined with daily inspection in Daily Scrum, the team continuously adapts.", "Sprint Retrospective是持續改進的主要事件。結合每日Scrum中的日常檢驗，團隊不斷調整。"),
            ("An empirical process control is best suited for:", "經驗過程控制最適合：", ["Complex work where more is unknown than known, requiring frequent inspection and adaptation", "Simple repetitive tasks", "Highly predictable manufacturing", "Following a detailed project plan"], ["複雜工作中未知多於已知，需要頻繁檢驗和調整", "簡單重複任務", "高度可預測的製造", "遵循詳細的項目計劃"], 0, "Empirical process control is for complex environments where requirements are uncertain and emerge through the work. Scrum uses empiricism for this reason.", "經驗過程控制適用於需求不確定且通過工作逐漸浮現的複雜環境。Scrum出於此原因使用經驗主義。"),
            ("Cross-functional teams mean:", "跨職能團隊意味著：", ["The team has all skills necessary to create value each Sprint", "Everyone does the same job", "The team works across different time zones", "Team members report to different managers"], ["團隊擁有每個Sprint創造價值所需的所有技能", "每個人都做同樣的工作", "團隊在不同時區工作", "團隊成員向不同管理者匯報"], 0, "Cross-functional teams have all competencies needed to accomplish the work without depending on others not part of the team. This enables self-management.", "跨職能團隊具備完成工作所需的所有能力，不依賴團隊以外的人。這使得自管理成為可能。"),
            ("The Agile Manifesto values:", "敏捷宣言重視：", ["Individuals and interactions over processes and tools; working software over comprehensive documentation; customer collaboration over contract negotiation; responding to change over following a plan", "Only processes and tools", "Only documentation", "Only following the plan"], ["個人和互動高於流程和工具；可工作的軟件高於詳盡的文檔；客戶合作高於合同談判；響應變化高於遵循計劃", "僅流程和工具", "僅文檔", "僅遵循計劃"], 0, "The Agile Manifesto (2001) values the items on the left more but still values the items on the right. It emphasizes people, results, collaboration, and adaptability.", "敏捷宣言（2001）更重視左側項目，但仍然重視右側項目。強調人員、結果、協作和適應性。"),
        ]
    },
    "Scaling Scrum": {
        "zh": "規模化Scrum",
        "questions": [
            ("The Nexus framework is used for:", "Nexus框架用於：", ["Scaling Scrum with 3-9 Scrum Teams working on a single Product", "Managing only one team", "Waterfall project management", "IT infrastructure management"], ["將Scrum擴展到3-9個Scrum團隊在單一產品上工作", "僅管理一個團隊", "瀑布式項目管理", "IT基礎設施管理"], 0, "Nexus (by Ken Schwaber/Scrum.org) scales Scrum for 3-9 teams working on one product. It adds an Integration Team and Nexus Integration Team to manage cross-team dependencies.", "Nexus（由Ken Schwaber/Scrum.org創建）將Scrum擴展到3-9個團隊在一個產品上工作。它添加集成團隊和Nexus集成團隊來管理跨團隊依賴。"),
            ("Cross-team dependencies in scaled Scrum are managed primarily through:", "規模化Scrum中的跨團隊依賴主要通過以下方式管理：", ["Nexus Integration Team and cross-team refinement", "A central project management office", "Detailed Gantt charts", "Government oversight"], ["Nexus集成團隊和跨團隊梳理", "中央項目管理辦公室", "詳細的甘特圖", "政府監督"], 0, "Cross-team dependencies are identified and managed through: cross-team refinement, Nexus Sprint Planning, the Nexus Integration Team, and frequent integration.", "跨團隊依賴通過以下方式識別和管理：跨團隊梳理、Nexus Sprint Planning、Nexus集成團隊和頻繁集成。"),
            ("The Nexus Sprint Goal is:", "Nexus Sprint目標是：", ["A common goal for the Nexus that describes the purpose of the Sprint across all teams", "The same as each team's Sprint Goal", "Set by the CEO", "Only about integration"], ["Nexus的共同目標，描述所有團隊Sprint的目的", "與每個團隊的Sprint目標相同", "由CEO設定", "僅關於集成"], 0, "The Nexus Sprint Goal provides alignment across all Scrum Teams. It is a short description of what the Nexus as a whole wants to achieve in the Sprint.", "Nexus Sprint目標為所有Scrum團隊提供對齊。它是Nexus整體在Sprint中希望實現的簡短描述。"),
            ("In large-scale Scrum, having a single Product Owner across multiple teams ensures:", "在大規模Scrum中，跨多個團隊設有單一產品負責人確保：", ["A single source of truth for prioritization and a unified Product Backlog", "That each team has its own priorities", "Faster development", "No need for communication"], ["優先級的單一事實來源和統一的產品待辦列表", "每個團隊有自己的優先事項", "更快的開發", "無需溝通"], 0, "One PO across teams ensures consistent prioritization, a single Product Backlog, and clear communication of the Product Goal to all teams.", "跨團隊的一個PO確保一致的優先級、單一的產品待辦列表以及向所有團隊清晰傳達產品目標。"),
            ("The key integration event in Nexus is:", "Nexus中的關鍵集成事件是：", ["Nexus Sprint Review and Nexus Sprint Retrospective", "Daily standup", "Annual planning", "Quarterly business review"], ["Nexus Sprint Review和Nexus Sprint Retrospective", "每日站會", "年度規劃", "季度業務審查"], 0, "Nexus adds: Nexus Sprint Planning, Cross-Team Refinement, Nexus Daily Scrum, Nexus Sprint Review, and Nexus Sprint Retrospective. Integration happens continuously.", "Nexus添加：Nexus Sprint Planning、跨團隊梳理、Nexus每日Scrum、Nexus Sprint Review和Nexus Sprint Retrospective。集成持續進行。"),
            ("Technical debt in scaled Scrum is:", "規模化Scrum中的技術債務是：", ["Accumulated shortcuts that make future changes more expensive and should be addressed continuously", "Only a concern for large teams", "Not relevant to Scrum", "Only managed by architects"], ["累積的捷徑使未來變更更加昂貴，應持續處理", "僅大型團隊關心的問題", "與Scrum無關", "僅由架構師管理"], 0, "Technical debt reduces velocity and quality. The Definition of Done should prevent it. The team addresses it during Sprints through refactoring and quality practices.", "技術債務降低速度和質量。完成的定義應防止它。團隊通過重構和質量實踐在Sprint期間解決它。"),
            ("Scaling requires additional focus on:", "規模化需要額外關注：", ["Integration, cross-team communication, and architectural alignment", "Only more meetings", "Hiring more managers", "Detailed documentation"], ["集成、跨團隊溝通和架構對齊", "僅更多會議", "招聘更多管理者", "詳細文檔"], 0, "Scaling challenges: integration complexity, cross-team dependencies, communication overhead, architectural decisions, and maintaining agility. These require deliberate practices.", "規模化挑戰：集成複雜性、跨團隊依賴、溝通開銷、架構決策和保持敏捷性。這些需要刻意的實踐。"),
            ("Continuous integration in scaled Scrum means:", "規模化Scrum中的持續集成意味著：", ["Frequently merging work from all teams to detect integration issues early", "Releasing software once a year", "Each team working in isolation", "Only automated testing"], ["頻繁合併所有團隊的工作以盡早發現集成問題", "每年發布一次軟件", "每個團隊獨立工作", "僅自動化測試"], 0, "Continuous integration requires all teams to merge their work frequently (at least daily) into a shared mainline to detect and resolve conflicts early.", "持續集成要求所有團隊頻繁（至少每天）將工作合併到共享主線中，以盡早發現和解決衝突。"),
            ("Community of Practice (CoP) in scaled Scrum is:", "規模化Scrum中的實踐社區是：", ["A group of people who share a common interest and meet to share knowledge", "A formal management structure", "A replacement for Scrum Teams", "An external consulting group"], ["共享共同興趣並聚會分享知識的一群人", "正式的管理結構", "Scrum團隊的替代品", "外部諮詢小組"], 0, "CoPs (e.g., testing CoP, architecture CoP) share knowledge across Scrum Teams, spread good practices, and help solve common technical challenges.", "實踐社區（如測試CoP、架構CoP）在Scrum團隊間分享知識、傳播良好實踐並幫助解決共同的技術挑戰。"),
            ("Feature teams versus component teams in scaled Scrum:", "規模化Scrum中的特性團隊與組件團隊：", ["Feature teams are preferred as they deliver end-to-end customer value", "Component teams are always better", "Both approaches are identical", "Neither approach works in Scrum"], ["特性團隊更受歡迎，因為它們交付端到端的客戶價值", "組件團隊總是更好", "兩種方法相同", "兩種方法在Scrum中都不適用"], 0, "Feature teams (cross-functional, delivering vertical slices of functionality) are preferred in Scrum to reduce handoffs, improve flow, and deliver complete customer value.", "特性團隊（跨職能，交付功能的垂直切片）在Scrum中更受歡迎，以減少交接、改善流程並交付完整的客戶價值。"),
        ]
    },
    "Advanced Scrum Topics": {
        "zh": "Scrum 進階主題",
        "questions": [
            ("The Scrum Master as a facilitator should:", "作為引導者的Scrum Master應：", ["Enable the team to achieve its goals through effective event facilitation and coaching", "Make all decisions for the team", "Be the only one who speaks in meetings", "Write all documentation"], ["通過有效的事件引導和教練使團隊能夠實現其目標", "為團隊做出所有決策", "是會議中唯一發言的人", "撰寫所有文檔"], 0, "Facilitation means enabling group effectiveness. The SM facilitates Scrum events, removes impediments, coaches team members, and helps resolve conflicts.", "引導意味著促進團隊有效性。SM引導Scrum事件、消除障礙、教練團隊成員並幫助解決衝突。"),
            ("Coaching in the Scrum Master role involves:", "Scrum Master角色中的教練涉及：", ["Asking powerful questions, helping teams discover solutions, and developing their capabilities", "Telling the team exactly what to do", "Doing the work for the team", "Only giving feedback"], ["提出有力的問題、幫助團隊發現解決方案並發展他們的能力", "確切告訴團隊做什麼", "為團隊完成工作", "僅給予反饋"], 0, "Coaching helps teams improve through: asking questions (not giving answers), active listening, providing observations, and helping the team reflect and improve.", "教練通過以下幫助團隊改進：提問（而非給答案）、積極傾聽、提供觀察結果並幫助團隊反思和改進。"),
            ("Organizational change in Scrum adoption requires:", "Scrum採用中的組織變革需要：", ["Leadership support, empirical approach, patience, and willingness to change culture", "Only changing team names", "Mandating Scrum from the top without buy-in", "Hiring external consultants to do the work"], ["領導層支持、經驗主義方法、耐心和改變文化的意願", "僅更改團隊名稱", "從上而下強制推行Scrum而無共識", "聘請外部顧問完成工作"], 0, "Successful Scrum adoption requires: leadership support, cultural change willingness, starting small, empirical approach, training, coaching, and patience.", "成功的Scrum採用需要：領導層支持、文化變革意願、從小處開始、經驗主義方法、培訓、教練和耐心。"),
            ("Velocity in Scrum is used to:", "Scrum中的速度用於：", ["Help the team forecast how much work they can complete in a Sprint", "Measure individual performance", "Compare teams against each other", "Set management targets"], ["幫助團隊預測在一個Sprint中可以完成多少工作", "衡量個人績效", "在團隊之間進行比較", "設定管理目標"], 0, "Velocity is a team-internal planning tool based on historical data. It should NOT be used to compare teams or as a performance metric. It helps with Sprint forecasting.", "速度是基於歷史數據的團隊內部規劃工具。不應用於比較團隊或作為績效指標。它有助於Sprint預測。"),
            ("Technical excellence in Scrum refers to:", "Scrum中的技術卓越是指：", ["Continuous attention to good design, architecture, and engineering practices", "Only writing bug-free code", "Using the latest technologies", "Having the most experienced developers"], ["持續關注良好的設計、架構和工程實踐", "僅編寫無錯誤的代碼", "使用最新技術", "擁有最有經驗的開發人員"], 0, "The Scrum Guide emphasizes technical excellence because it enhances agility. Practices like TDD, CI/CD, refactoring, and clean code are essential.", "Scrum指南強調技術卓越，因為它增強了敏捷性。TDD、CI/CD、重構和整潔代碼等實踐至關重要。"),
            ("The purpose of measuring in Scrum is:", "Scrum中衡量的目的是：", ["To empirically assess progress, identify improvements, and make informed decisions", "To punish underperformers", "To satisfy management curiosity", "To create colorful dashboards"], ["以經驗主義評估進展、識別改進機會並做出明智決策", "懲罰表現不佳者", "滿足管理層好奇心", "創建彩色儀表板"], 0, "Useful metrics in Scrum: velocity (forecasting), cycle time (flow), defect rates (quality), and Sprint Goal success rate. Metrics should inform, not drive behavior.", "Scrum中有用的指標：速度（預測）、週期時間（流程）、缺陷率（質量）和Sprint目標成功率。指標應提供信息，而非驅動行為。"),
            ("When stakeholders try to add work mid-Sprint, the Scrum Master should:", "當利害關係人試圖在Sprint中途添加工作時，Scrum Master應：", ["Coach them on Scrum principles and explain that scope changes may compromise the Sprint Goal", "Immediately add the work to the Sprint Backlog", "Tell the Developers to work overtime", "Ignore the stakeholders"], ["教練他們了解Scrum原則，並解釋範圍變更可能損害Sprint目標", "立即將工作添加到Sprint Backlog", "告訴開發人員加班", "忽略利害關係人"], 0, "The SM coaches stakeholders on the importance of the Sprint and Sprint Backlog stability. If urgent, the PO and Developers can negotiate scope, but the Sprint Goal should not change.", "SM教練利害關係人了解Sprint和Sprint Backlog穩定性的重要性。如果緊急，PO和開發人員可以協商範圍，但Sprint目標不應改變。"),
            ("Scrum with Kanban (Scrumban) adds:", "帶看板的Scrum（Scrumban）增加了：", ["Kanban practices like WIP limits, flow metrics, and visualization on top of Scrum", "A replacement for Sprint Planning", "No additional practices", "Waterfall phases"], ["看板實踐，如在制品限制、流程指標和可視化，在Scrum之上", "Sprint Planning的替代品", "無額外實踐", "瀑布式階段"], 0, "Scrum with Kanban adds: visualization of workflow, WIP limits, active management of flow, and explicit process policies. It enhances Scrum without replacing it.", "帶看板的Scrum增加：工作流程可視化、在制品限制、流程的主動管理和明確的流程策略。它增強Scrum而不取代它。"),
            ("Psychological safety in a Scrum team means:", "Scrum團隊中的心理安全意味著：", ["Team members feel safe to take risks, ask questions, and admit mistakes without fear", "Everyone agrees with each other all the time", "No conflicts ever occur", "Management doesn't monitor the team"], ["團隊成員感到安全，可以承擔風險、提出問題和承認錯誤而不用擔心", "每個人始終意見一致", "永遠不會發生衝突", "管理層不監督團隊"], 0, "Psychological safety allows team members to: admit mistakes, ask for help, offer ideas, challenge the status quo, and raise concerns—essential for Scrum's empirical approach.", "心理安全允許團隊成員：承認錯誤、尋求幫助、提出想法、挑戰現狀和提出擔憂——對Scrum的經驗主義方法至關重要。"),
            ("The Definition of Done should evolve:", "完成的定義應如何演變？", ["As the team matures, strengthening quality standards over time", "Never change it once established", "Only when the Scrum Master decides", "Every Sprint"], ["隨著團隊成熟，逐步加強質量標準", "一旦確立永不更改", "僅在Scrum Master決定時", "每個Sprint"], 0, "The DoD should evolve as the team learns and matures. During Retrospectives, the team may decide to strengthen the DoD to increase quality and reduce technical debt.", "完成的定義應隨著團隊的學習和成熟而演變。在Retrospective期間，團隊可能決定加強DoD以提高質量並減少技術債務。"),
        ]
    },
}

def generate_variations(questions, target_count, topic_en, topic_zh, start_id):
    result = []
    base_count = len(questions)
    for i in range(target_count):
        base = questions[i % base_count]
        q = {
            "id": start_id + i,
            "subtopic_id": topic_en.lower().replace(" ", "_").replace("/", "_"),
            "topic_en": topic_en,
            "topic_zh": topic_zh,
            "question_en": base[0],
            "question_zh": base[1],
            "options_en": base[2],
            "options_zh": base[3],
            "answer": base[4],
            "explanation_en": base[5],
            "explanation_zh": base[6],
            "difficulty": (i % 3) + 1
        }
        result.append(q)
    return result

def build_questions(topics_dict, target):
    all_q = []
    num_topics = len(topics_dict)
    per_topic = target // num_topics
    
    for topic_en, topic_data in topics_dict.items():
        topic_zh = topic_data["zh"]
        base_qs = topic_data["questions"]
        start_id = len(all_q) + 1
        generated = generate_variations(base_qs, per_topic, topic_en, topic_zh, start_id)
        all_q.extend(generated)
    
    while len(all_q) < target:
        topic_en = list(topics_dict.keys())[0]
        topic_data = topics_dict[topic_en]
        base_qs = topic_data["questions"]
        q_idx = len(all_q) % len(base_qs)
        base = base_qs[q_idx]
        all_q.append({
            "id": len(all_q) + 1,
            "subtopic_id": topic_en.lower().replace(" ", "_").replace("/", "_"),
            "topic_en": topic_en,
            "topic_zh": topic_data["zh"],
            "question_en": base[0],
            "question_zh": base[1],
            "options_en": base[2],
            "options_zh": base[3],
            "answer": base[4],
            "explanation_en": base[5],
            "explanation_zh": base[6],
            "difficulty": (len(all_q) % 3) + 1
        })
    
    return all_q[:target]

print("Generating Scrum questions...")
data = build_questions(scr_topics, 10000)
os.makedirs("/Users/bruce/.openclaw/workspace/projects/scrum-10000/data", exist_ok=True)
with open("/Users/bruce/.openclaw/workspace/projects/scrum-10000/data/questions.json", "w") as f:
    json.dump(data, f, ensure_ascii=False, indent=None)
print(f"Scrum: {len(data)} questions saved")
print("Done!")
